### ISSUE TITLE
Renaming "Anoma" to "Namada"

### ISSUE THREAD

**Issue by gnosed** [anoma/namada#1]
To be fully consistent with the rebranding, following points should be renamed: 
- [x] the CLI commands anoma* to namada*
- [x] config folders .anoma to .namada
- [x] same for logs and env variables
- [x] rust crates

**Comment by arafey** [comment]
Rust crates (and therefore logs) now use "namada". Config folders and env variables are only relevant to developers, node operators, etc so branding is not critical/not worth the effort of refactoring.
