### ISSUE TITLE
Have a Cargo workspace for wasm crates

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#102]
We have the following crates
- [x] `wasm/wasm_source`
- [x] `wasm/tx_template`
- [x] `wasm/vp_template`
- [ ] `wasm_for_tests/wasm_source`

These crates share the same sort of directory structure, Makefile targets and Rust dependencies (`Cargo.lock`) so it could make sense to contain them in a Cargo workspace e.g. located at `wasm/Cargo.toml` (and have `wasm_for_tests/` move under the `wasm/` directory).

**Comment by tzemanovic** [comment]
everything except for `wasm_for_tests` is now in wasm workspace (#258)

**Comment by cwgoes** [comment]
@james-chf is this still relevant?

**Comment by james-chf** [comment]
It's still relevant and should eventually be done - it would mean all our wasms are built under one workspace so they would be easier to work with and keep in sync e.g. only one `Cargo.toml` to patch and keep updated, one less `Cargo.lock` file in the repo, etc. 

One issue currently is that there are various duplicate references and hardcoded paths to our `wasm_for_tests` directory in the repo at the moment, that should be cleaned up first before we migrate the folder - I've linked https://github.com/anoma/namada/pull/893 which starts on doing that.

**Comment by james-chf** [comment]
After https://github.com/anoma/namada/pull/893 lands this should be fairly straightforward to do
