### ISSUE TITLE
allow to set a default ledger address

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#103]
depends on anoma/namada#47 

The client commands that interact with the ledger have `--ledger-address` optional arg, but its default value is currently hard-coded in the CLI. It would be convenient to have a way to set the default value in the config instead

**Comment by cwgoes** [comment]
@tzemanovic is this still relevant?

**Comment by tzemanovic** [comment]
> @tzemanovic is this still relevant?

yes, but blocked by #47

**Comment by tzemanovic** [comment]
done in #2466
