### ISSUE TITLE
Handle errors correctly in tower-abci

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#1044]
Noted by @Fraccaman, see https://github.com/heliaxdev/tower-abci/blob/main/src/server.rs#L192

May also relate to https://github.com/anoma/namada/issues/204

**Comment by tzemanovic** [comment]
yeah, this crashes the ledger in case e.g. the `Info` queue is at full capacity and it cannot handle any more requests

**Comment by cwgoes** [comment]
closed by https://github.com/anoma/namada/pull/2152
