### ISSUE TITLE
PoS - verify validator keys ownership with signatures

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#106]
For the on-chain validator account creation and for transactions to change consensus key (pending on anoma/namada#36), we must also require that a signature with the consensus key is attached to the transactions to verify the key's ownership. Depends on anoma/namada#85 to be able to attach multiple signatures to a tx.

For this, we should update the client commands and the PoS VP to enforce this rule.

**Comment by tzemanovic** [comment]
another way would be to have some "challenge" in the ledger's state that `init-validator` txs would have to sign over to verify ownership of the relevant PKs that they're trying to use for their validator account - sketched out here https://excalidraw.com/#json=GzskiES12LxvLl-7Y_wGk,qPn9jmoqX2VUnMbJSm86hQ

Other PKs we might want to verify are the protocol key and eth bridge cold and hot key.

For genesis validators, we might need to do something else as those are created before there's any ledger or chain ID. We can e.g. have some pseudo random hash that we ask validators to sign over with those keys.

**Comment by cwgoes** [comment]
@brentstone can you take this on as part of the PoS work?

**Comment by tzemanovic** [comment]
The genesis part will be solved by #685, but we'll still need something for `init-validator` tx. I think we could use multisig signatures for this (#81/#85)

**Comment by tzemanovic** [comment]
in #1840 we're authorizing pre-genesis init-validator tx with all these validator keys: https://github.com/anoma/namada/blob/3968fef59ec1f7b41cd79c236a6d98c8eaec7aa2/genesis/localnet/src/pre-genesis/validator-0/transactions.toml#L9-L31

We should use multisig to do the same for the regular init-validator tx

**Comment by tzemanovic** [comment]
we still need on-chain init-validator sigs check
