### ISSUE TITLE
Check whether the Ethereum oracle should be reconfigured after every epoch transition

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#1080]
After PR https://github.com/anoma/namada/pull/1079, the Ethereum event oracle will effectively only be configured once when a validator node starts up. It a parameter affecting the oracle is changed on-chain (at the moment, this is just the `min_confirmations` parameter) e.g. via a governance proposal, any running Ethereum oracle won't automatically be reconfigured - validators will need to restart their node.

If a validator is running an Ethereum oracle, they should check whether it needs reconfiguring after every epoch transition (e.g. a governance proposal may have passed to change a relevant parameter like `min_confirmations`), and do so.

**Comment by kunimei** [comment]
good

**Comment by sug0** [comment]
Closed by https://github.com/anoma/namada/pull/1210
