### ISSUE TITLE
Ensure ERC20 base units map to `token::Amount` type correctly

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#1085]
In the smart contracts, ERC20 amounts over the Ethereum bridge are represented in ERC20 base units as  `uint256`.

```solidity
    struct NamadaTransfer {
        address from;
        uint256 amount;
        string to;
    }

    struct ERC20Transfer {
        address from;
        address to;
        uint256 amount;
        string feeFrom;
        uint256 fee;
    }
```

On Namada, we have an `Amount` type which uses units of `micros` (10^-6).
https://github.com/anoma/namada/blob/76169dcdaf15911ac2f69dec78604e18c4c5b259/core/src/types/token.rs#L32-L34

Currently, as of `eth-bridge-integration` commit aeb3a4979390a9dd3251a0383ee769179e3329c6, 1 ERC20 unit translates to 1 micro.

We need to ensure: ERC20 base units are correctly translated to/from `Amount` type, in the sense that it is explicitly specified how 1 ERC20 base unit should translate to `Amount`. e.g. it should perhaps translate to 10^6 `micros` rather than 1 mico. Since we use `u64` type for `micros`, there is also maximum limit to how much should be sent in a transfer (something like `u64::MAX * 10^-6` which is roughly ~18.5bn) - though such transfers shouldn't be that large in practice (e.g. due to bridge token whitelisting/supply caps), we should make sure if a transfer of such an amount was attempted it is handled robustly.

**Comment by james-chf** [comment]
NB: in latest `eth-bridge-integration` - we do currently panic if we encounter an `Amount` type in a transfer which is larger than `u64::MAX`.

https://github.com/anoma/namada/blob/f4a9d94d598ac2e1dd21455392e34c50da15c2fd/apps/src/lib/node/ledger/ethereum_node/events.rs#L552-L561

**Comment by sug0** [comment]
Closed by https://github.com/anoma/namada/pull/1282
