### ISSUE TITLE
`token::Amount` may not be able to fully represent some wrapped token amounts

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#1089]
On Namada, we have an `Amount` type which uses units of `micros` (10^-6).
https://github.com/anoma/namada/blob/76169dcdaf15911ac2f69dec78604e18c4c5b259/core/src/types/token.rs#L32-L34

Since we use `u64` type for `micros`, the is maximum limit for how much a single `Amount` can hold is something like `u64::MAX * 10^-6` which is roughly ~18.5bn full units. We use `Amount` type to represent amounts of native tokens on Namada as well as wrapped tokens from other chains. On Ethereum, ERC20 tokens can have supplies much larger than ~18.5bn e.g. [SHIB](https://etherscan.io/token/0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce). We want to be able to represent any wrapped token amounts in our `Amount` type. 

Multiple possible solutions including changing our `Amount` type to support a higher supply (e.g. [num256::Uint256](https://docs.rs/num256/0.1.3/num256/uint256/struct.Uint256.html) instead of u64), or using a different `Amount` type entirely for wrapped tokens.

**Comment by james-chf** [comment]
Have tagged this issue https://github.com/anoma/namada/labels/IBC as well as https://github.com/anoma/namada/labels/ethereum-bridge as I presume there are types of tokens that could come over IBC, that could be affected by this issue as well

**Comment by sug0** [comment]
Closed by https://github.com/anoma/namada/pull/1282
