### ISSUE TITLE
Formatting token amounts should support placing the decimal point in different places

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#1090]
When displaying/interacting with token amounts in the CLI, we work with the token amount in either base units (10^1) or micros (10^-6). 

For some tokens, it makes sense to expect or display the decimal point in a different place e.g. for wrapped ERC20s, we will want to match wherever the original ERC20 puts the decimal point. This is different depending on the ERC20 (and some ERC20s do not use a decimal point at all).

For each token type (including multitoken tokens), we should store details of where a decimal point should be displayed (this could be on-chain, under the token's storage subspace, so that it could be easily queried).

From the UX side, CLI commands to do with token amounts like `namadac balance`, `namadac transfer` would need to be updated.

**Comment by sug0** [comment]
Closed by https://github.com/anoma/namada/pull/1282
