### ISSUE TITLE
Remove `wasm_for_tests/*.wasm` blobs from the repo

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#111]
We have `*.wasm` blobs under `wasm_for_tests/`, which are built from that crate. We should remove these blobs from the repo and expect them to be built (or downloaded?), something similar to what we do for the WASMs built from the `wasm/wasm_source/` crate.

**Comment by diceride** [comment]
Alternatively, we could (1) store the blobs as attachments in the GitHub releases and theen (2) download them over HTTPS in the build.rs script file.

Deno uses a similar approach, where binary blobs of the v8 JavaScript engine are stored as attachments of GitHub releases  (https://github.com/denoland/rusty_v8/releases). 

Example build.rs script file

https://github.com/denoland/rusty_v8/tree/0b299420bd8756a802331479057e37baeb89639f/build.rs#L297


And here is the corresponding GitHub action

https://github.com/denoland/rusty_v8/tree/0b299420bd8756a802331479057e37baeb89639f/.github/workflows/ci.yml#L185

**Comment by james-chf** [comment]
Yeah having the wasms built and published alongside each commit of the repo could be useful, moreso for our real `*.wasm` blobs (i.e. under `wasm/`). For the `wasm_for_tests` blobs, they are needed to run the e2e tests. Currently these test wasms are not built in CI so the ones in the repo can become stale . The same sort of approach of publishing artifacts alongside commits rather than inside them I think would be good to apply to `wasm/checksums.json`.
