### ISSUE TITLE
PoS: update PoS VP for lazy collections storage

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#1126]
follow-up to #16 (implemented in #740), the PoS VP validation has to be updated for the new storage. We have helpers on the lazy collections that can be used to replace the data accumulation. The starting point for this may be to revert https://github.com/anoma/namada/commit/3958ed6c387d0e41d50be807ea5d2c4e991782b5.

I'm setting this as low prio for now as it's not critical for namada as the main purpose of it is to allow tx programmabilty, which is out of scope. The authorization of PoS actions (e.g. bond, unbond, withdraw, update validator commission rate) has already been updated in #740 and correct application of the actions is ensured by tx whitelisting (https://github.com/anoma/anoma/issues/876) - our pre-built txs will simply fail if you're for example trying to bond tokens you don't have or unbond tokens you didn't stake.

**Comment by cwgoes** [comment]
Not applicable anymore.
