### ISSUE TITLE
Memory leak when running the ledger

### ISSUE THREAD

**Issue by mariari** [anoma/namada#1135]
If i leave the ledger on for too long, it seems to leak memory over time.

https://pomf2.lain.la/f/qz65ico1.png

Is an example of letting namada run over night on my machine

**Comment by Fraccaman** [comment]
I think this is due to rocksdb cache settings (but its a guess). It will eat up most of the memory but it never gets killed due to oom. We have a configurable variable you could try to set in the config called `block_cache_bytes` under `shell`

**Comment by cwgoes** [comment]
@yito88 Can you take a look at this?
