### ISSUE TITLE
Inflation System article slight error

### ISSUE THREAD

**Issue by mariari** [anoma/namada#1183]
It seems that in 

https://specs.namada.net/economics/inflation-system.html

we calculate the cap for the tokens as follows:

`CapSPA​−Epoch ​= SNAM​∗CapSPA​​/EpochsPerYear (separate value for each A)`

It seems that the SNAM should be SSPA which is per token

@brentstone

**Comment by cwgoes** [comment]
Yes, all caps should be denominated in fractional inflation, so they will include `S_nam`. We should not need to reason about the total supply of any asset. @mariari does this make sense? are we not doing this at the moment?
