### ISSUE TITLE
PoS - add validation tests

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#12]
add tests for the validation function

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762962686238) by [Unito](https://www.unito.io)

**Comment by brentstone** [comment]
> @brentstone do you know what the status of this is?

This issue may be addressed by the PoS VP state machine tests, and these validation tests will probably have to be tweaked a bit for the new PoS storage. @tzemanovic can comment on this if I've missed something.

**Comment by tzemanovic** [comment]
> > @brentstone do you know what the status of this is?
> 
> This issue may be addressed by the PoS VP state machine tests, and these validation tests will probably have to be tweaked a bit for the new PoS storage. @tzemanovic can comment on this if I've missed something.

that's right - the valid PoS actions (the supported txs) were covered, but will need to be updated together with the storage changed from #740 and the VP itself)

**Comment by cwgoes** [comment]
No longer applicable.
