### ISSUE TITLE
integrate `tracing-appender` for logging into files

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#122]

**Comment by cwgoes** [comment]
@tzemanovic can you clarify this a bit / is this issue still relevant?

**Comment by tzemanovic** [comment]
> @tzemanovic can you clarify this a bit / is this issue still relevant?

This crate makes it easy to setup a non-blocking rolling file logger https://github.com/tokio-rs/tracing/tree/master/tracing-appender#non-blocking-rolling-file-appender, it would be nice to have. The usage should be described somewhere in user docs
