### ISSUE TITLE
Enforce ethereum bridge caps

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#1234]
While the Ethereum smart contracts should enforce token caps, this should also be enforced namada-side. We should also come up with a strategy for when the are more tokens on the bridge than allowed by the cap (because a cap was lowered).

**Comment by sug0** [comment]
Regarding:
> come up with a strategy for when the are more tokens on the bridge than allowed by the cap

Configuring token caps on the smart contracts can take into account the tokens that are already in circulation. it's worse UX for governance, but whatever.

**Comment by sug0** [comment]
Regarding the first part, it's a non-issue as well, since token caps are enforced in Ethereum, and a quorum of validators agree on valid events.
