### ISSUE TITLE
PoS - integrate cubic slashing

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#124]
spec: https://specs.anoma.net/master/architecture/economics/proof-of-stake/cubic-slashing.html

**Comment by cwgoes** [comment]
@brentstone this might be a duplicate?

**Comment by brentstone** [comment]
> @brentstone this might be a duplicate?

This issue is referenced in PR #892, and I think it's the only issue specifically for cubic slashing, unless I've missed another.

**Comment by brentstone** [comment]
Completed in #892
