### ISSUE TITLE
improve error handling in init_chain

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#126]
there are some `unwrap`s in the init_chain (and possibly other shell's methods?) - ideally these should be propagate up to the method's Result

**Comment by cwgoes** [comment]
@tzemanovic is this still relevant?

**Comment by tzemanovic** [comment]
> @tzemanovic is this still relevant?

I'd say so, but it's probably not a high priority for now

**Comment by tzemanovic** [comment]
On a second thought, it's better to crash on any errors than to return the errors back to tendermint as it's clearer to see what happened. With the new genesis #2088 and #2130, we should be able to prevent invalid chain configurations. Any other issues are not recoverable
