### ISSUE TITLE
Remove Epoch 0

### ISSUE THREAD

**Issue by bengtlofgren** [anoma/namada#1265]
As @juped mentioned, we should not have an epoch 0. It makes sense for the Namada blockchain to start at Epoch 1.

**Comment by sug0** [comment]
not really a bug I'd say, and more trouble than it's worth getting into. a lot of logic relies on the fact epochs start counting from 0. who knows what would break from meddling with that logic

**Comment by tzemanovic** [comment]
There is no strong motivation to go with this change. Initializing state at epoch 0 is fine as init_chain doesn't commit anything and the first block simply begins at epoch 0 without any of the epoch increment logic that's applied after epoch 0
