### ISSUE TITLE
Namada validators should process relevant events from Ethereum smart contracts

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#127]
- [x] Integrate a full node into the ledger
- [x] Add the ability to subscribe and deserialize ethereum events
- [x] Events with relevant number of confirmations only should be sent to the ledger
- [x] Events should be added to vote extensions
- [x] #144 
- [x] #197
- [x] Mocks of ethereum events should be created for testing.

**Comment by cwgoes** [comment]
@batconjurer looks like this can be closed?
