### ISSUE TITLE
Add changed keys wrapper for `WlStorage`

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1305]
Introduce a `WlStorage` wrapper that keeps track of changed storage keys, due to writes or removals. The wrapper should have a `finalize()` method, that returns a `BTreeSet<Key>` of changed storage keys. It is not uncommon for me (personally) to forget adding storage key changes to a set of changed keys, so this abstraction would take this burden away by keeping track of the changed keys internally.

**Comment by sug0** [comment]
(already present in the `WriteLog`, the relevant method being `get_keys()`)

**Comment by sug0** [comment]
(already present in the `WriteLog`, the relevant method being `get_keys()`)

**Comment by tzemanovic** [comment]
@sug0 I'm not sure if I follow, doesn't the write log already contain this?

**Comment by sug0** [comment]
@tzemanovic guess so. the motivation for this was that in the ethereum bridge code we were manually updating a `BTreeSet` of changed keys, and would forget keys sometimes. the bigger issue here is a need for a refactor on the eth bridge code :D
