### ISSUE TITLE
Submitting namada validator set updates to Ethereum

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#131]
- [x] Namada validators should have accounts on Ethereum
- [ ] Write a VP to check validator eth keys are in storage
- [x] Write RPC method to query validator set update proofs
- [x] Write relayer code to submit validator set update to Eth
- [ ] In case a valset upd proof is not automatically constructed within the course of an epoch, it might be nice to build a tool to create a proof offline (low prio)

These tasks are currently not top priority, but ultimately required in the future:
- [ ] Add the submission of validator set updates to `PrepareProposal` for the first block proposer of a new epoch
- [ ] Events from Ethereum registering a successful validator set update should reimburse the block proposer during `FinalizeBlock` from the treasury

It is still to be decided how to do the following:
 - retry strategies if a validator set update fails
 - gas oracles for Ethereum
 - the reimbursement amount and strategy

**Comment by cwgoes** [comment]
@batconjurer @james-chf what's the status of this / can we update the issue?

**Comment by batconjurer** [comment]
@sug0, can we close this?

**Comment by sug0** [comment]
guess so. the remaining requirements for validator set updates are duped in #242
