### ISSUE TITLE
The data can not synchronize anymore after stop and restart system

### ISSUE THREAD

**Issue by atomstaker** [anoma/namada#1331]
after system is stop ,then restart system again, the data can not continue to synchronize anymore
not stable,sometimes there are panic from tendermint,then system restart, the system stop
![image](https://user-images.githubusercontent.com/128807593/236136572-1979252f-d3f7-4511-b729-045e9e899131.png)

**Comment by cwgoes** [comment]
Can you provide a full log? We'll need more information to debug what might have been happening on your machine.

**Comment by cwgoes** [comment]
Closing for now, please reopen if this reoccurs.
