### ISSUE TITLE
MASP CLI commands user feedback 

### ISSUE THREAD

**Issue by gnosed** [anoma/namada#134]
### Display payment key after its generation 
When an user generates a payment key with the command: 
```bash
anomaw masp gen-addr --key <a-previously-created-spending-key-alias> --alias <new-payment-key-alias>
```
It is desirable to display the generated payment key just after or before the current displayed message.
What's currently displayed: 
```bash
gnosed@mastoc:~/anoma$ anomaw masp gen-addr --key masp-key-1 --alias pay-masp-key-1
Successfully generated a payment address with the following alias: pay-masp-key-1
```
What's desired:
```bash
gnosed@mastoc:~/anoma$ anomaw masp gen-addr --key masp-key-1 --alias pay-masp-key-1
Successfully generated a payment address with the following alias: pay-masp-key-1
Payment address: patest1qeupa0plvhzxxpcyg56xjl5x4j8sx6xrdj0px4sgpf9kk0l6djaa0kzg4x37jcdglyhacp6ull7
```
In general, if the user generates a payment key, it's to share it with someone. In the current implementation, if the user wants to share the payment address he needs to execute `anomaw masp list-keys` and search for the previously generated alias. This an extra step for the user.

### (optional) Display viewing key after a new spending key was generated
Similarly to the previous comment, we could also display the corresponding viewing key after the generation of the spending key. In this case, sharing the viewing key would be less common, but good to keep it in mind.

**Comment by cwgoes** [comment]
Probably out-of-date.
