### ISSUE TITLE
Handle multiple WASMs in a single transaction

### ISSUE THREAD

**Issue by yito88** [anoma/namada#1356]
We want to put multiple IBC messages into a transaction so that an IBC relayer (Hermes) can request IBC transactions efficiently.

P.S. By supporting a transaction with multiple WASMs

**Comment by cwgoes** [comment]
We should do this in a general way, not an IBC-specific way - it should be possible to compose transactions, right? (we should allow multiple WASM blobs to be executed in sequence)

**Comment by cwgoes** [comment]
No, the multiple WASMs should be atomic, that's typically the desired user behaviour.

**Comment by cwgoes** [comment]
@grarco Would it be possible to re-scope this to batch IBC transactions only?
