### ISSUE TITLE
Failed to parse the argument net-address error: AddrParseError(Socket) when using FQDN

### ISSUE THREAD

**Issue by msobh13** [anoma/namada#1363]
i would like to  use FQDN in the namada client utils init-genesis-validator  command . but it give an err . 

Failed to parse the argument net-address. Raw value: namada1.cryptosj.net:26676, error: AddrParseError(Socket)

**Comment by Fraccaman** [comment]
Hi @msobh13! We are aware and planning to add this feature in a later release. Thanks for the feedback!
