### ISSUE TITLE
MASP CI False Positives and Negatives

### ISSUE THREAD

**Issue by murisi** [anoma/namada#1376]
The CI reports that the 3 MASP E2E tests are passing when they should be failing. That the tests should be failing can be established from the fact that trying to manually construct shielded-to-shielded transactions with `namadac` (almost?) always fails due to issues with the MASP transaction signer, and also because the MASP E2E tests (almost?) always fail when executed locally.

Interestingly when the aforementioned issues with `namadac` are fixed, the local E2E tests start passing but the 3 MASP E2E tests in the CI begin to fail. For reference, these fixes are at https://github.com/anoma/namada/blob/5504002ff6d3c234c78afe64df2a1417653912e5/apps/src/lib/client/signing.rs#L157 and https://github.com/anoma/namada/blob/5504002ff6d3c234c78afe64df2a1417653912e5/apps/src/lib/client/tx.rs#L1909 .

A solution to this issue would prevent future regressions in the MASP code. cc @Fraccaman @gijswijs

**Comment by cwgoes** [comment]
Closing since this seems to be out-of-date, please reopen if I'm mistaken.
