### ISSUE TITLE
Namada server run/join blows away several tendermint config settings and breaks things

### ISSUE THREAD

**Issue by DaveWK** [anoma/namada#1393]
I have several customized settings in the tendermint config which the namada process breaks and overwrites on `join` or when running.

This commit introduced a bug where the version is prepended every time it restarts, in example if you restart 3 times, it becomes "moniker-v1.16.0-v1.16.0-v1.16.0": (https://github.com/anoma/namada/pull/1057

The moniker in the tendremint config also appears to be getting set to the hostname when doing a reset, which is not ideal. 
Additionally the process is resetting the fields for `laddr`,  `external_address` and `pex` under the `p2p` settings, which introduces problems with my network setup, it also keeps resetting my `instrumentation` settings which disables monitoring, and keeps resetting my `log_format` to `plain` instead of `json` which breaks my log shipping.

I would really prefer that it would stop silently breaking/adjusting my config files altogether and validate the config file in a read-only manner, then log if something isn't correct.  By default my preference would be that it should create the config files only when they do not exist in the path. If settings need to be changed between versions, then one can simply move the existing file to another location and diff with the new version rather than losing their edits because the process silently clobbered the file.

**Comment by cwgoes** [comment]
Should be fixed. Apologies for the annoyances.
