### ISSUE TITLE
PoS - slashing tests

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#14]
Add tests for slashes applied from the base ledger

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762961351019) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@brentstone what is the status of this? perhaps part of the slashing PR?

**Comment by brentstone** [comment]
> @brentstone what is the status of this? perhaps part of the slashing PR?

Yeah, this will be addressed in #892.

**Comment by brentstone** [comment]
Completed in #892
