### ISSUE TITLE
Increase the number of iterations at the PBKDF

### ISSUE THREAD

**Issue by leontiad** [anoma/namada#141]
The recommended number of iterations for` orion::kdf` is 100k in order to sufficiently circumvent offline dictionary attacks for low entropy passwords. The default value set to anoma wallet [key.rs](https://github.com/anoma/anoma/blob/5831077bf1f1ff917f97264471b0ddcae224e739/apps/src/lib/wallet/keys.rs#L238) here is set to `1<<16 = 65536`

**Comment by cwgoes** [comment]
Fixed by #320
