### ISSUE TITLE
Cleaning up dependency mess

### ISSUE THREAD

**Issue by adrianbrink** [anoma/namada#1427]

**Comment by tzemanovic** [comment]
some things that would help:
- For tendermint-rs, ibc-rs and tower-abci we should remove the workspace patches and use the appropriate forks in specific crates that depend on them. To avoid having to patch the versions in multiple crates, we can re-export
  - tendermint, tendermint-proto, ibc and ibc-proto from core
  - tendermint-rpc from shared
  - and the rest is only used in the apps crate
- remove abcipp from codebase

**Comment by adrianbrink** [comment]
Ideally we should get to a state where we don't have any patches anymore in the main repo and a developer can import `shared` without [this mess](https://github.com/anoma/namada-sdk-starter/blob/main/Cargo.toml).

**Comment by adrianbrink** [comment]
It would also be helpful to upgrade our dependencies in this process.
