### ISSUE TITLE
Docs changes to make

### ISSUE THREAD

**Issue by 0xapriori** [anoma/namada#1433]
# Create Sections for
* Delegators
* Power Users - Shielded Transfers, Shielded Set rewards, TX building (atomically)
* Public Goods Stewards
* Privacy - How to make as Private as possible. Note limitations of IBC, bridging assets, Ethereum (ETH, Bengt NFTSs)etc. Meta Deta leakage. Reccomend using TOR 

# Hardware requirements
* Reference tendermint docs - full/light nodes

# Wallets
* Wait until later this week - file system wallet, web wallet, paper waller

**Comment by cwgoes** [comment]
@bengtlofgren can you move this issue to the namada-docs repo, or close it?

**Comment by bengtlofgren** [comment]
It has been moved
