### ISSUE TITLE
e2e tests: expectrl process panics in background

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#145]
with the switch to expectrl anoma/anoma#1095, it looks like when a process (usually a ledger node) is put into background and it panics, the e2e test doesn't seem to catch that

**Comment by cwgoes** [comment]
@tzemanovic what is the status of this?

**Comment by tzemanovic** [comment]
> @tzemanovic what is the status of this?

I think this is most likely still open (it doesn't affect the results unless the ledger panic)

**Comment by cwgoes** [comment]
Closing for the sake of @Fraccaman's sanity.
