### ISSUE TITLE
Cannot compare IbcAmounts with Namada Amounts

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#1451]
The IbcAmount type in ibc-rs keeps it's int type private and has a very limited API. We cannot compare IbcAmounts with namada Amounts as a result (for example bounds checking).

**Comment by yito88** [comment]
I had the same concern and asked about it.
We can get the [U256](https://docs.rs/primitive-types/latest/primitive_types/struct.U256.html) from IbcAmount with the [derive](https://github.com/cosmos/ibc-rs/blob/31b030d54885f7d35ffd0f07766bf718e7688945/crates/ibc/src/applications/transfer/amount.rs#L9).

**Comment by yito88** [comment]
Fixed in #1784
