### ISSUE TITLE
`read_subspace_val_with_height` does not return a value if value was written at `< height`

### ISSUE THREAD

**Issue by gijswijs** [anoma/namada#1466]
`read_subspace_val_with_height` in `apps/src/lib/node/ledger/storage/rocksdb.rs` takes three arguments: `key`, `height`, `last_height`.
It returns the new key value if it finds a "new" val at `height`.
It return `None` if it finds "old" val.
If it doesn't find either, it will loop `height + 1` up to and including `last_height`:
If it finds the key with "old" val it returns that key value (that value was the value of the key at `height`)
If it finds the key with "new" val it returns `None` (the key was created *after* the specified height, so it wasn't present at `height`)

Now consider the following scenario:
A key is created at height 4: `0000000000004/new/gijsisanidiot = true`
The current block height is 11.
We call `read_subspace_val_with_height` with `height = 6` and `last_height = 11` and `key = gijsisanidiot`

`read_subspace_val_with_height` would return `None` since it doesn't look backwards in the block history to find the "new" val at blocks smaller than 6.

Based on the name of the Fn that doesn't seem expected behavior.

**Comment by yito88** [comment]
I think that it returns the latest value from the subspace when no `new` val exists.
Do you have a test that fails in your case? I would be happy to investigate it.
https://github.com/anoma/namada/blob/15e49a8196b6fef043c2dd1ef3a44598de2ec425/apps/src/lib/node/ledger/storage/rocksdb.rs#L990-L992

**Comment by gijswijs** [comment]
I actually don't have a proper test case, since it quite involved to create one for `dump-db` (and `rollback`). I will try to create one.

**Comment by grarco** [comment]
@yito88 this looks good. Do you think is it worth to optimize this in case one would like to read a value at a height closer to the first block than the last one? So basically looking for the opposite diff keys. It's a simple heuristics that it's not even guaranteed to be faster but in some cases it might help to reduce the number of iterations

**Comment by gijswijs** [comment]
@yito88 You are absolutely right. I'm closing this issue for now.
One thing that might be interesting to investigate with regards to #1468 is performance of dumping the db at a height that is far back in the past.

**Comment by yito88** [comment]
@grarco @gijswijs Previously this function read the value forward to the first height (the given height to smaller height). We changed this to the current implementation and added `storage_read_past_height_limit` because a read query might take a long time.
We could read `diffs` from the first height since we don't have any checkpoints of the subspace in the storage. It would take a long time too.
