### ISSUE TITLE
`namadaw key gen` and `namadaw address gen` do the exact same thing

### ISSUE THREAD

**Issue by bengtlofgren** [anoma/namada#1488]
<img width="492" alt="Screenshot 2023-05-31 at 13 53 24" src="https://github.com/anoma/namada/assets/51077282/a6e0676e-cb05-4cb8-a43a-8692149381f3">

Fix:
`namadaw key gen` should just generate the key ideally. `namadaw address gen` should create the address and a key.
Otherwise maybe delete the command `namadaw key gen`? Or perhaps you want the aliases to be different between them? Maybe you can generate address from a key?

I don't know, but it's weird atm

**Comment by tzemanovic** [comment]
personally I don't see the issue - the help for both is `Generates a keypair with a given alias and derive the implicit address from its public key. The address will be stored with the same alias.`, but if it's confusing imho prefer to remove `namadaw address gen` as an address is derived from a key.

**Comment by cwgoes** [comment]
Agreed, we should only use `gen` for things which are actually "generated", i.e. using local randomness.

**Comment by cwgoes** [comment]
Any concerns @karbyshev? If not, can you take a look quickly, as this should be code you're familiar with?

**Comment by karbyshev** [comment]
They have been synonymous from the beginning, indeed.
@bengtlofgren What would be a possible use case for generating a key without storing the respective address?
I didn't check that, but storing the former without the latter currently might break some internal wallet assumptions.

**Comment by karbyshev** [comment]
If to remove any, I would ditch `address gen` and, recently introduced, `address restore`.

**Comment by karbyshev** [comment]
Closing the issue for now.
