### ISSUE TITLE
Skipping creation of key with the same alias throws error

### ISSUE THREAD

**Issue by bengtlofgren** [anoma/namada#1501]
Assume you have a key in the wallet with alias `aliace`.
Now, if you execute:

`namadaw key gen --alias aliace` 

you will run into the following dialogue: 

```
You're trying to create an alias "aliace" that already exists for a key in your store.
Would you like to replace it? s(k)ip/re(p)lace/re(s)elect: k
```

However, instead of completing this silently (as expected), we receive

```
The application panicked (crashed).
Message:  Action cancelled, no changes persisted.
Location: /Users/unknowit/Heliax/namada/shared/src/ledger/wallet/store.rs:269
```

**Comment by cwgoes** [comment]
@karbyshev can you quickly take a look at this?

**Comment by karbyshev** [comment]
Well, technically speaking, nothing bad is happening: the action gets cancelled by panicking :-) It is confusing from the user's perspective, though.
