### ISSUE TITLE
PoS/test: division by zero

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#1556]
Trace: https://github.com/anoma/namada/actions/runs/5253847650/jobs/9491877974?pr=1549

The state machine test failure is most-like a problem with pre-conditions because `get_total_consensus_stake` ends up being zero.

**Comment by brentstone** [comment]
I have a local change that somewhat fixes this issue actually. I started doing SM tests with somewhere around 8 consensus validator slots and more genesis validators. Compared to the current config of like 3 or 4 consensus validators, we run into this issue MUCH less frequently.

**Comment by brentstone** [comment]
@tzemanovic Are we still concerned with this enough to keep the issue open? Haven't encountered this in a while but don't recall if we've explicitly solved it.

**Comment by tzemanovic** [comment]
we have a fix for this in #1612 where we account for enqueued slashes in the pre-condition (https://github.com/anoma/namada/blob/d0f994f721dfc723a8f00cc5a0c0be9997ea479a/proof_of_stake/src/tests/state_machine.rs#L2657-L2668)
