### ISSUE TITLE
dependencies clean-up

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#1562]
todo:
- [x] get rid of workspace patches and re-export 3rd party crates that appear in public API of a crate
  - borsh is blocked by #1563
- [x] make sure that every sub-crate can be built with default features
- [x] switch to use workspace inheritance added in rust 1.64
- [ ] reduce the amount of duplicate deps (detect with `cargo tree --duplicates` and potentially add an automated test in CI for this)

**Comment by Fraccaman** [comment]
we might want also to look at: 
- https://github.com/anoma/namada/issues/1024
- https://github.com/anoma/namada/issues/1023

**Comment by cwgoes** [comment]
Closing this for now per @brentstone but we should periodically check before cutting a release.
