### ISSUE TITLE
Possible malleability attack on tx encrypted sections

### ISSUE THREAD

**Issue by grarco** [anoma/namada#1567]
About the commitment of the header to the sections. There are only the hashes of the code and data section in the header and other commitments are placed in the `Data` section if needed. This looks good but there might be room for an attack on the encrypted sections.

Fees are paid when the entire tx is included in the block: in the following block we decrypt the sections and do validation. If this validation fails we can avoid executing the transaction but the problem is that the wrapper’s signer has already paid the fees, suffering an economic damage.

**Comment by grarco** [comment]
Yes, I think this issue applies to all of the sections that are included in transaction. If I recall correctly what you explained me, we "encrypt" all of the sections except for the signature on the `Header`. Except for this signature, I think all of the other sections need a commitment in the header to prevent tampering. Note that this doesn't have anything to do with the encryption per se, we'd need the commitment even if all of the sections were in plaintext

**Comment by cwgoes** [comment]
MERGED :rocket:
