### ISSUE TITLE
common storage read trait

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#166]
Depends on #110 

Add a common trait for client RPC storage read queries, ledger direct storage access (probably needs to include gas metering somehow), VPs posterior storage read (we shouldn't need to re-use code for reading from pre-state, that's typically only ever done by the VP that owns the given storage key) and tx storage read.

**Comment by cwgoes** [comment]
@tzemanovic what's the status of this?

**Comment by tzemanovic** [comment]
done in #324 (incorrectly showing closed, but it was merged)
