### ISSUE TITLE
v0.18.0+ won't parse TOML created earlier

### ISSUE THREAD

**Issue by joesixpack** [anoma/namada#1699]
`Jul 10 10:43:47 tucana namada[1359180]: The application panicked (crashed).
Jul 10 10:43:47 tucana namada[1359180]: Message:  called `Result::unwrap()` on an `Err` value:
Jul 10 10:43:47 tucana namada[1359180]:    0: couldn't parse TOML from /home/j/.local/share/namada/public-testnet-10.3718993c3648.toml
Jul 10 10:43:47 tucana namada[1359180]:    1: invalid type: integer `9223372036854`, expected a string for key `token.Schnitzel.balances.atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3` at line 2518 column 88
Jul 10 10:43:47 tucana namada[1359180]: Location:
Jul 10 10:43:47 tucana namada[1359180]:    apps/src/lib/config/genesis.rs:706
Jul 10 10:43:47 tucana namada[1359180]: Backtrace omitted.
`

**Comment by tzemanovic** [comment]
hi, we're currently not aiming for full backwards compatibility, but this issue is the same as #1655
