### ISSUE TITLE
PoS - use checked arithmetics

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#17]
Use checked arithmetics in the PoS library code (has a TODO left in code)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762910654658) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@brentstone do you know what the status of this is? we should definitely do it :smile:

**Comment by tzemanovic** [comment]
> @brentstone do you know what the status of this is? we should definitely do it 😄

still open I think

**Comment by sug0** [comment]
since everything is using the updated amounts now, since `v0.19.0`, which `.unwrap()`s overflows/underflows, I think we can close this, right?

**Comment by brentstone** [comment]
> given everything is using the updated amounts now, since `v0.18.0`, which `.unwrap()`s overflows/underflows, I think we can close this, right?

I think it's prob still good to keep open as a reminder to go through and ensure this is universally true at some point. I'd bet there are still some PoS things which could use this.

**Comment by cwgoes** [comment]
Would it be possible to configure our Rust linter to warn/error when unchecked arithmetic is used?

**Comment by tzemanovic** [comment]
> Would it be possible to configure our Rust linter to warn/error when unchecked arithmetic is used?

I don’t see anything out of box, but it should be possible to add this to clippy

**Comment by tzemanovic** [comment]
ah, there is a way - we can configure clippy "disallowed-methods" https://doc.rust-lang.org/nightly/clippy/lint_configuration.html#disallowed-methods

**Comment by brentstone** [comment]
It seems like the original instances that this issue referenced have already been fixed, but nevertheless I've added some more checked arithmetics in the PoS code in #2178.
