### ISSUE TITLE
Specs: Ethereum bridge recovery multisig

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#170]
As discussed with @adrianbrink 

- Require all Namada validators to create an Ethereum address and sign it
- Create a threshold 2/3 multisignature contract on Ethereum with voting weights and addresses of the validators
- Keep that contract up to date when there are validator set updates
- After a delay period with no regular updates, the contract can recover the funds in the Namada bridge contract

**Comment by cwgoes** [comment]
@Fraccaman @batconjurer have we implemented a recovery multisig yet, or not yet?

**Comment by batconjurer** [comment]
@cwgoes Not yet, no

**Comment by sug0** [comment]
I presume this is related to https://github.com/anoma/ethereum-bridge/issues/62 ??

**Comment by cwgoes** [comment]
Yes, unless you had another, different plan for enabling emergency withdrawals.

**Comment by sug0** [comment]
@cwgoes was just checking. all namada side things are complete, then. only the smart contracts need to be updated, so I'm closing the issue on this side
