### ISSUE TITLE
Allow the Bridge pool fees to be payed in more token types

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1704]
Allow the Ethereum Bridge pool fees to be payed in more token types. This feature depends on #1693.

Associated tasks:

- [x] Change the Bridge pool VP logic to accept more gas token types, and check their escrowed amounts
- [x] Determine how to remove from the appropriate Bridge pool escrow token address (we're currently hardcoded to NAM)
- [x] Change CLI arguments
- [x] Fix `build_bridge_pool_tx` (must use fee token addr obtained from `args`)
- [x] Test paying gas fees in NUTs is not possible
- [x] Test paying gas fees with wrapped NAM (NUTs or ERC20s) is not possible
- [x] Add tests checking fee token types other than NAM in the Bridge pool

---

Relevant CLI arguments:

```
      --fee-amount <fee-amount>
          The amount of NAM you wish to pay to have this transfer relayed to Ethereum.
      --fee-payer <fee-payer>
          The Namada address of the account paying the fee.
      --gas-amount <gas-amount>
          The amount being paid for the inclusion of this transaction
      --gas-token <gas-token>
          The token for paying the gas
```

**Comment by sug0** [comment]
cc @batconjurer

**Comment by batconjurer** [comment]
Yes, we should
