### ISSUE TITLE
Wasm pre-compile cache

### ISSUE THREAD

**Issue by Fraccaman** [anoma/namada#1707]
For some reason, the pre-compiled wasm that we build at startup and save in the `tx_cache` and `vp_cache` folder are not always portable between machines/versions. An easy fix would be to just recompute them at every startup.

**Comment by tzemanovic** [comment]
the compiled wasm cache is expected to be platform specific. It doesn't seem like a common issue, but maybe we can move the caches out of the chain dir instead to make it portable?
