### ISSUE TITLE
RPC queries at a given height

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#172]
implement `query.height` support client queries where it's supported:
- [ ] epoch
- [x] storage values
- [ ] also in newly added block #659

We can add `height` to the shared `args::Query`.

**Comment by tzemanovic** [comment]
OpenAPI spec will need to be updated for this (adding in #1228)

**Comment by cwgoes** [comment]
@tzemanovic do you know the status of this?

**Comment by tzemanovic** [comment]
> @tzemanovic do you know the status of this?

`storage values` RPC now supports height, but rest is still tbd

**Comment by tzemanovic** [comment]
closing, re-open if needed
