### ISSUE TITLE
wasmer: mac m1/m2 misaligned pointer dereference

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#1721]
We're having a problem with this error https://github.com/wasmerio/wasmer/issues/4072 on wasmer 2.3.0 but newer versions are also affected as reported. In our code it can be reproduced in e.g. `cargo test vm::wasm::run::tests::test_tx_stack_limiter`

**Comment by adrianbrink** [comment]
Is this still the case even with the latest release of wasmer?

**Comment by tzemanovic** [comment]
it should have been fixed in #1778
