### ISSUE TITLE
Return status codes from native VPs

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1723]
Currently, if a native VP doesn't return `Err`, we have no way of asserting the reason why it might have rejected a tx. We could refactor the interface of native VPs to return a `Status: Into<bool>`, to offer more context for testing and even debugging purposes.

**Comment by sug0** [comment]
cc @tzemanovic

**Comment by tzemanovic** [comment]
perhaps we could use `Result<()>` to require an err type for rejection

**Comment by sug0** [comment]
yeah, that seems fine. however, it's a bit more work refactoring wise, because you cannot do it in stages (e.g. by default you could set `Status = bool`, and replace `Status` as needed)

**Comment by sug0** [comment]
Native VPs' `validate_tx` can wrap another `validate_tx_with_status` method, returning some `Into<bool>` value. It is not necessary to change the native VP trait.

**Comment by sug0** [comment]
Closed by #2958
