### ISSUE TITLE
Separate accounting for shielded rewards

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#1730]
We should keep a counter of all shielded rewards paid (separately from the MASP balance)

cc @bengtlofgren @mariari @juped

**Comment by cwgoes** [comment]
We should also test that we can never withdraw more rewards than were originally paid.

**Comment by murisi** [comment]
@cwgoes I just want to clarify: is the goal to augment the `namadac -- balance` command to indicate to the user how much of their balance is due to receiving MASP rewards? If so, this would take at most a day. Or do you have something else in mind?

**Comment by cwgoes** [comment]
No - the goal is to track in state (accessible with a distinct query command) the total NAM that have ever been allocated (minted through inflation) to shielded rewards and could potentially be withdrawn by using the convert circuit. It's possible that we even do this already - I'm not sure.
