### ISSUE TITLE
client denies any gov proposal tx without epoch denomination of 3

### ISSUE THREAD

**Issue by gavinly** [anoma/namada#1734]
the Namada client denies any gov proposal tx without epoch denominations of 3, even if the min_proposal_period parameter is set to 1

when min_proposal_period is set to 1, the client reports that the epoch must be a multiple of 1, but in practice it only generates and submits the tx if epoch is a multiple of 3

**input**
namada init-proposal --data-path proposal.json

**output**
2023-07-18T12:53:14.277122Z  INFO namada_apps::cli::context: Chain ID: knowable.ac38ac99c7e5eb0d7c68c
Last committed epoch: 204
Invalid proposal end epoch: difference between proposal start and end epoch must be at least 1 and at max 27 and end epoch must be a multiple of 1

**unsuccessful proposal.json parameters**
 "voting_start_epoch": 207,
    "voting_end_epoch": 208,
    "grace_epoch": 211,

**successful parameters**
    "voting_start_epoch": 207,
    "voting_end_epoch": 210,
    "grace_epoch": 213,

**Comment by gavinly** [comment]
more specifically, the delta can be 1 epoch, but only if voting_end_epoch is a denomination of 3 (or the client will refuse). examples:

**works**
    "voting_start_epoch": 212,
    "voting_end_epoch": 213,
    "grace_epoch": 216,

**won't work**
"voting_start_epoch": 213,
    "voting_end_epoch": 214,
    "grace_epoch": 219,

**Comment by gavinly** [comment]
confirmed that forcing the tx results in a valid gov proposal going live on-chain

root@Namada-Gavin:~# namada init-proposal --data-path proposal.json --force
2023-07-18T13:22:55.080979Z  INFO namada_apps::cli::context: Chain ID: knowable.ac38ac99c7e5eb0d7c68c
Last committed epoch: 210
Invalid proposal end epoch: difference between proposal start and end epoch must be at least 1 and at max 27 and end epoch must be a multiple of 1
Looking-up public key of atest1v4ehgw36g56yxve38y6rx3zyxpzngw2rxycrwdf3gse5gw2rx5erqd3hgfrrsde5ggmryv6psnlapg from the ledger...
The transaction requires the completion of a PoW challenge.
Looking for a solution with difficulty 1...
Checking 514.
Found a solution: 514.
Transaction added to mempool: Response { code: Ok, data: Data([]), log: Log("Mempool validation passed"), hash: transaction::Hash(D9B92F5521C253383898EC6598A4AE3B42FA4F7A5879BC20E9A8275B1A16DA43) }
Wrapper transaction hash: "557FD84069A36E9EBDAE653866A3442B52DA8160EC25D1159337F2A519877AFD"
Inner transaction hash: "9023A4A9DE12F8EB930C97E4B2AC037BCF65407C950B234C8C6B401D0613E2F8"
Transaction accepted with result: {
  "info": "Transaction is valid. Gas used: 2; VPs result: ",
  "log": "",
  "height": "37029",
  "hash": "557FD84069A36E9EBDAE653866A3442B52DA8160EC25D1159337F2A519877AFD",
  "code": "0",
  "gas_used": "2",
  "initialized_accounts": []
}
Transaction applied with result: {
  "info": "Transaction is valid. Gas used: 12085439; Changed keys: #atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1v4ehgw36g56yxve38y6rx3zyxpzngw2rxycrwdf3gse5gw2rx5erqd3hgfrrsde5ggmryv6psnlapg, #atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/counter, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/6/author, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/6/content, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/6/end_epoch, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/6/funds, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/6/grace_epoch, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/6/start_epoch, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/6/type, #atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/epoch/219/6; VPs result:  Accepted: atest1v4ehgw36g56yxve38y6rx3zyxpzngw2rxycrwdf3gse5gw2rx5erqd3hgfrrsde5ggmryv6psnlapg, atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5, atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt;",
  "log": "",
  "height": "37030",
  "hash": "9023A4A9DE12F8EB930C97E4B2AC037BCF65407C950B234C8C6B401D0613E2F8",
  "code": "0",
  "gas_used": "12085439",
  "initialized_accounts": []
}

**Comment by Fraccaman** [comment]
this was fixed in 0.20.0! ill close the issue
