### ISSUE TITLE
Update Docker Hub for Anoma/Namada

### ISSUE THREAD

**Issue by gnosed** [anoma/namada#174]
Since we are removing Nix from Namada (see issue #173), we want to give the user the ability to start Namada from a Docker image.

Before the transfer to Namada, Anoma Docker images used to live [here](https://hub.docker.com/r/heliaxdev/anoma). To guarantee consistency, we need to:

- [ ] Create an Anoma organisation on Docker Hub (similar to GitHub structure), so it's not attached to Heliax organisation anymore.
- [ ] Re-establish the CI to deploy the images to Docker Hub when a new release is issued.
- [ ] If needed, update the docs under "Install Namada/From Docker" section.

**Comment by gnosed** [comment]
It works for me!

**Comment by alexmeise** [comment]
hi! are those images already available somewhere? I am getting some errors when trying to build the dockerfile in the repo: 

```
---> Running in 70a71b627849
error: could not find `Cargo.toml` in `/app` or any parent directory
thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.35/src/recipe.rs:145:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The command '/bin/sh -c cargo chef cook --release --recipe-path recipe.json' returned a non-zero code: 101
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 101
```

**Comment by tzemanovic** [comment]
docker images are published at https://github.com/anoma/namada/pkgs/container/namada

**Comment by tzemanovic** [comment]
@alexmeise pls re-open if this is still an issue
