### ISSUE TITLE
Wrapper tx replay protection 

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#178]
As noted in https://github.com/anoma/anoma/blob/625bab46c32da6aeb35418869974bfb1ac98cd3e/docs/src/specs/ledger.md: "DKG transactions will include replay protection (this is because we can simply check a counter against the source (i.e. gas payer) of the transaction before the transactions order is committed to by the DKG protocol, which could affect the expected counter order for sources with multiple queued transactions)".

We should add reply protection to the wrapper tx. This can simply be a counter in implicit accounts that is checked and incremented by the wrapper transactions.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763318619271) by [Unito](https://www.unito.io)

**Comment by grarco** [comment]
Closed in favor of #1009
