### ISSUE TITLE
Need total staked tokens for older governance proposals

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#1783]
Governance proposals may tally voting results at a grace epoch that can be many epochs after the voting end epochs. We currently keep total staked tokens data in the `total_deltas` just for 23 epochs, but this should probably be larger, perhaps some arbitrarily larger number like 100, or some number tied to governance like one related to `max_proposal_period`.

**Comment by tzemanovic** [comment]
#1944 changes the PoS epoched data to be available for tallying. @Fraccaman we then need to store the tallying result on-chain, right?
