### ISSUE TITLE
Improve formatting of help messages in the CLI

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1796]
Some CLI commands have huge help messages, with no line wrapping. For instance:
<img width="1470" alt="image" src="https://github.com/anoma/namada/assets/13282069/64de9b2b-8818-4c7a-b68e-1c8b843f4678">

It would be helpful to:

- [ ] Wrap the output of help lines to 80 characters or less.
- [ ] For longer help messages, use something like...
    - [`Arg::long_help`](https://docs.rs/clap/4.3.4/clap/struct.Arg.html#method.long_help)
    - [`Arg::next_line_help`](https://docs.rs/clap/4.3.4/clap/struct.Arg.html#method.next_line_help)

**Comment by nodersteam** [comment]
@sug0 Can we take this to work?

**Comment by sug0** [comment]
if you want to take this on, feel free @nodersteam

**Comment by Kofituo** [comment]
Hello, is this take still available? @sug0 @nodersteam

**Comment by cpp-phoenix** [comment]
I can pick it up @sug0

**Comment by sug0** [comment]
@cpp-phoenix looks like https://github.com/nodersteam/namada/pull/3 had already partially completed this work. you can pick it up from there.

there might exist a cleaner way to implement this though. I think `clap` already provides facilities to wrap the output to a certain number of lines.
