### ISSUE TITLE
SMT proofs with ics23 v0.10.0 or later

### ISSUE THREAD

**Issue by yito88** [anoma/namada#1804]
We're using arse-merkle-tree (our modified Sparse Merkle Tree) because the old `ics23` crate didn't support SMT proofs.
`ics23` [v0.10.x](https://github.com/cosmos/ics23/blob/master/CHANGELOG.md#0100) supports them.
We can use SMT for IBC-related data.

- Require ibc-rs v0.42.0 or later #2084 

- Gaia, Osmosis, and Noble should support SMT proofs, provided by `ibc-go` v7 or later
  - Gaia v0.15.1 or later supported
  - Osmosis v23 or later supported
  - [Blocked] Noble doesn't support because it is still using `ibc-go` v4

**Comment by yito88** [comment]
Counterparty chains should be able to verify SMT proofs. They have to use:
- `ics23` v0.9.1 or later
- `ibc-go` v7 or later

But the latest Gaia v13 (also the next v14) is still using `ibc-go` v4 (`ics23` v0.9.0) which has been already EOL...

**Comment by cwgoes** [comment]
@yito88 do you know if there have been any updates here Gaia-side?

**Comment by yito88** [comment]
In Gaia's main branch, `ibc-go` has been updated to `v7` supporting SMT proofs.
However, it's not included in the latest release `v14.1.0`.

**Comment by yito88** [comment]
Gaia `v15.1.0` has been released, which version has `ibc-go` v7.
Started replacing `arse-merkle-tree`.

**Comment by yito88** [comment]
Osmosis v23 has `ibc-go` v7 already.
Noble is still using `ibc-go` v4 according to https://github.com/circlefin/noble-fiattokenfactory

**Comment by cwgoes** [comment]
@yito88 Is this issue still relevant?

**Comment by yito88** [comment]
The latest Noble uses `ibc-go` v8. To reduce the Merkle tree size, we could go back to SMT for IBC-related data. I'll test it.

**Comment by yito88** [comment]
hmm, the current `ics23` can't support our SMT. Our hack to replace the key and value in the proof doesn't work by the [changes](https://github.com/cosmos/ics23/commit/bce5420709ab1fca1b88de0aba95986b0168b28a) which forces to apply the given spec instead of the leaf spec.

**Comment by yito88** [comment]
We need to keep using arse-merkle-tree. We could open it again if ics23 would support other SMTs
