### ISSUE TITLE
Handle validators rebonding their stake under a different address in order to vote multiple times for an Ethereum event

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#181]
(relevant version of spec: https://github.com/anoma/namada/blob/c6bc20d35497d0244c201c698e79471aca2027c0/documentation/spec/src/interoperability/ethereum-bridge.md)

We act on Ethereum events only once they have been voted as seen by 2/3 total voting power. This 2/3 total voting power can come from across multiple epochs, but validators may not vote more than once. If a validator votes for an event in some epoch, they cannot vote again on the same event, even in a later epoch where their voting power has changed.

We need to prevent the situation where some actor is able to workaround this by acting as an active validator under different addresses in different epochs, voting on the same event.

Example
- actor bonds stake to become a validator under address A
- in epoch i, as validator A, they vote for event x with 1/3 total voting power
- actor unbonds stake
- actor rebonds stake to become a validator under address B
- in epoch j > i, as validator B, they vote for event x again with 1/3 total voting power
- event x gets acted upon

In the case where event x is a valid Ethereum event, this is fine and event x would very likely be included into Namada quickly anyway. Where event x is invalid, this could mean the invalid event x gets acted upon. 

If we can detect and prevent invalid Ethereum events being included into Namada in such a way that they could never be acted on in the first place (https://github.com/anoma/namada/issues/180), that could obviate this issue altogether.

Possible solution: events that are first included in epoch `i` must go into the `seen = true` state by epoch `i+n` inclusive, where `n` is strictly less than the number of epochs it would take a validator to unbond and rebond their stake under a different address. Being strict, we could take `n=0` (events must be acted on in the same epoch they are first seen). We will need some way to recover for valid events that timeout like this.

This issue covers
- [ ] updating the spec
- [ ] making updates to the code in `eth-bridge-integration`, or otherwise replacing this issue with smaller broken down issues to do so

**Comment by james-chf** [comment]
NB: in short, a solution to this issue is to have Ethereum events included onto Namada expire within a certain number of epochs, if they are not confirmed within that time

**Comment by cwgoes** [comment]
@james-chf @batconjurer do you know the status of this?

**Comment by james-chf** [comment]
I think we were going to go with expiring unconfirmed Ethereum events before a validator could rebond their stake, this needs to be specced out. I would say - when an (unconfirmed) Ethereum event is first seen and recorded in storage, we should set an expiration epoch that is before when a validator could rebond (e.g. if it takes six epochs for a validator to rebond, we should have the expiration epoch for events be five epochs into the future). If the event doesn't receive enough votes by the time that epoch starts, it expires and can never be confirmed - this expiration would need to be provable to the Ethereum bridge smart contracts also so that any expired transfers can be refunded to the sender on Ethereum.

In practice with >2/3 honest voting power, we'd expect Ethereum events to be confirmed relatively quickly once they are deep enough in the Ethereum chain (i.e. same epoch they were first seen, or potentially the epoch after if an event was first seen just before an epoch transition). Separate but related to this issue, we will probably want to monitor for Ethereum events that don't become confirmed quickly as they would likely be either fake/invalid.
