### ISSUE TITLE
Converting from CLI to SDK types should be fallible

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1815]
Some conversions from CLI to SDK types require file I/O. Of course, reading from and writing to files can fail. However, currently `CliToSdk` does not have a way to forward errors to a higher stack frame. This encourages panicking in the CLI, which is bad UX.

The suggested approach is to turn `CliToSdk` into something like:

```rs
/// Convert CLI args to SDK args, with contextual data.
pub trait CliToSdk<SDK>: Args {
    /// Error type for fallible operations.
    type Error;

    /// Convert CLI args to SDK args, with contextual data.
    fn to_sdk(self, ctx: &mut Context) -> Result<SDK, Self::Error>;

    /// Convert CLI args to SDK args, with contextual data.
    fn infallible_to_sdk(self, ctx: &mut Context) -> SDK
    where
        // NB: matching on the type with `==` is not stable AFAIK,
        // so we use `Into<T>`, which is implemented for any `T`
        Self::Error: Into<std::convert::Infallible>,
    {
        match self.to_sdk(ctx).map_err(Into::into) {
            Ok(x) => x,
            Err(e) => match e {},
        }
    }
}
```

Whenever errors are not expected, it is possible to return a `Result<T, std::convert::Infallible>`, which has 0 cost from a runtime perspective.

**Comment by phasewalk1** [comment]
hey @sug0, is this still needed? i'd be happy to take it up.
