### ISSUE TITLE
Create a utils command that takes in a wallet.toml and generates the tendermint priv_validator_key.json and node_key.json

### ISSUE THREAD

**Issue by nick-u410** [anoma/namada#1826]
**Tested on**: public-testnet-11/12*

**Problem:**
Currently the only way to generate the `priv_validator_key.json` deterministically is to `namada client utils join-network --chain-id $CHAIN_ID --genesis-validator $ALIAS`, this will generate the keys(`node_key.json`, `priv_validator_key.json`) from the `wallet.toml`. However, people who use a remote signer need this key up front on their remote signer machine. Validators would prefer a way to get these keys before joining the network.

**Potential Solution:**
Create a utils command that takes in a `wallet.toml` and generates the tendermint `priv_validator_key.json` and `node_key.json`

**Comment by sug0** [comment]
https://github.com/anoma/namada/issues/1155
