### ISSUE TITLE
Gas `SCALE` as protocol parameter

### ISSUE THREAD

**Issue by grarco** [anoma/namada#1881]
Currently, the `SCALE` of the gas is a constant. This value has an impact in the way that the gas (and therefore its price) is computed. Since the minimum gas price is already a protocol parameter, it would be slightly better to make the gas scale one as well to give the community complete control on the two factors that determine the gas fee of a transaction.

**Comment by cwgoes** [comment]
We've decided not to do this.

**Comment by grarco** [comment]
Reopening this as per discussion with @Fraccaman, @sug0 and @gavinly
