### ISSUE TITLE
IBC transaction gas costs

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1923]
Especially after #1904 is merged, IBC transactions will not pay many (if any) gas fees. Updating Namada's state machine with an IBC transaction is somewhat expensive, as validation and storage modifications do the exact same amount of work (i.e. validation is not cheaper, the same code is executed for wasm as is for the native VP).

We should assign a constant gas price to invoking the IBC tx actions host function, and some other cost to executing the IBC native VP. These values should be determined based on the computational effort of running the associated IBC code, with benchmarks.

**Comment by sug0** [comment]
cc @grarco @yito88 @tzemanovic

**Comment by grarco** [comment]
Just as a note, I think this pattern should be shared across all native vps given the impossibility of tracking their execution at runtime. If a native vp is computationally expensive (access to storage are already correctly tracked though host functions, so no need to care about them) we should extract the complex part out to a host function to which we can assign a gas cost
