### ISSUE TITLE
Native VPs should account for cpu cycles spent during validation

### ISSUE THREAD

**Issue by sug0** [anoma/namada#1924]
>Just as a note, I think this pattern should be shared across all native vps given the impossibility of tracking their execution at runtime. If a native vp is computationally expensive (access to storage are already correctly tracked though host functions, so no need to care about them) we should extract the complex part out to a host function to which we can assign a gas cost

_Originally posted by @grarco in https://github.com/anoma/namada/issues/1923#issuecomment-1731092440_

**Comment by grarco** [comment]
Actually, if the expensive part of a native vp doesn't need to be shared with a transaction or a non-native vp, there's no need to export it to a host function: we can just benchmark its execution and charge the gas before calling it
