### ISSUE TITLE
Unknown key message while inputting wrong key password in signing-keys flag

### ISSUE THREAD

**Issue by McDaan** [anoma/namada#1935]
By inputting a wrong password of an existing key in `--signing-keys` flag, it returns the following message:
```
[...]
Message:  called `Result::unwrap()` on an `Err` value: "Unknown key test"
Location: apps/src/lib/cli/context.rs:175
[...]
```
The key with alias `test` exists:
```
namadaw key find --alias test
Enter your decryption password:
Public key hash: 4FEB63BF0C8AC453B05DCEAD727FE69BB8BD5A55
Public key: 0006d7101fbc0b9cd868197ec75c24ea55ff93104c1b0494ef705bb6da73eb7316
```
So, it should return this error instead, right?
```
Error:
   0: Unable to decrypt the keypair. Is the password correct?
```
**How to reproduce it?**
It happens on every command that involves `--signing-keys` flag.

**Comment by Kofituo** [comment]
Hello, I'd like to contribute to thud project. 
Have this issue been fixed?

**Comment by Kofituo** [comment]
How can I reproduce the error? @McDaan @tzemanovic

**Comment by cwgoes** [comment]
This should have been fixed, but please re-open if not.
