### ISSUE TITLE
Explicit implementation for EthereumEvent Ord

### ISSUE THREAD

**Issue by sug0** [anoma/namada#194]
Between crate version upgrades (e.g. `ethabi`), the current ordering of `EthereumEvent` instances may be inconsistent between different versions of namada. We should remove the derived implementation of `Ord`, and create an explicit impl.

The ordering of `EthereumEvents` is required for decompressing `VoteExtensionDigest` instances into `Vec<Signed<VoteExtension>>`.

It would be nice to test if the ordering stays consistent between different namada versions.

**Comment by james-chf** [comment]
In general, we want something like the following to hold: if event A is emitted by Ethereum smart contracts before event B, then event A should be acted on before event B. 

It would be good if `EthereumEvent` could naturally order by when they were emitted. We could do this if every variant of `EthereumEvent` included a monotonic `id` field that was set by the Ethereum smart contracts when they emit the event. Currently we have a `nonce` field in some but not all event variants eg `TransfersToNamada` has a `nonce` but `UpgradedContract` does not - this `nonce` could now be replaced with `id`.

**Comment by cwgoes** [comment]
@sug0 what is the status of this?

**Comment by sug0** [comment]
@cwgoes technically not an issue anymore, until we move back to using vote extensions (some time when the full ABCI++ spec is implement by the Tendermint folk). this is only relevant for vote extension digests

**Comment by sug0** [comment]
took another look at the inner data fields of `EthereumEvent` instances. the representation of this data should stay consistent between crate upgrades, because it's using types with Ethereum data representations, which are effectively set in stone. all other values are Namada-specific, so as long as we don't muck around with these reprs (e.g. `Address`), we're in the clear. in any case, if this ever becomes an issue (IMO unlikely), it should be left to governance to solve it
