### ISSUE TITLE
functions like generating keypairs won't work without a genesis file

### ISSUE THREAD

**Issue by gavinly** [anoma/namada#1952]
we want to be able to perform different functions with the binaries as stand-alones, but can't perform functions like keygen without a genesis file (and possibly other dependencies)

**Comment by gavinly** [comment]
@Fraccaman

**Comment by Fraccaman** [comment]
this is addressed by #1782

**Comment by sug0** [comment]
Related to / duplicate of #711

**Comment by cwgoes** [comment]
Should be fixed.
