### ISSUE TITLE
Epoched validator protocol key

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#1961]
We should move the validator protocol key into PoS system to make it epoched, so that it can be changed without immediately invalidating txs signed with the original key.

_Originally posted by @sug0 in https://github.com/anoma/namada/pull/1943#discussion_r1342781060_

**Comment by brentstone** [comment]
Should we address this in #1944 or open a separate PR for it?

**Comment by sug0** [comment]
@brentstone I think it's fine to include it in the same PR
