### ISSUE TITLE
IBC native VP suddenly fails to apply/handle IBC client update

### ISSUE THREAD

**Issue by McDaan** [anoma/namada#1974]
I have been searching for a similar issue but I couldn't find it, so I proceed to open this one, just in case.

Yesterday I have opened a IBC channel between Namada and Cosmos testnets. After manually applying regular updates to both IBC clients, I have noticed that Hermes was supposed to automatically update these on both sides (it did and keeps doing so on Cosmos side), so I just left Hermes to do its job. Today, suddenly, and judging by logs below, the IBC client on Namada's side (`07-tendermint-3`) wasn't able to update anymore.

Seeing the latest consensus state timestamp (from 18245237 block height on Cosmos testnet) of the mentioned IBC client, it seems to me that IBC client updates are not working properly/or started not to work properly after a while (I'm unsure if this has to do with IBC native VP or Hermes):
```
client state is not valid: latest height is outside of trusting period! latest_height=0-18245237 network_timestmap=2023-10-07T19:52:53.913204847Z consensus_state_timestamp=2023-10-06T07:35:05.459075349Z elapsed=130668.454129498s
```
I have also tried to update it manually several times. Although it showed up that it's been updated, it wasn't the case.

This IBC related log, and others, started to appear today (on `October 7, 2023 at 12:06:31 UTC`):
```
2023-10-07T12:06:31.904279Z  INFO namada_apps::node::ledger::shell::finalize_block: Transaction 2C863063CD4EED8A5B48FB0D39DB1C9B964099A04D14B995DABD979242CECCDB failed with: Error trying to apply a transaction: IBC native VP: IBC action error: IBC validation error: context error: `ICS02 Client error: client specific error: `The given hash of the validators does not matches the given hash in the signed header. Expected: `7EC571E8DBA54AF2E94555F411EF9867A3B37A7E62BE1F751898ACA0E49FCF67`, got: `5F3142F3FFE1B96CB59616406D87FDBE6B0EA7A32ABBB735B47F005E842CA370```
```

Attached IBC related ledger logs (info+debug): [ibcledgerlogs.txt](https://github.com/anoma/namada/files/12838725/ibcledgerlogs.txt)

I also updated it to a Github Gist, just in case: https://gist.github.com/McDaan/ccf7af19b6a612d71c60fa608dfc3dc5

**Comment by McDaan** [comment]
That's great! By the way, I have noticed that Hermes recommends to set trusting period under 1200s (which is the pipeline length (2) on this testnet, not the unbonding one (3) - 1800s)
```
namadac query-protocol-parameters | grep "Unbonding length"
    Unbonding length: 3
```

**Comment by yito88** [comment]
Namada's `unbonding_len` is not exactly the same as the "unbonding period" in a Tendermint light client.
Our PoS the consensus state can only change at the pipeline offset. We can withdraw the stake after the `pipeline_len` + `unbonding_len`.
That's why we use `pipeline_len` for the unbending time of the IBC client.

**Comment by Fraccaman** [comment]
This seems related to hermes and not namada. Closing.
