### ISSUE TITLE
CheckTx could reject transactions that will always be excluded during PrepareProposal

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#199]
This issue applies to ABCI++ where we have the opportunity to exclude transactions from a block during `PrepareProposal`

`CheckTx` currently permits transactions into the mempool as long as they can deserialize to our `Tx` type

https://github.com/anoma/namada/blob/2fb565e44f23c00d67b9f585bbca822eef204f0d/apps/src/lib/node/ledger/shell/mod.rs#L569-L583

In `PrepareProposal`, we explicitly exclude any transactions that Tendermint passes us from the mempool which don't pass some extra validation that happens during `process_tx`, and that aren't `TxType::Wrapper(_)`. So these transactions can never be included in a block.

https://github.com/anoma/namada/blob/2fb565e44f23c00d67b9f585bbca822eef204f0d/apps/src/lib/node/ledger/shell/prepare_proposal.rs#L40-L53

e.g. `TxType::Protocol` transactions pass `CheckTx` and go into the mempool but will always be excluded during `PrepareProposal` if Tendermint passes them to the ledger.

Preliminarily this issue could be low priority as worst case the mempool gets polluted with transactions that will never be included in a block, but this could have performance implications.

**Comment by cwgoes** [comment]
@sug0 what is the status of this w.r.t. the latest block space allocator work?
