### ISSUE TITLE
allow to configure CometBFT genesis consensus params

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#2026]
Allow to configure the cometBFT genesis consensus params from our genesis config, i.e.:

```rust
pub struct Params {
    /// Block size parameters
    pub block: Option<block::Size>,

    /// Evidence parameters
    pub evidence: Option<evidence::Params>,

    /// Validator parameters
    pub validator: Option<ValidatorParams>,

    /// Version parameters
    pub version: Option<VersionParams>,
}
```

We don't need the `evidence` params as outdated evidence is being handled in the ledger.

Depends on #711

**Comment by adrianbrink** [comment]
Needs to be coordinated with https://github.com/anoma/namada/pull/2122

**Comment by sug0** [comment]
https://github.com/anoma/namada/pull/2187
