### ISSUE TITLE
Check if Bridge is disabled to reject tx in Bridge pool VP

### ISSUE THREAD

**Issue by sug0** [anoma/namada#2027]
if the bridge is disabled through a governance vote, the Bridge pool may grow arbitrarily large. the Bridge pool VP should reject txs when the bridge is disabled

**Comment by Kofituo** [comment]
@sug0 @brentstone @tzemanovic 
Hello, I'd like to contribute to this project and I'd like to address this issue. May I know how to go about this issue, for instance the relevant lines of code involved?

**Comment by sug0** [comment]
@Kofituo  The patch is relatively simple: you need to hook up a condition to `shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs`, which is where the Bridge pool VP lives, rejecting transactions if the Ethereum Bridge is disabled. Look in `ethereum_bridge/src/storage/eth_bridge_queries.rs` to determine how to test if the Bridge is disabled or not.
