### ISSUE TITLE
Replace uses of hardcoded `address::tokens()` with fetching token addresses from the wallet

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#203]
When initially populating the wallet, and when calling `anomac balance` without specifying a token, we use a hardcoded set of test token addresses.

https://github.com/anoma/namada/blob/26a0b67b22090cdaa5a12cd1b7c6c0ff6d4a56a3/shared/src/types/address.rs#L525-L537

Instead of this hardcoded set, we should delegate to whatever is in the wallet (once we mark out token addresses as in https://github.com/anoma/namada/issues/135  ). When initially populating the wallet, we shouldn't put tokens in there which might not exist - at most only the token(s) that will definitely exist in a chain (`XAN`/`NAM`?).

**Comment by cwgoes** [comment]
@karbyshev can you take this on as part of the wallet work?

**Comment by karbyshev** [comment]
@tzemanovic Is it still relevant?

**Comment by tzemanovic** [comment]
> @tzemanovic Is it still relevant?

done in #1081
