### ISSUE TITLE
Airdrops Feature

### ISSUE THREAD

**Issue by adrianbrink** [anoma/namada#2038]
We'll only implement pre-genesis airdrops (ie a server collects addresses and the AF puts them into its genesis block proposal)

- this doesn't restrict future on-chain airdrops 
- but it means that we don't have to implement a new transaction type on-chain for claiming.

The website is needs to implement roughly the following flow:
- a user goes to [genesis.namada.net](http://genesis.namada.net/) and is shown available airdrop options
    - options for airdrops: github activity, ibc activity, ethresearch activity (we can copy all of this from celestia), osmosis activity, cosmos activity, zcash activity
    - the user connects their GH account or their wallet in order to proof to the website that he executed certain actions or held certain assets at a certain date (we need to pick this and user may have to proof it by creating a signature with their zcash/osmosis/keplr wallet)
    - the website shows the user the probable airdrop amount in nam
- the user generates a new seed phrase with their wallet of choice (probably only support namada extension) and then enters that new address in the claims field
- the user hits "claim" which sends the proof of their activity + their airdrop address to the backend server
    - the backend server verifies the proof and records the address along with the amount (we can also do the final amount calculation later, this is what celestia did)
    - the website responds with, you've successfully claimed

**Comment by cwgoes** [comment]
Tracked elsewhere.
