### ISSUE TITLE
Node shutdown if governance proposal requires it

### ISSUE THREAD

**Issue by Fraccaman** [anoma/namada#2053]
Governance proposal should have a flag to indicate if a restart (to update binaries or restart state) is needed. Namada node should be able to listen for ended governance proposal with a positive outcome and stop ur node automatically. 
The latter feature should be able to turn on or off this feature.

**Comment by cwgoes** [comment]
(there should be a configuration option to disable this feature if desired)

**Comment by grarco** [comment]
Closing this as we already have a mean to achieve the same goal: the halt height can be written in the proposal's description and the user can simply rerun the node with `namada node ledger run --run-until <block height>` if the proposal passes
