### ISSUE TITLE
Prepare PoS VP for mainnet

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#2059]

**Comment by cwgoes** [comment]
Can you explicate this issue further?

**Comment by brentstone** [comment]
I don't think we have to do much here since we are whitelisting transactions, but just wanted to make an issue as a reminder to take a look. Can @tzemanovic comment as well?

**Comment by tzemanovic** [comment]
that's right, I think only thing we might need to check is PoS params changes from an accepted gov proposal
