### ISSUE TITLE
Cross-test HD key derivation between Ledger device, Namada extension, and SDK implementation

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2067]
We should be able to:
- [x] export a mnemonic from the SDK, import it into the Ledger device, and derive the same keys (as the SDK)
- [x] export a mnemonic from the Ledger device, import it into the SDK, and derive the same keys (as the Ledger device)

**Comment by cwgoes** [comment]
Note: If we import the SDK into the extension instead of using native HD code, we should test against an external HD library, e.g. [this one](https://github.com/meherett/python-hdwallet), and make sure the outputs match.

**Comment by adrianbrink** [comment]
@sug0 @murisi did one of you complete this?

**Comment by sug0** [comment]
I only tested an independent implementation (https://github.com/heliaxdev/namada-wallet-go) against `namadaw`.
