### ISSUE TITLE
Unable to query shielded balances of tokens received over IBC after updating epoch

### ISSUE THREAD

**Issue by yito88** [anoma/namada#2087]
It is related to not only `IbcToken` but also `Erc20` tokens.

When the epoch is updated after receiving a token over IBC, this shielded balance has only the epoch when the token is received.
https://github.com/anoma/namada/blob/c82a0b3bbf69f09f5f794e9bc5f25d43bad591bf/apps/src/lib/client/rpc.rs#L843-L846

Currently, we update the conversion state only for pre-existing tokens.
https://github.com/anoma/namada/blob/c82a0b3bbf69f09f5f794e9bc5f25d43bad591bf/core/src/ledger/storage/masp_conversions.rs#L217

**Comment by cwgoes** [comment]
Would we need to add entries to the conversion table by default, for new tokens? This may be dangerous, since any number of new tokens can be created - we should think about this. First, though, can you explicate exactly what you mean?

**Comment by yito88** [comment]
I faced an issue with not being able to query the balance of `IbcToken` received at the previous epoch.
In `query_shielded_balance()`, `compute_shielded_balance()` returned the following `MaspAmount` as `balance`. 
```
MaspAmount({(Epoch(2), Internal IbcToken: 8dc92a4843306e81055aad27883459d43410a3bb: atest1d93xxw368pjxxwfjvy6rsdpnxvcrvefcxycr2dtpv9jrydec8qengdfevs6rxdp3xpsnxcnzxv9rns): 10})
```
After that, to get the `total_balance`, it could `get` nothing with the current epoch (3).
https://github.com/anoma/namada/blob/c82a0b3bbf69f09f5f794e9bc5f25d43bad591bf/apps/src/lib/client/rpc.rs#L843-L846

**Comment by yito88** [comment]
We can query the shielded balance of IBC tokens now
