### ISSUE TITLE
Remove PoS VP `panic::catch_unwind`

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#21]
Depends on anoma/namada#12, anoma/anoma#435 and anoma/namada#17

Remove the temporary measure in `apps/src/lib/node/ledger/protocol/mod.rs` and `UnwindSafe + RefUnwindSafe` impls in `shared/src/ledger/pos/vp.rs` that runs the PoS VP in a new thread to catch panics.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763032614644) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@brentstone do you know if this is still applicable?

**Comment by tzemanovic** [comment]
we still have this in
