### ISSUE TITLE
TxInitValidtor no `threshold` argument

### ISSUE THREAD

**Issue by bengtlofgren** [anoma/namada#2146]
If no `threshold` argument is passed when running `namadac int-validator`, the tx just seems to be a no-op. It should return either an error or default to `1`.

**Comment by Cryptmenic** [comment]
This is better now

**Comment by Kofituo** [comment]
Is this solved now?

**Comment by brentstone** [comment]
I believe this has been fixed in a prior PR when reworking `init-validator`
