### ISSUE TITLE
wallet store decoding error is misleading

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#2151]
When the format of the wallet.toml is incorrect, running commands that load the wallet fail with a misleading error (e.g. `No pre-genesis wallet found at ...`) instead reporting decoding error

**Comment by Kofituo** [comment]
Hello. I'm working on this issue. I'd like more information about it. How can I reproduce this error? 
I see the error is related to this method: https://github.com/anoma/namada/blob/50caebb38c07fb43dbf102e3817eafd4ffd693fd/apps/src/lib/client/utils.rs#L936-L943

**Comment by tzemanovic** [comment]
hi @Kofituo ! It looks like the behavior has slightly changed in more recent versions. You can reproduce it by manually editing a wallet file (`{base_dir}/pre-genesis/wallet.toml}`) to contains some invalid contents. Using a wallet command (e.g. `namadaw --pre-genesis list`) doesn't seem to print anything on latest release v0.29. For a chain wallet (e.g. `{base_dir}/{chain_id}/wallet.toml}`) the command panics on `unwrap` of `None`

**Comment by Kofituo** [comment]
@tzemanovic thanks for the feedback. I'll give it a try. Could you kindly take a look at the linked pr as well?

**Comment by tzemanovic** [comment]
@Kofituo the PR lgtm!

**Comment by cwgoes** [comment]
@tzemanovic Is this still applicable? Should we merge the linked PR on the fork here?

**Comment by tzemanovic** [comment]
> @tzemanovic Is this still applicable? Should we merge the linked PR on the fork here?

yeah, will do
