### ISSUE TITLE
genesis validator setup, Is documentation deprecated?

### ISSUE THREAD

**Issue by Fabryprog** [anoma/namada#2162]
Hello everyone,

I am trying to follow the documentation but I have a "syntax error" during "genesis validator setup" section (https://docs.namada.net/operators/validators/genesis-validator-setup)

> 1. Create your validator keys:
export ALIAS="CHOOSE_A_NAME_FOR_YOUR_VALIDATOR"
export PUBLIC_IP="LAPTOP_OR_SERVER_IP"
namada client utils init-genesis-validator --alias $ALIAS \
--max-commission-rate-change 0.01 --commission-rate 0.05 \
--net-address $PUBLIC_IP:26656

When I execute that command I have the following error

```
namada client utils init-genesis-validator --alias $ALIAS \
--max-commission-rate-change 0.01 --commission-rate 0.05 \
--net-address $PUBLIC_IP:26656
error: the following required arguments were not provided:
  --source <source>
  --transfer-from-source-amount <transfer-from-source-amount>
  --self-bond-amount <self-bond-amount>

Usage: namada client utils init-genesis-validator --source <source> --alias <alias> --net-address <net-address> --commission-rate <commission-rate> --max-commission-rate-change <max-commission-rate-change> --transfer-from-source-amount <transfer-from-source-amount> --self-bond-amount <self-bond-amount>

For more information, try '--help'.
```

Thanks a lot

**Comment by Fraccaman** [comment]
@bengtlofgren

**Comment by bengtlofgren** [comment]
Docs have now been updated

https://github.com/anoma/namada-docs/pull/207
