### ISSUE TITLE
“No such file or directory” crash in `anoma client`

### ISSUE THREAD

**Issue by ruuda** [anoma/namada#223]
```
$ anoma --version
Anoma v0.5.0-361-gf1afdff

$ anoma client epoch
2022-07-27T12:12:55.534792Z  INFO anoma_apps::cli::context: Chain ID: anoma-internal.000000000000000
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: apps/src/lib/config/genesis.rs:597

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```

This happens because I wasn’t passing `--base-dir`, but that’s not obvious from the crash. It would be nice if it prints a helpful error that explains how to create or select the base directory.

**Comment by james-chf** [comment]
+1, these commands should eventually provide a friendlier message. The panic may be happening because no chain has been joined (and so it's defaulting to some chain ID `anoma-internal.000000000000000`). Related issue - https://github.com/anoma/namada/issues/97
