### ISSUE TITLE
Refine the storage

### ISSUE THREAD

**Issue by yito88** [anoma/namada#2265]
Related to #1457 #1458 #1459

Our current storage API is tightly coupled with Merkle Tree and Subspace. For instance, data that doesn't require Merklization and diffs, and is specifically related to replay protection, necessitates a special API like `write_replay_protection_entry`, instead of using other write functions. Additionally, there's a risk of unintended usage, as seen in a previous bug, where, ideally, data should be written to `write_log` except for testing, but an API allowing direct writes to storage before committing a block makes unintended use easier.

**Comment by yito88** [comment]
Indeed, `wl_storage.write()` and `wl_storage.storage.write()` were confused (#1709). It would cause an inconsistent state.
We should basically use `wl_storage.write()` to write any data before committing a block because it writes data to only the write log. In the commit, these data in the write log are merklized and stored into the RocksDB.
For testing, we have to write data to RocksDB directly by `wl_storage.storage.write()` to make each initial state.

`PersistentStorage` is using `RocksDB`. `TestStorage` is using `MockDB` which has only the latest state. It means that it can't retrieve the old data by specifying a height. Tests requiring old data have to use `PersistentStorage`.

**Comment by yito88** [comment]
In my opinion, we need the following write APIs:
- Basic write
  - Write data into the write log (It will be persistent in the commit)
  - Written data will be merklized in the commit (tracked by the Merkle tree)
  - Written data can be read by specifying the height (It can be read from Diffs)
  - Currently almost all data
- (Write with diffs, without merklizing)
  - Write data into the write log
  - Not merklzed
  - Diffs
  - I guess there is no applied data for now (If we could apply some data, the size of Merkle tree would be decreased)
- Write without merklizing and storing diffs
  - Write data into the write log
  - Not merklized
  - No diff
  - E.g. replay protection
- Write to the storage directly
  - For only testing
  - Write data into the storage bypassing the write log 
    - To make the test state without commit
  - If you need merklizing/diffs, use basic write and commit (e.g. IBC testing)

**Comment by brentstone** [comment]
Thx @yito88. Couple questions of each of these APIs:

- Write with diffs, no merklization
  - we want such data written via this API to not be merklized upon a commit?
  - just to clarify, it sounds like there is nothing currently in the codebase that would need this API? If I'm wrong, can you provide an example of such a situation where this would be a useful upgrade?
- Write outout merklizing or storing diffs
  - is replay protection the only use case here?
- Write to storage directly and immediately
  - can you provide some examples of tests that should use / require this?

**Comment by yito88** [comment]
>- Write with diffs, no merklization
>.  - we want such data written via this API to not be merklized upon a commit?

Yes

>   - just to clarify, it sounds like there is nothing currently in the codebase that would need this API? If I'm wrong, can you provide an example of such a situation where this would be a useful upgrade?

Right, there is no data to be written by this API now

>- Write outout merklizing or storing diffs
>  - is replay protection the only use case here?

Yes, only replay protection

>- Write to storage directly and immediately
>  - can you provide some examples of tests that should use / require this?
https://github.com/anoma/namada/blob/9562c1602be0c7a9e40cc486cc673203b6737a98/shared/src/vm/wasm/run.rs#L782
I checked through tests briefly, and it seams there are few writes to store data to the storage directly.

I think we should review all data types to be written to the storage for more efficient writing.
We don't have other options now because we have only the basic write for now (except for replay protection write).
We might not need to add extra APIs.
