### ISSUE TITLE
Functionality to easily run a development Ethereum node with Ethereum bridge smart contracts deployed

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#228]
We should have a way of running a local ledger node alongside an Ethereum node of some sort (e.g. `geth`, or some dummy Ethereum node like a Hardhat node), with the [Ethereum bridge smart contracts](https://github.com/anoma/ethereum-bridge) deployed and the local Namada chain configured to use them.

Dependent tasks
- https://github.com/anoma/namada/issues/686
- https://github.com/anoma/ethereum-bridge/issues/24

**Comment by james-chf** [comment]
At the moment, the ledger always starts up `geth` on `http://127.0.0.1:8545` and then the oracle component connects to it via that endpoint. We could allow the setting of a custom `ETHEREUM_URL` envvar and, if set, not start up `geth`.

We may want to start `geth` out-of-process on `http://127.0.0.1:8545` and have the ledger still use it, or use some remote Ethereum API like Infura. This would provide the most flexibility for testing.

**Comment by james-chf** [comment]
The best way to do this (imo) may be to use something like `npx hardhat node` and then automatically deploy all the smart contracts, then start up the ledger pointing at the local Hardhat node using functionality from https://github.com/anoma/namada/pull/253

**Comment by cwgoes** [comment]
@james-chf what is the status of this?

**Comment by james-chf** [comment]
Currently WIP in this PR - https://github.com/anoma/ethereum-bridge/pull/44 - also tracked in this issue - https://github.com/anoma/ethereum-bridge/issues/24

**Comment by james-chf** [comment]
Closed by https://github.com/anoma/ethereum-bridge/pull/44
