### ISSUE TITLE
wallet address look-ups in client results

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#23]
For client commands that print out some outputs that include bech32m encoded address(es), it would be nice to try to reverse look-up these from the wallet's address book and show the aliases instead when available. For this, we might want to switch the address book in the `wallet::store` from regular `HashMap` to a bijective map (e.g. https://crates.io/crates/bimap)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763115228805) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@karbyshev can you take this on as part of the wallet work?

**Comment by karbyshev** [comment]
Looks to me like it was already implemented in #311 and https://github.com/anoma/anoma/pull/1138 ?

**Comment by tzemanovic** [comment]
> @cwgoes Looks to me like it was already implemented in #311 and [anoma/anoma#1138](https://github.com/anoma/anoma/pull/1138) ?

[#1138](https://github.com/anoma/anoma/pull/) / https://github.com/anoma/namada/pull/264 added the mapping to the wallet, but I think there still are many commands that print raw addresses, for which we could try to look-up aliases from wallet. It's not a high-prio, but would be nice to do.

**Comment by cpp-phoenix** [comment]
I am picking it up if it's ok @tzemanovic

**Comment by cwgoes** [comment]
Not critical, external contributions welcome.
