### ISSUE TITLE
Add RPC method to query all tokens

### ISSUE THREAD

**Issue by Fraccaman** [anoma/namada#2301]

**Comment by DoTheBestToGetTheBest** [comment]
hey what do you means by all tokens ? tokens from 0 ?

**Comment by DoTheBestToGetTheBest** [comment]
and also this should be in sdk crate in rpc.rs right ?

**Comment by Fraccaman** [comment]
this needs to be in the sdk as RPC method and also in the CLI :) thanks for contributing!

**Comment by brentstone** [comment]
@Fraccaman what did you mean here by query all tokens?

**Comment by Fraccaman** [comment]
@yito88 already did in #2729
