### ISSUE TITLE
Error: cannot submit response since we detected a duplicate response

### ISSUE THREAD

**Issue by lucremoy** [anoma/namada#2304]
Thank you for the bug report. Please provide any information that may be relevant to the issue you're experiencing.

I get an error that says I cannot submit my response because of a duplicate response, however, this is the first and only response I have tried to complete.

**Comment by lucremoy** [comment]
Hello, I have not been told what to do about this.

**Comment by sug0** [comment]
use the community discord for matters unrelated with software bugs, and expose your problem in a detailed manner. if it is a software bug, fill out a new issue with a detailed description of the problem you encountered, so other people can attempt to reproduce it. we cannot guess what went wrong for you.
