### ISSUE TITLE
Argent Mobile Wallet Compatibility

### ISSUE THREAD

**Issue by CLTSZ** [anoma/namada#2306]
A couple of early supporters of the projects are unable to claim their share of the upcoming $NAM tokens.
Basically one of the main issues is that the claiming site is not allowing wallet connect, hopefully the team can reconsider enabling it.

Also a lot have donated way beyond the GR 10-15 which is filtered on the snapshot, in my opinion those who have donated using zksync lite one first few rounds is also a eligible wallet donating for the cause and development of public goods funding.

Thanks for your hardwork Namada Team!

**Comment by sug0** [comment]
please do not open airdrop related issues on this repository. we are only interested in software bug reports. we already have to sift through enough bug entries to correlate problems between two different bug reports... we do not need our bug tracker to be filled with essentially noise.
