### ISSUE TITLE
ibc-gen-shielded transactions aren't working as expected

### ISSUE THREAD

**Issue by McDaan** [anoma/namada#2308]
Every time I try to send funds from Namada's MASP to Cosmos testnet, I got this:

```
namada client ibc-gen-shielded --target cosmos1ay642tntyt36kpgu7x2ynkxptq0gar4qenf7kt --token NAM --amount 10 --channel-id channel-0 --port-id transfer
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: "Unknown payment address cosmos1ay642tntyt36kpgu7x2ynkxptq0gar4qenf7kt"
```

**Comment by yito88** [comment]
Thank you for reporting it.

The command `ibc-gen-shielded` generates MASP proof for the destination Namada chain before the following IBC transfer.
The destination `target` should be an address on a Namada chain.
After generating the proof as a file, you can request `ibc-transfer` with `--memo` to specify the file.
```
gaiad tx ibc-transfer transfer transfer channel-0 $namada_payment_address 10samoleans --from source --chain-id gaia --yes --memo $string_of_proof
```

But, sorry, there is a bug in the command. It assumes that the given token address is only Namada address now.
I'm fixing it.

**Comment by McDaan** [comment]
> Thank you for reporting it.
> 
> The command `ibc-gen-shielded` generates MASP proof for the destination Namada chain before the following IBC transfer. The destination `target` should be a payment address on a Namada chain. After generating the proof as a file, you can request `ibc-transfer` with `--memo` to set the proof as a string.
> 
> ```
> namada client ibc-gen-shielded --output-folder-path $proof_path --target $namada_payment_address --token samoleans --amount 10 --port-id transfer --channel-id channel-0
> 
> gaiad tx ibc-transfer transfer transfer channel-0 $namada_payment_address 10samoleans --from source --chain-id gaia --yes --memo $proof_as_string
> ```
> 
> But, sorry, there is a bug in the command. It assumes that the given token address is only Namada address now. I'm fixing it.

Played with your branch and tokens seems to arrive to Namada's MASP, but when checking balances:
````./namadac balance --owner testmasp
Last committed epoch: 18
The application panicked (crashed).
Message:  Error in the query: "Info log: RPC error: No conversion found for asset type: 5ba73ef32a0b05a17ba843cc240ca2aaed8d2a2ce4470724054331a195288369, error code: 1"
Location: /.../namada/sdk/src/rpc.rs:143
```
