### ISSUE TITLE
Public and Transparent key labels seems to be flipped in the extension

### ISSUE THREAD

**Issue by phy-chain** [anoma/namada#2351]
![image](https://github.com/anoma/namada/assets/108097051/c5f5f754-057f-48c4-8219-a413e3c81cbc)
The public address starts with **tpk** and the transparent starts with **tnam**
Is this normal ?
If the repo of the extension is public, I can submit a PR to fix that

**Comment by sug0** [comment]
this is expected. the `tpk` prefix  stands for "transparent public key", while `tnam` is the prefix used by transparent addresses. the transparent address (`tnam1...`) displayed in the extension has been derived from the public key also in the extension (`tpk1...`). by the way, for future interface related issues, please open a bug report in https://github.com/anoma/namada-interface
