### ISSUE TITLE
Add optional size-limited memo field to transactions

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2354]
We should add an optional size-limited memo field to transactions (say, limited to 1 KB), which can be filled with arbitrary data (which may be encrypted, likely in the case of a shielded transfer). This can be used to communicate e.g. an identifier corresponding to a payment to the recipient.

/ref https://forum.namada.net/t/messages-in-transactions/375

**Comment by Fraccaman** [comment]
to any transactions?

**Comment by yito88** [comment]
I think the size of a transaction is limited by a genesis parameter (#2187). Should we limit the memo field separately?

**Comment by cwgoes** [comment]
> to any transactions?

Yes.
