### ISSUE TITLE
Didn't receive airdrop

### ISSUE THREAD

**Issue by Yopeace123** [anoma/namada#2361]
Hi, i still didn't receive the airdrop if i try to claim.
Still recognize the same problem after your update. I'am Atom Holder and staker since 2021 with over 500$ of atom in staking.

There are my cosmos address:

cosmos1fxc55zcx2pqdunqvgx5rjlndqlj7gkmvf4dsz3

*Screenshot*

![namada airdrop](https://github.com/anoma/namada/assets/154340643/247c89b5-2502-435d-b0b1-570a9eac8d4b)

**Comment by sug0** [comment]
use the official channels (twitter, discord) to dispute your airdrop situation. please don't open issues on the ledger's github repository, as this is reserved for software bug reports and enhancements/feature requests. thank you.
