### ISSUE TITLE
Can't build bin files

### ISSUE THREAD

**Issue by VuKhuongDuy** [anoma/namada#2362]
I ran `make install` on my Ubuntu 22
with correct pre-requirement package version
But it always failed when build bin:
![Screen Shot 2024-01-04 at 23 03 07](https://github.com/anoma/namada/assets/36961577/8e7e1dfe-a4be-4c17-90e0-2341bc91aee7)

I used branch v0.28.2
protoc --version    ==>    libprotoc 3.12.4
cometbft version ==>  0.37.2

**Comment by sug0** [comment]
can you show the entire error message? post it on pastebin, for instance.

some preemptive analysis, though: your `protoc` version is lower than my system's. that could be one of the causes of the build failure. another possible cause is that you might have too little system memory. to build namada successfully you need, at least, around 16 GiB of RAM. if the latter is the cause, try switching to [mold](https://github.com/rui314/mold/) as your linker. their github page shows you how to make the switch.
