### ISSUE TITLE
After some epochs inflation is 0

### ISSUE THREAD

**Issue by Fraccaman** [anoma/namada#2364]
In latest testnet, we can see that after some epochs the inflation goes to 0.
![Screenshot 2024-01-03 at 00 41 03](https://github.com/anoma/namada/assets/9825521/a2bf4175-1945-4aa9-9fac-2c13d6504ec0)

**Comment by cwgoes** [comment]
Is that the first epoch, or some epoch in the middle?

**Comment by Fraccaman** [comment]
some epochs in the middle
