### ISSUE TITLE
Refactor validate_vote_ext_and_get_it_back

### ISSUE THREAD

**Issue by sug0** [anoma/namada#238]
[`validate_vote_ext_and_get_it_back`](https://github.com/anoma/namada/blob/3112352753a8dcfe45d2f3bfc9d126a7819f23c0/apps/src/lib/node/ledger/shell/vote_extensions.rs#L121) is doing a lot of checks that could be split into different sub-methods. We should refactor it a bit.

**Comment by cwgoes** [comment]
What a method name. @sug0 - just checking, is this still relevant?

**Comment by sug0** [comment]
yup. not a super high priority issue, but nevertheless, it is an issue xD
@cwgoes good enough for new hires to learn the ropes around our protocol tx logic? :P

**Comment by sug0** [comment]
implemented in https://github.com/anoma/namada/pull/2289
