### ISSUE TITLE
Remove genesis block checks for vote extensions

### ISSUE THREAD

**Issue by sug0** [anoma/namada#239]
Tendermint shouldn't give us vote extensions issued during the genesis block, so some of our checks in the ledger are probably redundant.

[Example 1](https://github.com/anoma/namada/blob/3112352753a8dcfe45d2f3bfc9d126a7819f23c0/apps/src/lib/node/ledger/shell/vote_extensions.rs#L138)
[Example 2](https://github.com/anoma/namada/blob/3112352753a8dcfe45d2f3bfc9d126a7819f23c0/apps/src/lib/node/ledger/shell/prepare_proposal.rs#L87)

If possible, we should remove this logic to clean up the ledger code a bit.

**Comment by cwgoes** [comment]
@sug0 is this still relevant?

**Comment by sug0** [comment]
@cwgoes there was some confusion for a while with the fact Tendermint has no concept of a genesis block. the first block is decided through consensus, with height 1. we made a distinction in Namada where the first block would have height 0, i.e. the genesis block, and sprinkled some logic around our code to handle it.

I'd say we should keep some of the logic anyway, because it is possible for Byzantine validators to fill in H=0 in a vote extension. the first height where they can vote for these protocol txs is at H=1. maybe we could rename error types, though, to lessen the confusion.
