### ISSUE TITLE
Make sure we support Tendermint fast sync and make it a node option

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#24]
We should support [fast sync](https://docs.tendermint.com/v0.32/tendermint-core/fast-sync.html), which is very convenient for syncing a node quickly, and expose it clearly through the CLI and/or configuration, although we should also include warnings about proof-of-stake security considerations.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763123459983) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@batconjurer do you know if we support this at the moment? (asking since it's related to the abci work)

**Comment by batconjurer** [comment]
@cwgoes The 0.34 docs claim it is on by default. We aren't changing the default value in the config, whatever it is. But it is not exposed outward at the moment.

**Comment by cwgoes** [comment]
OK, sounds like we don't need to do anything for now.
