### ISSUE TITLE
Implement validator set update vote extensions

### ISSUE THREAD

**Issue by sug0** [anoma/namada#242]
1. First, decouple vote extension logic from Ethereum events logic, by renaming types/functions/methods accordingly.
    1. For instance, instead of `VoteExtensionDigest`, we would have `EthereumEventsDigest`, or something equivalent.
    2. Merged in https://github.com/anoma/namada/pull/243
2. Introduce some baseline Rust types necessary to implement the rest of the changes.
    1. The types on the Rust side need to map to types on the Ethereum smart contract's side.
    2. Merged in https://github.com/anoma/namada/pull/273
3. Implement PrepareProposal changes.
    1. Merged in https://github.com/anoma/namada/pull/286
4. Implement ProcessProposal changes.
    1. Merged in https://github.com/anoma/namada/pull/372
5. Implement shimming of vote extensions, to accomodate to [our Tendermint 0.37.x version](https://github.com/tendermint/tendermint/tree/0b58342a46b1917a40d506e48e87448dcc8b3131), which ships without vote extensions enabled.
    1. Merged in https://github.com/anoma/namada/pull/437
6. Implement a way to call Ethereum bridge smart contract with the validator
   set update vote extension digest decision from Tendermint. In other words,
   we need a relayer from Namada to Ethereum.
    1. Merged in https://github.com/anoma/namada/pull/1157
7. Implement FinalizeBlock changes.
    1. Merged in https://github.com/anoma/namada/pull/683
8. Implement extend vote and verify vote extension calls.
    1. Depends on https://github.com/anoma/namada/issues/133.
    3. Partially implemented in https://github.com/anoma/namada/pull/286
    4. The rest of the required changes were merged in https://github.com/anoma/namada/pull/471
9. ??? Other misc. changes.
    1. We need two secp256k1 ethereum keys in `ShellMode`, one for governance (on Ethereum) and another for signing validator set update proofs. Signatures can't be from Namada validator keys. Related to https://github.com/anoma/namada/issues/133.
        i. Merged in https://github.com/anoma/namada/pull/278
        ii. Key storage was merged in https://github.com/anoma/namada/pull/471
    5. Store the version of `Bridge.sol` in storage. Related to https://github.com/anoma/namada/issues/249.
---
These changes can be implemented as separate PRs. Notes for these changes can be accessed [here](https://hackmd.io/aKXu06tkSTqsoRVCTn_XMA?view=).

**Comment by cwgoes** [comment]
@sug0 what's the status of this / what's remaining here? just #133 ?

**Comment by sug0** [comment]
@cwgoes #133 (which is just missing some extra PoS VP logic) and the work on the relayer. then the issue can be closed.

**Comment by sug0** [comment]
The only missing thing now is checking if a validator has eth hot/cold keys in the pos vp. @tzemanovic any news on the storage issues you guys were having?

**Comment by sug0** [comment]
Checking for the existence of validator keys is implemented by https://github.com/anoma/namada/pull/1840
We can close this issue
