### ISSUE TITLE
`init-network` should be able to optionally bundle wasm files along with the network config files

### ISSUE THREAD

**Issue by sug0** [anoma/namada#2423]
Currently, `init-network` generates a `${chain_id}.tar.gz` file containing network config toml files and a wasm checksums json file. It should also (optionally) contain the wasm files pointed to by the checksums file.

**Comment by cwgoes** [comment]
Most importantly, we should check the WASM hashes against the expected ones when starting the node.

**Comment by cwgoes** [comment]
https://github.com/anoma/namada/pull/3119 is sufficient for the time being.

**Comment by Fraccaman** [comment]
shouldn't we include the wasms in the chain tar.gz? and remove the download functionality from the ledger?

**Comment by cwgoes** [comment]
> shouldn't we include the wasms in the chain tar.gz? and remove the download functionality from the ledger? Otherwise we have to host infrastructure

I don't think so, we can just upload the WASMs to a separate repository on GitHub and use the raw download URLs?
