### ISSUE TITLE
Could not find wallet on Campfire

### ISSUE THREAD

**Issue by ekkis** [anoma/namada#2439]
I'm running a Campfire node on Docker as per the `namada-selfhost` project.  I've installed the v0.29.0 version of the binaries on my local host and have joined the network like this:
```bash
export NAMADA_NETWORK_CONFIGS_SERVER=https://testnet.luminara.icu/configs
namada client utils join-network --chain-id luminara.c3c6d2a524160fd4de13e
```
which seemed to work, however, when I attempt to look at a list of wallets (or to create one), I get the error:

> The application panicked (crashed).
> Message:  Could not find wallet at /Users/ekkis/Library/Application Support/Namada/luminara.c3c6d2a524160fd4de13e.
> Location: apps/src/lib/cli/context.rs:119

the backtrace for it looks like this:

>  ⋮ 7 frames hidden ⋮
>    8: namada_apps::cli::context::Context:🆕:h01402dcca8d03c65
>       at <unknown source file>:<unknown line>
>    9: namada_apps::cli::utils::Cmd::parse_or_print_help::h4971f719470acb98
>       at <unknown source file>:<unknown line>
>   10: namada_apps::cli::namada_wallet_cli::h221efca70dd6c1bf
>       at <unknown source file>:<unknown line>
>   11: namadaw::main::{{closure}}::h1cf3ebd820428d0c
>       at <unknown source file>:<unknown line>
>   12: namadaw::main::h17ec63b1417672b4
>       at <unknown source file>:<unknown line>
>   13: std::sys_common::backtrace::__rust_begin_short_backtrace::hd08ff72e85cfa58c
>       at <unknown source file>:<unknown line>
>   14: _main<unknown>
>       at <unknown source file>:<unknown line>

and in looking at the container, I see that in `/.local/share/namada/local.af25e423983e63d2105da665` there's a `wallet.toml`, but in my local `/Users/ekkis/Library/Application Support/Namada/luminara.c3c6d2a524160fd4de13e` directory it doesn't exist

I tried creating it by hand using the contents of the one in the node and now everything works, but obviously something is failing and needs fixing

**Comment by adrianbrink** [comment]
The docker image is using Ubuntu and there the default folder for application data is under `.local/`. On macOS the default folder for application is under `/Users/xxx/Library/Application Support/`. These defaults are not of Namada's choosing but rather the convention of the respective operating systems.

The wallet command was reworked on v0.30.x and I believe this issue has been fixed there.

**Comment by ekkis** [comment]
yeah, I'm agnostic to where the wallet file is stored.  merely pointing out that the process is broken.  let me try v0.30 and report back

**Comment by ekkis** [comment]
ok, with v0.30.1 I get a different error

`$ namada client utils join-network --chain-id public-testnet-15.0dacadb8d663`

> Downloading config release from https://testnet.luminara.icu/configs/public-testnet-15.0dacadb8d663.tar.gz ...
> Error downloading release: HTTP status client error (404 Not Found) for url (https://testnet.luminara.icu/configs/public-testnet-15.0dacadb8d663.tar.gz)

and you'll notice: 

`$ echo $NAMADA_NETWORK_CONFIGS_SERVER`

> https://testnet.luminara.icu/configs`

or do I need to be using a different chain-id?

**Comment by ekkis** [comment]
ah, never mind.  I see the only one listed there is `luminara.c3c6d2a524160fd4de13e` and that works, however that breaks with:

> Error downloading wasm: Error while downloading https://artifacts.heliax.click/namada-wasm/tx_claim_rewards.ebfb746fd7f557baf222b9fc47619e10f8af2acf2dfc9eb0a1ee30fc7ee656f3.wasm: 404 Not Found
> Error downloading wasm: Error while downloading https://artifacts.heliax.click/namada-wasm/tx_init_proposal.eb8526d2bcd1452ce44434095d1ebdb6a3044e6c26b635919aa8df025d79fa56.wasm: 404 Not Found

**Comment by ekkis** [comment]
the above notwithstanding, I can do a wallet listing after joining the network.  should I leave this open so the above can be addressed or close since the original issue was fixed?

**Comment by okwme** [comment]
This still seems to be an issue on shielded expedition.
I don't have a wallet inside `shielded-expedition.b40d8e9055` and I'm unable to create one until I have one...

```
> namada wallet derive --alias okwme
The application panicked (crashed).
Message:  Could not find wallet at ~/.local/share/namada/shielded-expedition.b40d8e9055.
Location: crates/apps/src/lib/cli/context.rs:152

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Same thing happens when I try using the `gen` command:

```
> namada wallet gen --alias foo
The application panicked (crashed).
Message:  Could not find wallet at ~/.local/share/namada/shielded-expedition.b40d8e9055.
Location: crates/apps/src/lib/cli/context.rs:152

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by okwme** [comment]
found a workaround:

use the following command to create a wallet for a pre-genesis validator then move the wallet file to the network directory.

```
namadaw --pre-genesis derive --unsafe-dont-encrypt --alias name
mv ~/.local/share/namada/pre-genesis/wallet.toml ~/.local/share/namada/shielded-expedition.b40d8e9055/`
```
if you're not a pre-genesis validator you can remove this folder now
```
rm -rf ~/.local/share/namada/pre-genesis/
```

Seems like this is still a catch-22 bug right? Can't create a wallet without a wallet.

**Comment by TheHustler0** [comment]
Manually creating 'wallet.tom' under shielded-expedition.b40d8e9055/ does the also trick but it requires knowing the expected output format.
