### ISSUE TITLE
--unsafe-show-secret fails

### ISSUE THREAD

**Issue by ekkis** [anoma/namada#2450]
I need the private key for one of my wallets.  I can see that information in the `wallet.toml` but it's encrypted.  however the aforementioned parameter to wallet listing should work.  it doesn't.  if I run:

`$ namada wallet list --keys`

I see:

> Known transparent keys:
>   Alias "main" (encrypted):
>     Public key hash: 9B94E0031AD79F0FA282D935D28C0E23D11A60FA
>     Public key: tpknam1qplgxtcuussrctehrndrx6f2ad7yml0mfkt2yvc3nqfnftjrpfswz22uuyd

and running it with the parameter:

`namada wallet list --keys --unsafe-show-secret`

shows me the same output

> Known transparent keys:
>   Alias "main" (encrypted):
>     Public key hash: 9B94E0031AD79F0FA282D935D28C0E23D11A60FA
>     Public key: tpknam1qplgxtcuussrctehrndrx6f2ad7yml0mfkt2yvc3nqfnftjrpfswz22uuyd

I'm running v0.30.1 of the binaries.  help?

**Comment by Fraccaman** [comment]
@karbyshev can you take a look?

**Comment by karbyshev** [comment]
@ekkis You should pass `--decrypt` option, which allows to decrypt the secret keys. The secret keys are not printed unless `--unsafe-show-secret` is passed, additionally.

**Comment by ekkis** [comment]
it wasn't intuitive I should pass both but it works.  thank you
