### ISSUE TITLE
No permissions for default NAMADA_BASE_DIR in container.

### ISSUE THREAD

**Issue by egasimus** [anoma/namada#2518]
Continuation of https://github.com/anoma/namada-shielded-expedition/issues/206

People seem to be solving this by escalating to root within the container, which is suboptimal from a security perspective.

I suggest one of the following fixes be applied to the Docker image:

1. Pre-create `/.namada` directory owned by `namada` user, **or:**
2. Set default value of `NAMADA_BASE_DIR` to `/home/namada/.namada`.

**Comment by Fraccaman** [comment]
do you wanna open a PR?
