### ISSUE TITLE
VoteTx should fetch all the voter delegations on wasm

### ISSUE THREAD

**Issue by Fraccaman** [anoma/namada#2523]
Right now, the `vote_proposal` tx is expecting from the client a list of `validators` for which the voter has a delegation to. The Governance VP is then validating the list, but the validation logic is redundant and not optimal. We should instead fetch the voter delegation list directly from the wasm transactions.

**Comment by Fraccaman** [comment]
@brentstone it would come real handy if we could easily fetch the set of validator addresses for a specific delegator

**Comment by brentstone** [comment]
If I recall correctly, there is a dependency issue between proof-of-stake and governance here that would possibly require a refactor.
