### ISSUE TITLE
Namada does not progress from "crediting naan tokens" screen

### ISSUE THREAD

**Issue by Fible1** [anoma/namada#2525]
To replicate:

Install v 0.30.1 normally and start the node prior to network launch. It does not default ot "genesis time is in the future", rather it gets on the "crediting naan" interface of the node startup process, particularly here 

`_chain: Crediting 2321.272897 naan tokens to tpknam1qpzy9wl9efg3x26gpupaa6pmmkdrmzxjkx4unr28dhmh4jwqasjzwcghjs8
2024-02-06T00:47:32.572778Z  INFO namada_apps::node::ledger::shell::init_chain: Crediting 2321.272897 naan tokens to tpknam1qpzygwkus0ce8thsyd9dfpx9fdntf5y4rmenzuwlr6v02333a8flw5lwu3y`

There was a discussion about this on https://discord.com/channels/833618405537218590/1193958565531103272/1204201861339680848

Some users claim multiple restarts of the node fix the issue, this has not been the case for me. I downgraded the node without reinstalling and that did not help, while another user suggested a fresh install with previous version solves the issue.

I am @fible1 on Discord fible1 |NodeSoda
![namada stuck here](https://github.com/anoma/namada/assets/6124934/dcdf5c41-4107-41b9-b9c6-e3fc83395571)

**Comment by Fible1** [comment]
[Uploading logs1.txt…]()

**Comment by Fible1** [comment]
[logs1.txt](https://github.com/anoma/namada/files/14173502/logs1.txt)

**Comment by gnosed** [comment]
Have you checked the syslog? It should be there if you are a genesis validator

**Comment by Fraccaman** [comment]
this is a logging problem, not related to namada.
