### ISSUE TITLE
Mainnet readiness: modularization and technical debt minimization

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2529]
Objective:
- Modularize the codebase so that abstractions are clean & understandable, and establish a clear separation of concerns and appropriate dependency graph.
- Minimize technical debt so we don't need to deal with it in the future.

Dependencies:
- [x] https://github.com/anoma/namada/issues/2486
- [x] https://github.com/anoma/namada/issues/2485
- [x] https://github.com/anoma/namada/issues/2484
- [x] https://github.com/anoma/namada/issues/2483
- [ ] https://github.com/anoma/namada/issues/2287
- [x] https://github.com/anoma/namada/issues/802
- [x] https://github.com/anoma/namada/issues/2548
- [x] https://github.com/anoma/namada/issues/2549
- [x] https://github.com/anoma/namada/issues/2550
- [x] https://github.com/anoma/namada/issues/2564
- [ ] https://github.com/anoma/namada/issues/2111
- [ ] https://github.com/anoma/namada/issues/2553
- [ ] https://github.com/anoma/namada/issues/2554
- [ ] https://github.com/anoma/namada/issues/2556
- [ ] https://github.com/anoma/namada/issues/2623
- [ ] https://github.com/anoma/namada/issues/2523
- [ ] https://github.com/anoma/namada/pull/2630

**Comment by brentstone** [comment]
Closing here in favor of using the Project and Milestones
