### ISSUE TITLE
Mainnet readiness: security

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2531]
Objective:
- Ensure that the codebase (especially core protocol / state machine) has no bugs.
- Maximize defense-in-depth to contain any bugs which might slip through.
- Minimize the chances that an adversary can find an edge case which halts the chain.
- Minimize dependency security surface area.

Dependencies:
- [ ] https://github.com/anoma/namada/issues/759
- [ ] https://github.com/anoma/namada/issues/1677
- [ ] https://github.com/anoma/namada/issues/826
- [ ] https://github.com/anoma/namada/issues/944
- [ ] https://github.com/anoma/namada/issues/1708
- [ ] https://github.com/anoma/namada/issues/1562
- [ ] https://github.com/anoma/namada/issues/1024
- [ ] https://github.com/anoma/namada/issues/1023
- [x] https://github.com/anoma/namada/issues/2546
- [ ] https://github.com/anoma/namada/issues/2552
- [ ] https://github.com/anoma/namada/issues/2555
- [ ] https://github.com/anoma/namada/issues/2576
- [ ] 1-2 weeks of intensive internal red teaming with no finds

**Comment by brentstone** [comment]
Closing in favor of using the Project and Milestones
