### ISSUE TITLE
Mainnet readiness: testing

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2532]
Objective:
- Ensure that tests are present and appropriate to the context (e.g. basic functionality is covered by unit tests, end-to-end / black-box behaviour is covered by end-to-end tests, and complex invariants are covered by property tests).
- Ensure that we have metrics to understand test coverage and when it changes.
- Ensure that running tests is fast, convenient, and reliable.

Dependencies:
- [ ] https://github.com/anoma/namada/issues/2350
- [ ] https://github.com/anoma/namada/issues/1497
- [x] https://github.com/anoma/namada/issues/71
- [ ] https://github.com/anoma/namada/issues/305
- [ ] https://github.com/anoma/namada/issues/75
- [ ] #2661

**Comment by brentstone** [comment]
Closing in favor of Milestones and Project
