### ISSUE TITLE
Remove the ability to update an account's VP

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2554]
We do not need the ability for an account to update their VP in the initial version of Namada, and we should remove it.

**Comment by grarco** [comment]
Should we also remove the vp hash from `InitAccount` and just assign the default `vp_user` to all the established addresses?

**Comment by cwgoes** [comment]
> Should we also remove the vp hash from `InitAccount` and just assign the default `vp_user` to all the established addresses?

Yes.

**Comment by tzemanovic** [comment]
also rm the `vp` field from `genesis::transactions::ValidatorAccountTx`

**Comment by grarco** [comment]
Closing this as it seems we don't need it anymore
