### ISSUE TITLE
Pre-mainnet shell rework/cleanup

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2564]
Supersedes https://github.com/anoma/namada/issues/2550, https://github.com/anoma/namada/issues/2549, and https://github.com/anoma/namada/issues/2548, per discussion.

- [x] Keep the ABCI++ shims to preserve the future upgrade path here. Internally audit this code, clean up any minor issues (e.g. https://github.com/anoma/namada/issues/2546), and make sure it's readable.
- [ ] #2598
- [ ] #2656

**Comment by brentstone** [comment]
Closing, since all remaining open PRs are tracked in Milestones and Project now.
