### ISSUE TITLE
Allow multiple transfers in a single tx

### ISSUE THREAD

**Issue by grarco** [anoma/namada#2596]
We should allow multiple token transfers in a single transaction, i.e. involving more than one sender/receiver and with different tokens. We could either modify the current `tx_transfer` or come up with a different one. We'll also need to update the client and SDK to produce this new type of transactions.

**Comment by cwgoes** [comment]
It may make sense to make this change in conjunction with https://github.com/anoma/namada/issues/1677.

**Comment by cwgoes** [comment]
Moving this to phase 1 so we can avoid breaking transaction format changes.

**Comment by cwgoes** [comment]
Note that this is two parts:
- Batching multiple inner transactions in one transaction (this is #3103)
- Vectorized balance changes in a single transfer inner tx (no PR yet)
