### ISSUE TITLE
ethereum bridge pool command in CLI result in a "permission denied"

### ISSUE THREAD

**Issue by phy-chain** [anoma/namada#2600]
Not sure if this is a bug, but I've tried several variations to get this command to work, but it always ends up with the same error :

`namada ethereum-bridge-pool query --node 194.163.172.168:26657`

The result is the same with or without the node option

> Error: 
>  0: Command namadar failed with Permission denied (os error 13).

Could we get a more insightful error to find the proper paramters for this command ?

**Comment by Rigorously** [comment]
```
 Command namadar failed with No such file or directory (os error 2).
```

`Relayer commands are found in the namadar binary, which at the moment can only be installed from source.`

**Comment by Rigorously** [comment]
Also it looks like Anoma is not ready to release the Ethereum bridge at this time: https://github.com/anoma/namada/issues/2598

**Comment by sug0** [comment]
Ethereum Bridge functionality is not expected to work during this testnet. As @Rigorously as pointed out, we're actually in the process of disabling its code.
