### ISSUE TITLE
CLI hangs on shielding

### ISSUE THREAD

**Issue by opsecx** [anoma/namada#2614]
When trying to shield an asset (source: implicit address - tnam, target shielded address - znam), the command line simply hangs and nothing happens. Several users reporting this in discord. On v0.31.4. p

**Comment by brentstone** [comment]
I think this may be addressed at least in part by #2458. I don't think the command line was hanging necessarily, but it may be taking a long time to scan MASP notes, generate proofs, etc without providing any logs. Perhaps @batconjurer can comment.

**Comment by opsecx** [comment]
It takes so long (> several hours) that even if it's just a lack of progress bar, from a usability perspective it doesn't work imo.

**Comment by batconjurer** [comment]
This is indeed an issue with scanning. Both fetching all the blocks over the network to scan and attempting to decrypt are still part of the shielding transaction and this can take extremely long times. #2458 aims to make this a separate command (and it has progress bars) that can be done in down time so that once synced up, you can make shielded interactions quickly.

**Comment by batconjurer** [comment]
> > This is indeed an issue with scanning. Both fetching all the blocks over the network to scan and attempting to decrypt are still part of the shielding transaction and this can take extremely long times. #2458 aims to make this a separate command (and it has progress bars) that can be done in down time so that once synced up, you can make shielded interactions quickly.
> 
> So a bit like how monero-wallets work? having to sync if not used for a long time and once synced will behave rather rapidly?

That's the current plan. There may be more improvements down the line.

**Comment by opsecx** [comment]
> > > This is indeed an issue with scanning. Both fetching all the blocks over the network to scan and attempting to decrypt are still part of the shielding transaction and this can take extremely long times. #2458 aims to make this a separate command (and it has progress bars) that can be done in down time so that once synced up, you can make shielded interactions quickly.
> 
> > 
> 
> > So a bit like how monero-wallets work? having to sync if not used for a long time and once synced will behave rather rapidly?
> 
> 
> 
> That's the current plan. There may be more improvements down the line.

Thanks, appreciate the clarification. Feel free to close or keep open as best.
