### ISSUE TITLE
Add check in ``Update-account``  to not allow increasing ``--threshold above number`` of active public keys

### ISSUE THREAD

**Issue by spidey-169** [anoma/namada#2624]
## I think I have found a bug which renders a Multisig account unusable. 
This is when trying to increase the number of threshold for a Multisignature account. I created a multi-signatuere account with a single signer and then went on to do txns with it. Then I updarte the number of threshold of the account to 2 and this action though it shouldn't be allowed, went through. Now I cannot use this account at all for any transactions, as I can send no transactions through it as **threshold < total public keys** is violated. This is SEVERE as the user cannot access his funds in this wallet.

## DESCRIPTION:

The description for ``update-account -h`` says

``--threshold <threshold>
          The minimum number of signature to be provided for authorization. Must be less then the maximum number of public keys provided ``

To check, I created a multisig wallet with a single signer using this

```
namada client init-account --alias $WALLET_MULTISIG --public-keys $WALLET --signing-keys $WALLET --memo $MEMO
```

Successful

```
Wrapper transaction hash: 18A56855E8324279A88E190BEDDE5D0C3F97C116AD3AE6C32E400E7E3890608F
Inner transaction hash: 50DC8E7C183619086114227D7DC0B6A6E25DF9411616BBB56874999D59C34912
```

Then I tried to update-this account to have a threshold of 2. Now since this has only 1 public keys, this shouldn't be allowed as **threshold < total public keys**

However I was able to do it using this transaction, where I am providing two wallet keys for signing.

```
namada client update-account --address $WALLET_MULTISIG --threshold 2 --signing-keys $WALLET,$WALLET_2 --memo  $MEMO
```

```
Transaction added to mempool.
Wrapper transaction hash: C468C810B9A0191AC4A1E3513A74035F2A1DE99F73D3448D9E61863F5200A496
Inner transaction hash: A285AFB43F8A063C6EFB17D67D091CF21EC09C44C1F01C16E790BFBDC4F95831
Wrapper transaction accepted at height 22514. Used 23 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 22515. Used 7130 gas.
```

**The problem is that now I have an account with a threshold of 2 and Only one public Key.**

## Every Transaction from this wallet is rejected no matter what

To confirm account details

``
namada client query-account --owner $WALLET_MULTISIG 
``

```
Address: tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m
Threshold: 2
Public keys:
- tpknam1qzsq8k8hf8f89g6an4tx554g0qp2hfyqz8rjsmk87lnffjmc02esxywulpk
```
**Tried a couple of transactions and all rejected, and from what I can see this account is unusable.**

### A) Here I am trying with using 2 signers, which I used to update-threshold. This FAILS

```
namada client transfer --source $WALLET_MULTISIG --target $WALLET --token NAAN --amount 2 --signing-keys $WALLET,$WALLET_2 --memo $MEMO
```

```
Wrapper transaction hash: B16B03301C9B3E633D28244BB5ABC6D2674E27FFE523941497F94621FA0E1408
Inner transaction hash: 67DB15034431DA14C9F94E98F67ACC940720033491C262B2E7E80590C2DF737F

Transaction was rejected by VPs: [
  "tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m"
].
Changed keys: [
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m",
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd"
]
```

### B) Here I am trying with using 1 signers (Which was how originally it was created), which I used to update-threshold. This FAILS too

```
namada client transfer --source $WALLET_MULTISIG --target $WALLET --token NAAN --amount 2 --signing-keys $WALLET --memo $MEMO
```
```
Wrapper transaction hash: BC37FD3782A5DCC44C7D8437D2D00F7A7294371433D721B3226476CAAF18BC48
Inner transaction hash: 2ADF57C61C8B8856909F1BB55165121DE6674E06C8E147FA80BF95111E52A557
Wrapper transaction accepted at height 22722. Used 24 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m"
].
Changed keys: [
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m",
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd"
]
```

### FAIL 2: Here I am trying to update public keys to be 2 as well to somehow salvage it, still fails

```
namada client update-account --address $WALLET_MULTISIG --public-keys $WALLET,$WALLET_2 --signing-keys $WALLET,$WALLET_2 --memo $MEMO
```
```
Enter your decryption password: 
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 57F2E8C4D6939881CC9C92A4CDEFE2663F88663010882B63836F54B023E4068E
Inner transaction hash: C8710398FD9F8A2D09AE7E47CFC70DFDDBFB2D6A251DC603A7D8E345872BC2CB
Wrapper transaction accepted at height 22805. Used 24 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m"
].
Changed keys: [
  "#tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m/public_keys/data/00",
  "#tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m/public_keys/data/04"
]
```

### LAST ATTEMPT: FAIL: Trying to bring the threshold down to 1 also doesn't work.

```
namada client update-account --address $WALLET_MULTISIG --threshold 1 --signing-keys $WALLET,$WALLET_2 --memo $MEMO
```
```
Transaction added to mempool.
Wrapper transaction hash: F9818F322A2E7EA34F1B2E96A11B55564114430AEC7CC50639845415454E514F
Inner transaction hash: D0150992A0760CD511EB5F389E0BE02D57E09589C10CC7FCDE2DFCD8C1ED5F8B
Wrapper transaction accepted at height 22682. Used 23 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m"
].
Changed keys: [
  "#tnam1q8veg8w2v0azkzetch3ev92y0d6rg3a0su2x297m/threshold"
]
```

 ## Now I cannot use this account at all for any transactions, as I can send no transactions through it as **threshold < total public keys** is violated. 

Tagging @brentstone @Fraccaman  here. 

Cheers,

**Comment by Fraccaman** [comment]
maybe we can add a client side check but I dont see any bug here.

**Comment by spidey-169** [comment]
> maybe we can add a client side check but I dont see any bug here.

It shouldn't be allowed to change the threshold above the public keys right. Once this is done it cannot be changed back? Potentially bad from what I believe. Maybe I am missing something? Thanks

**Comment by Fraccaman** [comment]
you are messing up voluntarily your account. What would be the expected behaviour in your opinion? except for a client side check.

**Comment by spidey-169** [comment]
> you are messing up voluntarily your account. What would be the expected behaviour in your opinion? except for a client side check.

Haha, that is true. I was just advising, that this shouldnt be allowed maybe for a client side check then. Cool, I do like to mess with things. Thanks for the clarification

**Comment by spidey-169** [comment]
Updated description and your recommendation in the coments. Thanks

**Comment by Fraccaman** [comment]
Closing this issue and tracking in #2671
