### ISSUE TITLE
Refuse bond again after forced interruption during previous bond action.

### ISSUE THREAD

**Issue by bnjavod** [anoma/namada#2635]
When I was bonding to my post-genesis validator node. I suddenly want to modify the amount. So, I control-C while prompting me to input password. then, I got issues when bond in second time.

VALIDATOR_ALIAS=tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq 
WALLET=tnam1qz90sjngex259tvplx6wpga2722e0dv7dcr9xlzu
WALLET_PK=tpknam1qzf3c3csf6x68tjemcjnwxyummcevds7647kx5fy0w2k0wkl962evjxv08k
SELF_BOND_AMOUNT=27000

1. Bond firstly:
namadac bond \
  --validator $VALIDATOR_ALIAS \
  --source $WALLET \
  --signing-keys $WALLET \
  --amount $SELF_BOND_AMOUNT \
  --memo $WALLET_PK
Enter your decryption password:        <--- CTRL-C to interrupt 

2. Modify amount: 
    SELF_BOND_AMOUNT=27116

3.  Bond again:
  namadac bond \
  --validator $VALIDATOR_ALIAS \
  --source $WALLET \
  --signing-keys $WALLET \
  --amount $SELF_BOND_AMOUNT \
  --memo $WALLET_PK
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: D686894CE4E94738F1A0DB5348FBD1D9275495533EB0E95C70772264787F74F9
Inner transaction hash: 66224BF51A4A014BA23A90278A9A7A16474EE22847BB43493504AD1B6D90F97E
Wrapper transaction accepted at height 27446. Used 23 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq",
  "tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96"
].
Changed keys: [
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp",
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1qz90sjngex259tvplx6wpga2722e0dv7dcr9xlzu",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/bond/#tnam1qz90sjngex259tvplx6wpga2722e0dv7dcr9xlzu/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/bond/#tnam1qz90sjngex259tvplx6wpga2722e0dv7dcr9xlzu/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/lazy_map/data/000000000000I",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/total_deltas/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/total_deltas/lazy_map/data/000000000000I",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/deltas/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/deltas/lazy_map/data/000000000000I",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/state/lazy_map/data/0000000000006",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/state/lazy_map/data/000000000000A",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/state/lazy_map/data/000000000000I",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/state/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/total_bonded/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq/total_bonded/lazy_map/data/000000000000I",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96/state/lazy_map/data/0000000000004",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96/state/lazy_map/data/0000000000006",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96/state/lazy_map/data/0000000000008",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96/state/lazy_map/data/000000000000A",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96/state/lazy_map/data/000000000000I",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96/state/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000000I/data/#tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000000I/data/#tnam1qyuwul00hd37q9yngjlmpefxnyd05frj0vc4da96",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/below_capacity/lazy_map/data/000000000000I/data/FVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVP1L3JEVG/data/0000000000000",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/below_capacity/lazy_map/data/000000000000I/data/FVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV0MKHBVG/data/0000000000000",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000000I/data/000000000000000000000000000000000000000000006UASCH00/data/0000000000000",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000000I/data/00000000000000000000000000000000000000000000DJB8P000/data/0000000000000"
]

4. Check bonds, no more bonds on validator. Bonding's been refused any more.
namadac bonds --owner $WALLET
Last committed epoch: 7
Delegations from tnam1qz90sjngex259tvplx6wpga2722e0dv7dcr9xlzu to tnam1q9fh638spqdu4jys5a3gxnw6akgtvsemvcchtchq:
  Remaining active bond from epoch 2: Δ 100.000000
Active (slashed) bonds total: 100.000000
Bonds total: 100.000000

Withdrawable total: 0.000000

All bonds total active: 100.000000
All bonds total: 100.000000
All unbonds total: 0.000000
All unbonds total withdrawable: 0.000000

**Comment by cwgoes** [comment]
Closed by https://github.com/anoma/namada/pull/3681.
