### ISSUE TITLE
Exception after trying to unjail caused by change-consensus-key command

### ISSUE THREAD

**Issue by Liver-23** [anoma/namada#2640]
Steps:
1. Run the change-consensus-key command to create a new key and switch to it
`namadac change-consensus-key --validator liveraven --consensus-key liveraven-consensus-key --memo "<>" --signing-keys wallet`
Result: the message about key change appears with a notice that you need to change priv_validator_key as well 2 blocks before the new epoch (which is confusing since nothing happened and I still could sign blocks for the next ~1-2 epochs) 
2. Once the switch is done my validator stops signing blocks with an old key
3. Tried to change back to the original consensus key but the command reply was that it is in use already, when it was not from this moment
```
namadac change-consensus-key --validator liveraven --consensus-key liveraven-consensus-key --memo "<>" --signing-keys wallet
The consensus key is already being used.
```
4. Since there is no internal possibility to create the expected priv_validator_key I used the "convert" command from https://github.com/anoma/namada/pull/2516
Result: the file was successfully created and after switching to it the validator started to sign blocks again
5. Since missed enough blocks to be jailed I need to perform unjail command and it started to fail with the following exception:
```
namadac unjail-validator --validator liveraven --signing-keys wallet
Looking-up public key of tnam1qxzx92ztwjmtka0mdfd60wn7ejcljgx6sqe4800u from the ledger...
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 74012C8324BD93EA7BAF94BE705E12D67408E51138ED205287BC06B7BB0D42D1
Inner transaction hash: 1FA46FEE07EFB433CD453D53CAD1CCF62B1293175F2390A2678441E8760B9E76
Wrapper transaction accepted at height 29232. Used 21 gas.
Waiting for inner transaction result...
Transaction failed.
Details: {
  "inner_tx": null,
  "info": "Error trying to apply a transaction: Transaction runner error: Failed running wasm with: RuntimeError: unreachable\n    at <unnamed> (<module>[795]:0x6c10c)\n    at <unnamed> (<module>[90]:0x1eff6)\n    at <unnamed> (<module>[84]:0x1ec6a)\n    at <unnamed> (<module>[16]:0x13688)\n    at <unnamed> (<module>[830]:0x6d560)",
  "log": "",
  "height": 29233,
  "hash": "1FA46FEE07EFB433CD453D53CAD1CCF62B1293175F2390A2678441E8760B9E76",
  "code": "WasmRuntimeError",
  "gas_used": "4031"
}
```

**Comment by Liver-23** [comment]
`namadac find-validator --tm-address=$(curl -s localhost:26657/status | jq -r .result.validator_info.address)`
Return the new consensus-key in `Consensus key: tpknam1`.

But both (old and new) are treated as working at the same time:
```
namadac change-consensus-key --validator liveraven --consensus-key liveraven-consensus-key --memo "<>" --signing-keys wallet
The consensus key is already being used.
```
```
namadac change-consensus-key --validator liveraven --consensus-key liveraven-consensus-key-1 --memo "<>" --signing-keys wallet
The consensus key is already being used.
* liveraven-consensus-key - old
* liveraven-consensus-key-1 - new
```

**Comment by brentstone** [comment]
Closing, let's continue discussion on #2663 if needed.
