### ISSUE TITLE
Buggy Output``Change-consensus-key`` reporting two keys are being used "for signing blocks" after creating a new consensus-key

### ISSUE THREAD

**Issue by spidey-169** [anoma/namada#2643]
Changed consensus key using this command.
```
namadac change-consensus-key --validator $ALIAS--memo $MEMO --signing-keys $WALLET
```
this created a new key ``spidey-consensus-key-1`` in addition to previous ``spidey-consensus-key``. My validator is currently signing using my original ``spidey-consensus-key`` key.

However when I check 
```
namadac change-consensus-key --validator $ALIAS--memo $MEMO --signing-keys $WALLET --consensus-key spidey-consensus-key
```
I get 
```
The consensus key is already being used.
```
And with the new key, WHICH IS NOT YET SIGNING
```
namadac change-consensus-key --validator $ALIAS--memo $MEMO --signing-keys $WALLET --consensus-key spidey-consensus-key-1
```
```
The consensus key is already being used.
```

I know at this time spidey-consensus-key is the only signing blocks, hence its confusing to shwo both consensus keys are being used "to sign blocks" . This was before my validator got jailed which is descriibed in https://github.com/anoma/namada/issues/2642

**Comment by brentstone** [comment]
Thanks. Collecting all issues related to consensus key change UX under one issue #2664, so I'll close this one now.
