### ISSUE TITLE
Calling validator-state for an epoch > 2

### ISSUE THREAD

**Issue by zenodeapp** [anoma/namada#2644]
Not a bug, so making this a blank issue.

Calling `namada client validator-state` for an epoch greater (and also equal?) than 2 is probably always unreliable if we think of the `threshold` since changes in the epochs before could change the outcome. Perhaps a different message could be given for when one queries such values. Like an extra warning added.

Though I understand it always has a certain degree of unreliability due to whether a validator is healthy or not.

Like WARN logs, this isn't high prio or shouldn't have any prio at all :)!

**Comment by brentstone** [comment]
I started thinking somewhat recently about making the `validator-state` command output more sophisticated messages to account for certain edge cases like this. I'd say it should be pretty low priority for now though, we have a lot on our plates at the moment. Let's keep the issue open though in case we want to revisit when the backlog of work clears up a bit.

**Comment by zenodeapp** [comment]
> I started thinking somewhat recently about making the `validator-state` command output more sophisticated messages to account for certain edge cases like this. I'd say it should be pretty low priority for now though, we have a lot on our plates at the moment. Let's keep the issue open though in case we want to revisit when the backlog of work clears up a bit.

Gotcha!

**Comment by zenodeapp** [comment]
To keep it all in one place: there is also a `validator-state` suggestion in #2645 for giving consensus-key change messages/updates.

But, as you've put it, in general the `validator-state` could indeed be upgraded to contain more useful info or sophisticated messages for more than just the aforementioned (edge) cases.

But an exploration for a different moment in time.

**Comment by brentstone** [comment]
I'm including some upgrades in #3031, but I don't think I am going to include this specific request in there.

It sounds like this issue asks for an extra message to the effect of `Warning: this is an epoch that is at least pipeline length epochs in the future, and the validator state returned could be changed before then.` But this requires some extra RPC calls that I'd rather not incorporate here. Furthermore, I think for those using Namada from the command line, such users should be knowledgeable enough about the protocol to know that no data that is >= pipeline length epochs is set in stone before then. This is one of the core parameters for how the protocol works.

I am open to hearing a counter-argument, especially if it is believed that this is very important for users, but I think I'll close this issue for now.

**Comment by zenodeapp** [comment]
> I'm including some upgrades in #3031, but I don't think I am going to include this specific request in there.
> 
> It sounds like this issue asks for an extra message to the effect of `Warning: this is an epoch that is at least pipeline length epochs in the future, and the validator state returned could be changed before then.` But this requires some extra RPC calls that I'd rather not incorporate here. Furthermore, I think for those using Namada from the command line, such users should be knowledgeable enough about the protocol to know that no data that is >= pipeline length epochs is set in stone before then. This is one of the core parameters for how the protocol works.
> 
> I am open to hearing a counter-argument, especially if it is believed that this is very important for users, but I think I'll close this issue for now.

Ah, cleaning up issues I see!

Yes, sounds good. Seems also too much of a hassle to get something this small implemented.

We as humans should know best how uncertain the future can be hehe.
