### ISSUE TITLE
Missing key data in the proposal object return by query-proposal CLI

### ISSUE THREAD

**Issue by phy-chain** [anoma/namada#2647]
`namada client query-proposal --proposal-id 16` for instance, this is a PGF funding, we expect to see the address(es) that might receive funding or being cut from it, how much they'd receive...

The same applies for the proposals modifying parameters for instance (is there a doc somewhere on how to format/prepare data for that kind of proposal ? I've been trying to figure that out, but I dont understand how to get the wasm to input, and/or how/what to build to get that wasm)

Generally speaking, I guess the data field should be made available to be displayed in a fully functionnal UI to vote on proposals. (not sure how to decode wasm in a webapp to expose what the code is changing though :thinking: )

**Comment by cwgoes** [comment]
cc @brentstone what do you think might make sense here?

**Comment by brentstone** [comment]
@cwgoes This looks like it was included in #2572
