### ISSUE TITLE
Better diagnostics

### ISSUE THREAD

**Issue by ekkis** [anoma/namada#2648]
if I create an account:
```bash
namada wallet gen --alias donor
```
and fund it, when I attempt to send funds from it via code, it fails with the output below

> response=Ok(Applied(TxResponse { inner_tx: Some(TxResult { gas_used: Gas { sub: 77268461 }, changed_keys: {Key { segments: [AddressSeg(Internal Multitoken: tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv), AddressSeg(Established: tnam1q87wtaqqtlwkw927gaff34hgda36huk0kgry692a), StringSeg("balance"), AddressSeg(Implicit: tnam1qpqqnuh6yh624nut0sx2py4zwk7u487yks74fsg5)] }, Key { segments: [AddressSeg(Internal Multitoken: tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv), AddressSeg(Established: tnam1q87wtaqqtlwkw927gaff34hgda36huk0kgry692a), StringSeg("balance"), AddressSeg(Implicit: tnam1qrqggncc4tfts9xwjkfrefwy54yxfw5a6cj0dsp5)] }}, vps_result: VpsResult { accepted_vps: {Internal Multitoken: tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv, Implicit: tnam1qrqggncc4tfts9xwjkfrefwy54yxfw5a6cj0dsp5}, rejected_vps: {Implicit: tnam1qpqqnuh6yh624nut0sx2py4zwk7u487yks74fsg5}, gas_used: VpsGas { max: Gas { sub: 39116268 }, rest: [Gas { sub: 0 }, Gas { sub: 0 }, Gas { sub: 29392 }, Gas { sub: 0 }, Gas { sub: 0 }, Gas { sub: 38313684 }, Gas { sub: 0 }, Gas { sub: 0 }] }, errors: [], invalid_sig: true }, initialized_accounts: [], ibc_events: {}, eth_bridge_events: {} }), info: "Check inner_tx for result.", log: "", height: BlockHeight(7193), hash: "E26D2CB76FBF193ED5D4F1A37DCC46E2B7F03D25B2366FADA7E62FA5BDE81D90", code: InvalidTx, gas_used: "7727" }))

after some effort, I've come to understand this happens because the "donor" account needs to _reveal_ its public key.  there is nothing in the above output that might lead me to that conclusion.  in fact, the only hint I get is that `invalid_sig: true`

could you guys enhance the output such that the error leads us developers to a resolution? something such as "needs reveal public key" or whatever

**Comment by sweatdust** [comment]
I have similar issues

**Comment by cwgoes** [comment]
Error messages have since been improved - thank you for the report!
