### ISSUE TITLE
 Parameters of the bonds_and_unbonds function must not be Option.

### ISSUE THREAD

**Issue by hkey0** [anoma/namada#2652]
I thought I could run this function (`bonds_and_unbonds`) by giving it a value of `None` but I got an error. The parameters of this function should not be `Option`.

**Comment by brentstone** [comment]
I see you also opened and then soon after closed #2651, so I'm assuming you figured out how to use this funcion properly and will close this. However, feel free to reach out if there is still a concern on your end.

**Comment by hkey0** [comment]
> I see you also opened and then soon after closed #2651, so I'm assuming you figured out how to use this funcion properly and will close this. However, feel free to reach out if there is still a concern on your end.

I created a PR because I thought I had made the adjustments I mentioned, but then I realized that this function was also related to other files and I closed the PR. 
Of course I understand how to use the function, but since these parameters are not `Optional`, I think that the `Option` in the Parameters should be removed in order not to make mistakes for future developers.

Have a nice day!
