### ISSUE TITLE
Possible bug in `vp_user`

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#2663]
There have been numerous reports of users failing to unjail their validators after, following a consensus key change, the validators did not properly update their CometBFT keys, resulting in jailing for downtime. The transactions fail largely due to VP rejection from another validator that would be demoted to the below-capacity validator set after the unjailed validator would be reinserted into consensus. Such issues have been reported in #2640 and #2642.

There may have been other reports of unjailing failures at the VP-level that do not involve a consensus key change, though it is unclear if the issue is the same as the above.

Lastly, a small bug in the `vp_user` has already been found and addressed in #2617.

**Comment by opsecx** [comment]
> There have been numerous reports of users failing to unjail their validators after, following a consensus key change, the validators did not properly update their CometBFT keys, resulting in jailing for downtime. The transactions fail largely due to VP rejection from another validator that would be demoted to the below-capacity validator set after the unjailed validator would be reinserted into consensus. Such issues have been reported in #2640 and #2642.
> 
> 
> 
> There may have been other reports of unjailing failures at the VP-level that do not involve a consensus key change, though it is unclear if the issue is the same as the above.
> 
> 
> 
> Lastly, a small bug in the `vp_user` has already been found and addressed in #2617.

Can confirm I have the unable to unjail issue here, I have not done consensus key change.

**Comment by opsecx** [comment]
Just leaving the observation here: I'm now in epoch 10 and jailed, never changed consensus keys, and still getting rejected by VPs error when trying to unjail (command format tested previously with no issues).

**Comment by gin** [comment]
**Bug report:**
Same issue as @opsecx but with v0.31.6
Unable to unjail.
No consensus key changed.

**Version:** v0.31.6
**Time:** at block height 43191

Command used:
```bash
namada client unjail-validator --validator tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl --node http://localhost:26657
```

Output:
```bash
Looking-up public key of tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl from the ledger...
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 4DF210EFC7585F94ADB9A5F9A7B9F8463B6964AD2735DEF73BB99D5F1CB5D224
Inner transaction hash: DD490B89C6BB6FDFBF267A7701BF86FC06937CC0852AABF7E55591E5C37CAE79
Wrapper transaction accepted at height 43191. Used 21 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q8vg3n4tfl9wcj5emckrjhgl62d88pmmpg9sljxr"
].
Changed keys: [
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q8vg3n4tfl9wcj5emckrjhgl62d88pmmpg9sljxr/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1q8vg3n4tfl9wcj5emckrjhgl62d88pmmpg9sljxr/state/lazy_map/data/000000000000Q",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl/state/lazy_map/data/000000000000E",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl/state/lazy_map/data/000000000000I",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl/state/lazy_map/data/000000000000Q",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl/state/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000000Q/data/#tnam1q8vg3n4tfl9wcj5emckrjhgl62d88pmmpg9sljxr",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_set_positions/lazy_map/data/000000000000Q/data/#tnam1qyagaxpgdaksew8smtxkl9gv8xcqcyngkv5k3ynl",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/below_capacity/lazy_map/data/000000000000Q/data/FVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVH356NVG/data/000000000003G",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000000Q/data/000000000000000000000000000000000000000000000ESQP800/data/000000000000M",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_sets/consensus/lazy_map/data/000000000000Q/data/00000000000000000000000000000000000000000015R503TUG0/data/0000000000000"
]

```

**Comment by gin** [comment]
I see. Thanks.

Report:
Still unable to unjail.
Block height 50257
Epoch 12

**Comment by blockhunters-dev** [comment]
also unable to unjail, running a script to try 100 consecutive unjail commands, maybe we get lucky

**Comment by brentstone** [comment]
There's been additions to #2617 recently that we believe solve this issue.
