### ISSUE TITLE
Withdraw Stake Bug: Error processing ``Withdraw`` even-though bonded stake is withdrawable as per current epoch

### ISSUE THREAD

**Issue by spidey-169** [anoma/namada#2669]
The following ``Withdraw`` command is giving an error. I have tried with the native node and RPC and get the same error. 

## 1. Withdraw transaction with the ERROR message**
```
namadac withdraw --validator $ALIAS --memo $MEMO --node tcp://namada-testnet-rpc.itrocket.net:80
```
```
There are no unbonded bonds ready to withdraw in the current epoch 10.
Error: 
   0: There are no unbonded bonds ready to withdraw in the current epoch 10.
   1: There are no unbonded bonds ready to withdraw in the current epoch 10.

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:235

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

## 2. However when I check the amount Withdrawable using ``bonds`` I see that at epoch 10, 1500 NAAN is Withdrawable

```
namadac bonds --owner $WALLET  --memo $MEMO --node tcp://namada-testnet-rpc.itrocket.net:80
```
```
Last committed epoch: 10
Delegations from tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd to tnam1q9ycyllty9lqx8tz5jxdc2l2k8a9qvtveu5faz50:
  Remaining active bond from epoch 5: Δ 2.000000
Active (slashed) bonds total: 2.000000
Bonds total: 2.000000

Unbonded delegations from tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd:
  Withdrawable from epoch 10 (active from 5): Δ 1500.000000
Unbonded total: 1500.000000
Withdrawable total: 1500.000000

Delegations from tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd to tnam1qyqs0erg46fnu5rlu34ek3nkkgv8fcmzku4m9uxa:
  Remaining active bond from epoch 5: Δ 8.000000
Active (slashed) bonds total: 8.000000
Bonds total: 8.000000

Withdrawable total: 0.000000

All bonds total active: 10.000000
All bonds total: 10.000000
All unbonds total active: 1500.000000
All unbonds total: 1500.000000
All unbonds total withdrawable: 1500.000000
```
@brentstone Tagging you here, as I think this is an important bug, which is also stopping a few other pilots and crews from claiming/withdrawing rewards or withdrawing stake to be used for transaction fees

**Comment by tzemanovic** [comment]
hi, the issue that you have to specify `--source tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd` for in the `withdraw` command, otherwise the client tries to withdraw the validator's self-bonds which you cannot access. We could probably improve the client UX to make this clearer

**Comment by spidey-169** [comment]
> hi, the issue that you have to specify `--source tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd` for in the `withdraw` command, otherwise the client tries to withdraw the validator's self-bonds which you cannot access. We could probably improve the client UX to make this clearer

yes, this worked. The CLI doesn't give the --source flag as a required input and I think it would be wise to make that a Required input. Currently the CLI gives this message fir source. 
```   
--source <source>
          Source address for withdrawing from delegations. For withdrawing from self-bonds, this arg does not need to be supplied.```

Hence the confusion, it sys it grabs this info by default, but I am guessing at the backend it doesn't. Hence worth fixing it at the back to either get it via defailt or in UI to require --source!
