### ISSUE TITLE
Does it make sense to be able to pass threshold=0 on init-account ?

### ISSUE THREAD

**Issue by phy-chain** [anoma/namada#2671]
```
namada client init-account      \
    --threshold 0   \
    --alias test-account-to-update2   \
    --signing-keys validatorade     \
    --memo tpknam1qpayc0rxtuulknrvygcwvlhehuw2tvmxhvhxmjm8s43hxj3vdxjlv62jzcq
```
This works without any warning. What would be the consequences of having a 0 threshold account ? Possibility of not signing tx ?

**Comment by sug0** [comment]
hm, this shouldn't make sense. the currently consequences seem to be that no signatures are required to validate an action within that account

**Comment by phy-chain** [comment]
Yep, I confirm. Tested this morning, and you can also lower it to 0 through update-account : 
`namadac update-account --address test-establied-0 --threshold 0 --signing-keys $KEY_ALIAS --memo $NAMADA_MEMO --node http://rpc.namada.validatorade.org`

Indeed, no signing required afterward, I can transfer funds with this account without signing

**Comment by phy-chain** [comment]
I have also fixed "init-validator" to enforce a threshold > 0
