### ISSUE TITLE
Vote error on wrong password

### ISSUE THREAD

**Issue by opsecx** [anoma/namada#2672]
When voting proposals, you will get a VP error if the following steps are taken:

1. Enter correct command for proposal vote
2. Enter wrong password
3. Wait for recurring password prompt
4. Enter correct password

Result: The transaction is sent but rejected by VP. This is a really strange bug but happens consistently here. It does not fail if you enter the password correctly the first time.

**Comment by opsecx** [comment]
Also wondering if this could give hints to the other vp errors atm

**Comment by opsecx** [comment]
Had another look at this. Interestingly, the error also produces when running with --dry-run-wrapper (not plain --dry-run).

**Comment by cwgoes** [comment]
Fixed by https://github.com/anoma/namada/pull/3681.
