### ISSUE TITLE
Remove MASP pin key

### ISSUE THREAD

**Issue by grarco** [anoma/namada#2675]
Currently, the masp optional pin key is used in an inconsistent way: when a user generates a payment address there’s the chance to pin this address, if this is the case than all transactions with this payment address as the receiver will produce a pin key with the hash of the address, otherwise no pin key will be produced. If no pin is requested when generating the address, then no pin key will be produced.

Also, since we produce the pin key in a deterministic way (hash of the payment address) I believe we end up rewriting the same key in storage.

**Comment by grarco** [comment]
In the end, after some talk we decided to remove the pin key and focus on developing a better implementation of the shielded sync process #2900.

cc: @Fraccaman, @batconjurer

**Comment by cwgoes** [comment]
In that case I'm going to close this issue.

**Comment by grarco** [comment]
Reopening as this has not been completed yet

**Comment by cwgoes** [comment]
I see, sorry, it wasn't clear to me what task needed to be completed. Updated the title to clarify.
