### ISSUE TITLE
Next breaking release

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2688]
The next breaking should contain ONLY:
- Everything in the non-breaking release queue, including modularization work
    - See https://github.com/anoma/namada/pull/2616
    - This should be in a separate release beforehand.

Projected for 0.32.X: 
- https://github.com/anoma/namada/pull/2628
- https://github.com/anoma/namada/pull/2601
- https://github.com/anoma/namada/pull/2599
- https://github.com/anoma/namada/pull/2604
- https://github.com/anoma/namada/pull/2617
- State migration code

**Comment by brentstone** [comment]
Wondering if we should also include at least #2617 too.

**Comment by cwgoes** [comment]
> Wondering if we should also include at least #2617 too.

We should include it soon, but we want to make this breaking release an automatic upgrade, and my understanding of #2617 is that an automatic upgrade will be somewhat tricky (e.g. we have to update all the current `vp_user`s). What do you think?

**Comment by adrianbrink** [comment]
Do we already have the migration code for all the PRs?

**Comment by tzemanovic** [comment]
added https://github.com/anoma/namada/pull/2604 that doesn't require migration

**Comment by tzemanovic** [comment]
> Do we already have the migration code for all the PRs?

we don't have any migration code afaik

**Comment by cwgoes** [comment]
https://github.com/anoma/namada/pull/2617 to be added if possible - @brentstone to investigate state migration options.
