### ISSUE TITLE
`namada_sdk::rpc::get_all_validators` always returns empty set

### ISSUE THREAD

**Issue by dadamu** [anoma/namada#2693]
`namada_sdk::rpc::get_all_validators` always returns empty set whenever epoch is set to a valid epoch number like 1 or 2.

```rust
let validators = namada_sdk::rpc::get_all_validators(&client, Epoch::from(1)).await?;
println!("{:?}", validators); // {}
```

**Comment by sug0** [comment]
this is not a bug, it's intentional behavior. we prune validator sets after a certain number of epochs

https://github.com/anoma/namada/pull/1944
