### ISSUE TITLE
Feedback for “Shielded Transfers”

### ISSUE THREAD

**Issue by ekkis** [anoma/namada#2694]
when I do `namadac balance --owner=deposits` (a payment address I created), I get the following error:

> Payment address znam1qq93rs3tyuk0qdx5gwrwdemkw2quunpsfr5782lvjy0kh5un882dh27vh80wmrv528xj7scuyggxj has not yet been consumed.

what does that mean and what do I do about it? 

I sent tokens to that address.  furthermore, that address belongs to a shielded keypair where if I do `namadac balance --owner=customer` I see a balance of 5 NAM (pulling a balance takes half of forever, btw -- 4m11s)

**Comment by cwgoes** [comment]
The balance command has since been reworked.
