### ISSUE TITLE
RPC HTTP error and URL scheme is not allowed

### ISSUE THREAD

**Issue by isunfox** [anoma/namada#2704]
Thank you for the bug report. Please provide any information that may be relevant to the issue you're experiencing.
Failed to query node status with error: 
   0: HTTP error
   1: builder error for url (tcp://127.0.0.1:36657): URL scheme is not allowed

Location:
   /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Error: 
   0: Querying error: Error in the query: Failed to query node status with error: 
         0: HTTP error
         1: builder error for url (tcp://127.0.0.1:36657): URL scheme is not allowed

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.
   1: Error in the query: Failed to query node status with error: 
         0: HTTP error
         1: builder error for url (tcp://127.0.0.1:36657): URL scheme is not allowed

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:528

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

![image](https://github.com/anoma/namada/assets/30688978/21f3ec4f-7195-44c9-9aa0-fe9c7ffda4f5)

**Comment by brentstone** [comment]
Closing as this is a duplicate fo #2702.
