### ISSUE TITLE
Command namada client validator-state shows wrong output

### ISSUE THREAD

**Issue by Fible1** [anoma/namada#2706]
Hi, if I run this command:  

namada client validator-state --validator wallet --node http://176.9.7.136:26657 I get this output:

"Validator tnam1qr495c9zr52lfc8vedu2lwutffhk6a8p5qkvvrq9 is either not a validator, or an epoch before the current epoch has been queried (and the validator state information is no longer stored)"

This however is not correct a the explorers I am aware of show me as an active validator, and I am also able to vote see:

https://namada-explorer.stakepool.dev.br/validators/57B060D8F035A23DE62BD7A15141F47E8EC2BBB8

unfortunately I did not save the outputs, but I voted on 20ish proposals today successfuly.

Thank you.

**Comment by brentstone** [comment]
It is possible you are using the wrong address as your validator, do you have another address associated with your account? Can you perhaps provide the output of `namada wallet list` here?

**Comment by Fible1** [comment]
Here you go:

root@Ubuntu-2204-jammy-amd64-base:~# n
namada wallet list
Known transparent keys:
  Alias "fible1-consensus-key" (encrypted):
    Public key hash: 35F60EF37052DC459EDDE458152BA431DF0785D3
    Public key: tpknam1qz6w9ksk48yx8yntzslhpqcu6l6e5txtr4knk84magmdha9cdkrp2zgrus9
  Alias "wallet" (encrypted):
    Public key hash: EA5A60A21D15F4E0ECCB78AFBB8B4A6F6D74E1A0
    Public key: tpknam1qpqud8rn0599njgymc748d82zaacjhwu2gt55vyrgm50z0a5rw4pkc0tyuz
  Alias "fible1-protocol-key" (encrypted):
    Public key hash: A2E32ED346D84F9747A8B27F8CA6A489C395097C
    Public key: tpknam1qpztevsgad43rkecvr0gaessfr7k4rnq005u578ataxxq0ahmdmfjvy3q0g
  Alias "fible1-eth-cold-key" (encrypted):
    Public key hash: F86712F17C13B90A11F89B5D6C90C177CD661DB8
    Public key: tpknam1qypmsd4t6jpz9r662d0s706tm5cuukrwnul4a5cs5ynfdnqn5zsarygyz3mn0
  Alias "fible1-eth-hot-key" (encrypted):
    Public key hash: 96AB44AC32291F063799E3D632C12C735B85C041
    Public key: tpknam1qypqdj89amcpgrt3wgg4nys6uan3r9qgr03cau8dpgx4lv36ch4ulfccu5xk2
Known transparent addresses:
  "fible1": Established: tnam1q9gx7anyzey3f4lhl95eav48dxt4jwqvjg9yvec3
  "fible1-consensus-key": Implicit: tnam1qq6lvrhnwpfdc3v7mhj9s9ft5sca7pu96vw795yw
  "fible1-eth-cold-key": Implicit: tnam1qruxwyh30sfmjzs3lzd46mysc9mu6esahqt38kcf
  "fible1-eth-hot-key": Implicit: tnam1qzt2k39vxg537p3hn83avvkp93e4hpwqgyanr04z
  "fible1-protocol-key": Implicit: tnam1qz3wxtkngmvyl9684ze8lr9x5jyu89gf0sfqfash
  "naan": Established: tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee
  "wallet": Implicit: tnam1qr495c9zr52lfc8vedu2lwutffhk6a8p5qkvvrq9

**Comment by brentstone** [comment]
Your validator address is `tnam1q9gx7anyzey3f4lhl95eav48dxt4jwqvjg9yvec3`:
```
target/release/namadac validator-state --validator tnam1q9gx7anyzey3f4lhl95eav48dxt4jwqvjg9yvec3 --node http://159.203.161.252:26657
Validator tnam1q9gx7anyzey3f4lhl95eav48dxt4jwqvjg9yvec3 is in the consensus set
```
Looks like `wallet` is the implicit account address that was used to create your validator account `fible1`.

**Comment by brentstone** [comment]
@Fible1 were you a genesis validator?

**Comment by Fible1** [comment]
Okay, yes please close it. Thank you, it was my mistake. Was half asleep when I sent this :).
 
@brentstone no.
