### ISSUE TITLE
Namada client [vote-proposal] Rejected by VPs when Voting 

### ISSUE THREAD

**Issue by papadritta** [anoma/namada#2709]
#### Issue Description
When attempting to vote on a proposal using the `namada client vote-proposal` command, the transaction is added to the mempool but subsequently rejected by the VPs. This issue occurred while voting on proposal ID 127.

#### Command Executed
```
namada client vote-proposal --proposal-id 127 --vote yay --address tnam1qzeenzqnngaldqtj2texua4td3x8tdx9rsknvknv --signing-keys papa --memo tpknam1qpgff9uw9km6f34957xptf3v86sack0p894gfl8lkfr77a3rmqn96lwfl8k --node http://localhost:26657
```
#### Output
```
Transaction added to mempool.
Wrapper transaction hash: 17FDC6D7F80C260A84B01C7483090C7976838BEE4286E369F738FFB92150B33E
Inner transaction hash: 62C8AFA331F7D91D5839597FBAA80F4245B571471241823C4A163DC1F9DB9BBE
Wrapper transaction accepted at height 48484. Used 23 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6"
].
Changed keys: [
  "#tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6/proposal/127/vote/#tnam1q8d5mhh96qm3zaqt735znann0nucqw9dvyc4j82f/#tnam1qzeenzqnngaldqtj2texua4td3x8tdx9rsknvknv"
]
```

**Comment by JuliaMoon1** [comment]
## Description:

I've encountered an inconsistency in how transactions are handled for votes that start before `Epoch 20`. Specifically, I attempted two transactions with the same command as previous votes, but observed different outcomes based on the epoch in which the votes started.

## Details:

Transaction `218` (start epoch 18, end epoch 22) was rejected.
Transaction` 221 ` (start epoch 20, end epoch 22) was successful.
This issue seems to affect any vote that started before epoch 20, even if they remain active for additional epochs, as seen with transaction `218.`

## Commands and Outputs:

#### Transaction 218 Rejection:
```
namada client vote-proposal --proposal-id 218 --vote yay --address laliola --signing-keys laliola --memo tpknam1qpxleh3wtgyxdlm6e6ux6m5mfafad6l7jae42r6xvf0yaemerltcjms5d8l --node http://localhost:26657
```
```
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: A9CC23A28ABE496A05A579395D03D5A6F132A390E67064685F555501B1D2858C
Inner transaction hash: 7FF65CDC67A8581FC34B89205533CE413FFF94A75125F6DC537B5F0555BCD2E6
Wrapper transaction accepted at height 78132. Used 24 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6"
].
Changed keys: [
  "#tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6/proposal/218/vote/#tnam1q8090mwcccefg07ghh74falxx8zmdad725kd6mc8/#tnam1qr759dcuw699ju7h9s6t93tnsj5aphp9yvxryz87",
  "#tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6/proposal/218/vote/#tnam1q89murp58fsnady469dj9r62ttrd3v6jnvhtzwhn/#tnam1qr759dcuw699ju7h9s6t93tnsj5aphp9yvxryz87",
  "#tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6/proposal/218/vote/#tnam1qyqs3ywln6e27ytnp9952wlpmj0dc2clwq6ka60u/#tnam1qr759dcuw699ju7h9s6t93tnsj5aphp9yvxryz87"
]
```
#### Transaction 221 Success:
```
namada client vote-proposal --proposal-id 221 --vote yay --address laliola --signing-keys laliola --memo tpknam1qpxleh3wtgyxdlm6e6ux6m5mfafad6l7jae42r6xvf0yaemerltcjms5d8l --node http://localhost:26657
```
```
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: B21136E80736188393CA616A27AC2EA68BC5BB380E0BC77531BE5534458FC99B
Inner transaction hash: 071F8C44B5C179718B902825A3C0A237673929A051A67064E84701D30ADB2682
Wrapper transaction accepted at height 78139. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 78140. Used 8122 gas.
```

## Question:

Is this behavior expected, or is it a potential issue with transactions that start before a specific epoch? It would be helpful to understand if this scenario affects any kind of vote that began before `epoch 20`, similar to transaction `218`.

**Comment by papadritta** [comment]
@Fraccaman @brentstone Could you check and clarify it, please? I still have the same issue with Voting and can't vote on valid proposal.

**Comment by JuliaMoon1** [comment]
#### Successful Votes in Epoch 20:
>I successfully voted on the following proposals, which were all scheduled within epochs 20 to 22, with exceptions noted:

```
Proposals 219 to 236 (inclusive), scheduled for epochs 20 to 22.
Proposals 237 and 238, scheduled for epochs 20 to 24.
Proposals 239, and 240, scheduled for epochs 20 to 22 and 20 to 24 respectively.
Additional successful votes on proposals 242 to 245, all scheduled for epochs 20 to 22.
```
#### Rejected Votes in Epoch 20:
>The following proposals were rejected by VPs, despite being active and seemingly within a valid voting period:

```
Proposal 192 (epochs 18-20)
Proposal 197 (epochs 16-20)
Proposals 206 to 213 (inclusive), all scheduled for epochs 18 to 20.
Proposal 214 (epochs 18-22)
Proposals 215 to 217 (inclusive), all scheduled for epochs 18 to 20.
Proposal 218 (epochs 18-22)
```

**Comment by opsecx** [comment]
> #### Successful Votes in Epoch 20:
> 
> >I successfully voted on the following proposals, which were all scheduled within epochs 20 to 22, with exceptions noted:
> 
> 
> 
> ```
> 
> Proposals 219 to 236 (inclusive), scheduled for epochs 20 to 22.
> 
> Proposals 237 and 238, scheduled for epochs 20 to 24.
> 
> Proposals 239, and 240, scheduled for epochs 20 to 22 and 20 to 24 respectively.
> 
> Additional successful votes on proposals 242 to 245, all scheduled for epochs 20 to 22.
> 
> ```
> 
> #### Rejected Votes in Epoch 20:
> 
> >The following proposals were rejected by VPs, despite being active and seemingly within a valid voting period:
> 
> 
> 
> ```
> 
> Proposal 192 (epochs 18-20)
> 
> Proposal 197 (epochs 16-20)
> 
> Proposals 206 to 213 (inclusive), all scheduled for epochs 18 to 20.
> 
> Proposal 214 (epochs 18-22)
> 
> Proposals 215 to 217 (inclusive), all scheduled for epochs 18 to 20.
> 
> Proposal 218 (epochs 18-22)
> 
> ```

I think you need voting power in the epoch proposal goes active? not 100% but that would explain the behavior

**Comment by JuliaMoon1** [comment]
> > #### Successful Votes in Epoch 20:
> > > I successfully voted on the following proposals, which were all scheduled within epochs 20 to 22, with exceptions noted:
> > 
> > 
> > ```
> > 
> > Proposals 219 to 236 (inclusive), scheduled for epochs 20 to 22.
> > 
> > Proposals 237 and 238, scheduled for epochs 20 to 24.
> > 
> > Proposals 239, and 240, scheduled for epochs 20 to 22 and 20 to 24 respectively.
> > 
> > Additional successful votes on proposals 242 to 245, all scheduled for epochs 20 to 22.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Rejected Votes in Epoch 20:
> > > The following proposals were rejected by VPs, despite being active and seemingly within a valid voting period:
> > 
> > 
> > ```
> > 
> > Proposal 192 (epochs 18-20)
> > 
> > Proposal 197 (epochs 16-20)
> > 
> > Proposals 206 to 213 (inclusive), all scheduled for epochs 18 to 20.
> > 
> > Proposal 214 (epochs 18-22)
> > 
> > Proposals 215 to 217 (inclusive), all scheduled for epochs 18 to 20.
> > 
> > Proposal 218 (epochs 18-22)
> > ```
> 
> I think you need voting power in the epoch proposal goes active? not 100% but that would explain the behavior

Yeah, it could be true or bug, let's wait the answer from the team.

**Comment by papadritta** [comment]
Just to clarify. I guess, the issue when attempting to vote on proposals using the `namada client vote-proposal` command might be related to voting power, particularly in the context of validators' status. I proposed that having a validator in a jailed state could result in losing voting power for that epoch, which, in turn, would prevent successful proposal voting.

Given this, I have a couple of questions:

1. Is it indeed the case that a validator being jailed (even though they have stake bonded) results in the loss of voting power for the duration of the jail period? 

2. would re-staking or bonding at least to one active validator associated with my account (not in jail and has sufficient voting power) be a correct solution to regain the ability to vote on proposals?
