### ISSUE TITLE
Optimizing MASP proofing

### ISSUE THREAD

**Issue by zenodeapp** [anoma/namada#2711]
Hi! 

First off, this `shielded-sync` approach is really a step forward into the right direction! Great job! Before I dive into potential optimizations, I'd like to address a current (small) problem in v0.31.6:

_At the moment, I have to re-run the command to let a shielded transfer get reflected in my balance. This possibly due to having an outdated asset list the moment we run the balance query. Perhaps re-running this whenever the asset list is outdated could help. Or, instead give the user feedback that the current state isn't up-to-speed thus the balance for the queried wallet could be outdated._

---

Now for optimizing MASP, I had a couple ideas:

**Simple, yet still not a fix for the >= O(n) MASP algorithm problem**
1. Could the `shielded-sync` be a separate process that runs alongside the ledger to keep up with the blockchain and resync whenever a new block (or arbitrary interval of blocks) gets added? This doesn't necessarily speed up MASP but it would make it a separate process running concurrently. I could imagine this may be a potential pitfall for state inconsistencies though.

**More complex ideas, but requires changes in infrastructure**
I'm not aware of all the ins-and-outs of the MASP algorithm, so what I'm about to say may make it less secure, sound ignorant or might theoretically even not be possible, but:

2. Is it an idea to instead start the scan _at the end of the chain_ and have every block point to multiple other blocks in the past. They then all, concurrently, traverse the chain back in time until they get far enough back (or all the way back) to get to a point where an agreement for the asset list can be made? Perhaps it will be necessary to traverse back up again to the current block and calculate the final state for the asset list in the present (due to else becoming _indeterminate_).

    This could relief it from its (_at minimum?_) O(n) time complexity by allowing the algorithm to be a multithreaded activity (if it's actually possible to let this be calculated in multiple threads). Also, the `stepInterval` to how far back a block should point could be treated as a parameter for how secure the algorithm is.
    
    _This idea could somewhat be thought of as a checkpoint mechanism. Also, reason for starting this at the end of the chain is due to not being able to predict and point to future blocks._

3. If 2. makes the cryptography less secure, there's also some randomization that could get implemented. What if the block selection used for the creation of this asset list is randomized at every new block (or whatever interval)? That way it's less straight-forward to predict which blocks it chooses for the calculation of the new asset list. Though to make this deterministic it would require global tracking of the `seed` used for randomization on every block.

4. A final idea is to fuse the current method with the above. This would probably be hard to attain. But it might give way to getting the best of both worlds. Let's say you utilize the tree-like traversing method from above for 80% of the chain. The last 20% would then be calculated by scanning every block linearly towards the current block. This would probably be tricky if I think of all the consensus issues this could give rise to, but it could potentially improve the _time complexity_.

These suggestions kind of point to finding the sweet spot between either _saving up on time complexity_ or improving the _granular aspect of the cryptography_.

To wrap it up: security or cryptography isn't exactly my strong suit, so apologies if these three latter points sound a bit ignorant to the problem at hand!

ZEN

**Comment by zenodeapp** [comment]
I seriously am bad with categorizing stuff. This is not a bug, but Enhancement/Improvement ofcourse.

(though the first point could be seen as a potential bug)

**Comment by zenodeapp** [comment]
Updated the comment above; added a 5th contemplation.

**Comment by zenodeapp** [comment]
Sadly, I'm in no way capable of writing a logic as complex as this in Rust as to see how it would play out.

Though, believe this thought process could actually help. Perhaps someone with the skills will see this and take a shot at trying to implement this.

**Comment by zenodeapp** [comment]
**UPDATE:** revised everything and also added a 4th contemplation.

**Comment by zenodeapp** [comment]
Another small side note to clarify 4: this idea of implementing a tree-like inverted structure fused with the current linear approach kinda makes me think of state-syncing.

**Comment by brentstone** [comment]
Will close this now, but tracking in #2900.
