### ISSUE TITLE
err while init-proposal to Ibc

### ISSUE THREAD

**Issue by msobh13** [anoma/namada#2714]
I tried to  init-proposal to Ibc  but i got this err .

namada version 0.31.6
hermes hermes 1.7.4+1ede457f

command used 
`namadac init-proposal --pgf-funding --data-path fundIBC.json --node http://localhost:19902 --memo tpknam1qr37yj7d9al5yerzn68kn7gtttfh25fqk45wwwvmt8snwgp5zwrzvjfujne`

err is 

`Transaction added to mempool.
Wrapper transaction hash: 09B47B38D229705AC30E6F2FFAC112F87E33866166440F40D298B9A4628C3E45
Inner transaction hash: 7FE5FCCDCD4DF4ECD0E58AC4D3BE5227B18A9B2CB9978E17A10EC0A0C2F71734
Wrapper transaction accepted at height 54790. Used 34 gas.
Waiting for inner transaction result...
Transaction failed.
Details: {
  "inner_tx": null,
  "info": "Error trying to apply a transaction: Transaction runner error: Failed running wasm with: RuntimeError: unreachable\n    at <unnamed> (<module>[639]:0x5962d)\n    at <unnamed> (<module>[60]:0x5155)\n    at <unnamed> (<module>[95]:0x7d8c)\n    at <unnamed> (<module>[608]:0x562d7)\n    at <unnamed> (<module>[745]:0x5b05c)",
  "log": "",
  "height": 54791,
  "hash": "7FE5FCCDCD4DF4ECD0E58AC4D3BE5227B18A9B2CB9978E17A10EC0A0C2F71734",
  "code": "WasmRuntimeError",
  "gas_used": "3381"
}
`

tried with multiple chains same issue .
normal and shielded Ibc tx works fine using same channel ID

**Comment by Fraccaman** [comment]
could you shaer the content of `fundIBC.json` ?

**Comment by msobh13** [comment]
@Fraccaman bug verified ?

**Comment by msobh13** [comment]
same issue with 0.31.9 . hmm may be i am doing somthing wrong ?

**Comment by Michel-Leidson** [comment]
It seems to me that the problem is related to the structure of the JSON.

I just copied your JSON and made a small change, see that it worked.

**Hash: 18E5A016DB15D8C9F079A43DF2BBCE1BB705A3142CCDBF7BBC31F7E073C9316E**

Example:
{
  "proposal": {
    "id": 378,
    "content": {
      "title": "Prop-Steward-013",
      "authors": "StakePool",
      "discussions-to": "forum.namada.net/t/namada-proposal/XXX",
      "created": "2024-03-19T18:00:00Z",
      "license": "MIT",
      "abstract": "StewardProp",
      "motivation": "foobaar",
      "details": "Just Some details about this ",
      "requires": "foobar"
    },
    "author": "tnam1q8q0g5j4k9ume9lapusf7wz9z3n7t8g4mszfsmtq",
    "voting_start_epoch": 46,
    "voting_end_epoch": 48,
    "grace_epoch": 50
  },
  "data": {
    "action": "add",
    "continuous": [
      {
        "Ibc": {
          "amount": "1337",
          "target": "tnam1q8q0g5j4k9ume9lapusf7wz9z3n7t8g4mszfsmtq",
          "port_id": "transfer",
          "channel_id": "channel-355"
        }
      }
    ],
    "retro": [
      {
        "Ibc": {
          "amount": "1337",
          "target": "tnam1q8q0g5j4k9ume9lapusf7wz9z3n7t8g4mszfsmtq",
          "port_id": "transfer",
          "channel_id": "channel-355"
        }
      }
    ]
  }
}

**Comment by msobh13** [comment]
perfecto . Thanks . I will close this now
