### ISSUE TITLE
Buggy``Show-transfers`` Query, doesn't yield anything, cli hangs and sometimes freezes the node

### ISSUE THREAD

**Issue by spidey-169** [anoma/namada#2717]
The ``show-transfer`` query parameter, which is very useful tool to get the list of confirmed transfers from a wallet, is not yielding anything but simply freezes the node when executed.

The commands I have tried
```
namadac show-transfers --node http://127.0.0.1:26657 --owner $NEW_WALLET --token tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee

```

```
namadac show-transfers --node <RPC> --owner $NEW_WALLET --token tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee

```
<img width="1171" alt="Screen Shot 2024-02-26 at 1 55 52 AM" src="https://github.com/anoma/namada/assets/83369878/3c6156bd-42ff-4264-af60-50458c244abf">

For this testing, I created a new wallet and just had 1 transaction using it.However, even with that the query freezes and doesn't yield anything. Bringing it forward so it can be fixed as this is a very useful query tool to have.! @brentstone Tagging you here. Thanks

**Comment by spidey-169** [comment]
More details on this issue. Looks like the client goes into an infinite loop for ``Converting current asset type to latest asset type``. Note that this command was executed for a new wallet with a single transaction.

<img width="526" alt="Screen Shot 2024-02-26 at 5 50 47 PM" src="https://github.com/anoma/namada/assets/83369878/698efd1d-dfae-4726-ac6e-be0f13641a0a">

**Comment by brentstone** [comment]
@Fraccaman @grarco ?

**Comment by spidey-169** [comment]
> @Fraccaman @grarco ?

Adding to the debug studies, for some wallets instead of going into an infinite ``converting current asset type to latest asset type`` if gives ``application panic crashes error`` 

![debug_op_1](https://github.com/anoma/namada/assets/83369878/5c89a72a-daf7-47d6-98c6-1a0aeb58b170)
![debug_2](https://github.com/anoma/namada/assets/83369878/7b164597-c838-40dc-815a-aed3ef65c388)

while for others, it still goes into an "infinte" converting loop. Tested on two different nodes and giving different results

**Comment by spidey-169** [comment]
When checking the balance, the screen shows balance and for some reason, CLI is trying to query the balance over a number of IBC channels? Could this be why its going into an infinite loop for Changing current asset type or just Application Panic crashing?

![debug_3](https://github.com/anoma/namada/assets/83369878/b0f89753-af37-4488-9c6a-482f43e58517)

**Comment by grarco** [comment]
This is related to #2381 since internally `show-transfers` calls `query_tx_deltas`

**Comment by spidey-169** [comment]
> This is related to #2381 since internally `show-transfers` calls `query_tx_deltas`

Great. Thanks for confirming the bug. Looks like this is already being looked into!

**Comment by cwgoes** [comment]
Thanks for your report! We're actually going to remove this command, and replace it later with a faster option using an indexer.
