### ISSUE TITLE
Buggy ``query-proposal-result`` freezes and hangs for certain proposals even thouhg ``query-proposal-votes`` yields all the votes for that proposal

### ISSUE THREAD

**Issue by spidey-169** [anoma/namada#2718]
The ``query-proposal-result`` is buggy and unable to query the result for some proposals while is works correctly for some other. I cam across this while trying to query proposal outcome and votes for my own explorer project and not having the clie correctly query results is a major hassle as API call to proposal and governance become extremely difficult

Current epoch is 17. I am trying to query result for two proposals, one expired in epoch 16 using this command
Here is the proposal details

<img width="1397" alt="Screen Shot 2024-02-26 at 2 14 32 AM" src="https://github.com/anoma/namada/assets/83369878/aaf83496-eeca-401c-8ddb-2d7a4e6f9dad">

```
namadac query-proposal-result --proposal-id 180 --node $NODE 
```
The cli simply hangs and doesn't yield anything. 
<img width="1061" alt="Screen Shot 2024-02-26 at 2 07 20 AM" src="https://github.com/anoma/namada/assets/83369878/ce6c762c-e888-4eae-be68-e7a1a902226c">

Note however, the ``query-proposal-votes`` for 180 p-id yields a finite number of vote, so I know that the query-proposal-result should be giving a response. **Thus this proposal voting query is an edge case bug** for sure since when I query proposal 120, which expired in epoch 12, the query yields a valid response. 

<img width="1162" alt="Screen Shot 2024-02-26 at 2 08 56 AM" src="https://github.com/anoma/namada/assets/83369878/b1be2e4f-2f88-43c8-99c4-73464c010d63">

I have tested voting for all proposal types and there is not specifie trend or order. Hence I am afraid it might be a bug under the hold where either the query is going into an infinite loop or not gettng valid response for votes. Either way this should be made bug free as its the prime API call for future governance infra for namada

**Comment by spidey-169** [comment]
@brentstone Tagging you here, I continue to see this. Can you confirm, or comment. I will also see if I can look into the code and search for this edge case and if possible submit PR to fix this :))

**Comment by Fraccaman** [comment]
there is nothing buggy here. The command is just slow as it scales with the number votes: more votes, more queries to rocksb.
