### ISSUE TITLE
Can't bond from validator

### ISSUE THREAD

**Issue by opsecx** [anoma/namada#2723]
Can't make a regular bond with validator as source and other validator as target. Can make self-bonds. Getting this error:

Waiting for inner transaction result...
Transaction failed.
Details: {
  "inner_tx": null,
  "info": "Error trying to apply a transaction: Transaction runner error: Failed running wasm with: RuntimeError: unreachable\n    at <unnamed> (<module>[854]:0x74567)\n    at <unnamed> (<module>[47]:0x1b87e)\n    at <unnamed> (<module>[40]:0x1b4c6)\n    at <unnamed> (<module>[20]:0x15d28)\n    at <unnamed> (<module>[891]:0x75a71)",
  "log": "",
  "height": 72088,
  "hash": "574D98F6F455CFAFD5B3E371A95A1020260999A7D0F38F5245484D6DBEB00048",
  "code": "WasmRuntimeError",
  "gas_used": "4222"

**Comment by brentstone** [comment]
This is explicitly forbidden - validator accounts can only bond to themselves.

**Comment by brentstone** [comment]
Could provide a client-side check to return a more descriptive error though.

**Comment by opsecx** [comment]
Feel free to close/leave open as appropriate

**Comment by brentstone** [comment]
A client check will be added in #2748.
