### ISSUE TITLE
``Disposable gas payer`` feature Error for IBC/Native transfers and giving "fee unshielding:Missing unshielding transaction"

### ISSUE THREAD

**Issue by spidey-169** [anoma/namada#2733]
Detail: 

I am trying to execute transfer using the ``disposable gas payer`` feature to hide my account used to pay gas-fees.  If I invoke the ``--disposable gas payer`` flag, the transaction fails in two different ways while the same transaction succeeds without the flag. I have tried transferring bridge IBC/osmo and naan and see the same issue in both.  This flag is quite important for maintaining privacy of the users if they wish to hide who is paying the gas, and hence its an important Bug/Protocol Improvement as this otherwise it removes certain privacy component of the transfers as far as hiding gas-payer identity is concerned. 

Steps:
1) Executing a transfer of naan from WALLET to WALLET_2 (Balance in WALLET is 1500 naan
```
namada client transfer --source $WALLET --target $WALLET_2 --token naan  --amount 2  --memo $MEMO --node $NODE  --signing-keys $WALLET --disposable-gas-payer --gas-spending-key $WALLET
```

<img width="1176" alt="Screen Shot 2024-02-27 at 2 03 24 AM" src="https://github.com/anoma/namada/assets/83369878/89373935-c3ce-4334-8bbf-f722868dec70">

```
namada client transfer --source $WALLET --target $WALLET_2 --token naan  --amount 2  --memo $MEMO--node $NODE --signing-keys $WALLET --disposable-gas-payer --gas-spending-key $WALLET
Created disposable keypair with alias disposable_1
Error: 
   0: Error in fee unshielding: Missing unshielding transaction
   1: Error in fee unshielding: Missing unshielding transaction

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:64

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it
```
 I have sufficient naan to cover txn fees in $WALLET
<img width="806" alt="Screen Shot 2024-02-27 at 1 55 39 AM" src="https://github.com/anoma/namada/assets/83369878/f5961e98-c8ca-4e0c-8ec5-ee14b835bcbf">

I have also confirmed I have sufficient fee in the SHIELDED accounts associated with the WALLET (i.e both transparent and shielded balance are good)

<img width="1008" alt="Screen Shot 2024-02-27 at 2 40 50 AM" src="https://github.com/anoma/namada/assets/83369878/be2ddd84-3828-4a2c-a176-8890a1df6230">

The same transfer WITHOUT ``disposable-gas-payer`` flag is SUCCESSFUL

``` 
namada client transfer --source $WALLET --target $WALLET_2 --token naan  --amount 2  --memo $CREW_PUBLIC_KEY --node $NODE --signing-keys $WALLET                                                          
Transaction added to mempool.
Wrapper transaction hash: 9501DB424F7E6932618DC8DF9B0B973F801F240416AF20061FB79387DDC05063
Inner transaction hash: 9A9EAD04989824730B1F8616F2BE80B545DA6396A1D62D2413FEE4DDE416CE5F
Wrapper transaction accepted at height 78049. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 78050. Used 7742 gas.
```

<img width="1176" alt="Screen Shot 2024-02-27 at 2 18 25 AM" src="https://github.com/anoma/namada/assets/83369878/56026710-ad2d-4550-a40f-4cf7022869f9">

Using --force flag, for executing the transfer, gives an " Insufficient transparent balance to pay " ERROR.

```
namada client transfer --source $WALLET --target $WALLET_2 --token naan  --amount 7  --memo $MEMO --node $NODE  --signing-keys $WALLET --disposable-gas-payer --gas-spending-key $WALLET
```
I get the following ERROR, that "nsufficient transparent balance to pay fees"
```
Submitting a tx to reveal the public key for address tnam1qr7t3nsexdp3gpnxnacwvgq58yu99w456clwzxsd...
Created disposable keypair with alias disposable_1
Error: 
   0: Encountered error while broadcasting transaction: 
   0:    0: server error: {"code":12,"data":"","log":"Mempool validation failed: Error trying to apply a transaction: Error while processing transaction's fees: Insufficient transparent balance to pay fees","hash":"F7205335EDA25A4C225BA2D4189581D2F9B88A0AEBA663DC681FBCD6577084BA"}

   0: Location:
   0:    /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

   0: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
   0: Run with RUST_BACKTRACE=full to include source snippets.
   1: Encountered error while broadcasting transaction: 
   1:    0: server error: {"code":12,"data":"","log":"Mempool validation failed: Error trying to apply a transaction: Error while processing transaction's fees: Insufficient transparent balance to pay fees","hash":"F7205335EDA25A4C225BA2D4189581D2F9B88A0AEBA663DC681FBCD6577084BA"}

   1: Location:
   1:    /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

   1: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
   1: Run with RUST_BACKTRACE=full to include source snippets.

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:64
```
<img width="1153" alt="Screen Shot 2024-02-27 at 1 54 44 AM" src="https://github.com/anoma/namada/assets/83369878/658d8808-3d2a-410c-be6c-6378539298ba">

If I use --force flag, its gives a Mempool validator failed error, which might give more insight as to why its failing as its saying that the transparent balances are insufficient to pay. Howwver I have ensured that the Balane in my wallet is sufficient.

2) I see the same error while transfering IBC assets
<img width="1179" alt="Screen Shot 2024-02-27 at 2 09 37 AM" src="https://github.com/anoma/namada/assets/83369878/5bbb8abd-d47a-4bd8-8461-45443c762171">

Once again, the same transfer is successful without the ``disposable-gas-transfer`` flag
<img width="1173" alt="Screen Shot 2024-02-27 at 2 10 40 AM" src="https://github.com/anoma/namada/assets/83369878/16078b16-520d-4a18-82e3-7a2f8f13f7d0">

3) Same error when transferring shielded assets 

```
namada client transfer --source $WALLET_SHIELDED --target $WALLET --token naan  --amount 2  --memo $CREW_PUBLIC_KEY --node $NODE --signing-keys $WALLET --disposable-gas-payer --gas-spending-key $WALLET
Created disposable keypair with alias disposable_1
Error: 
   0: Error in fee unshielding: Missing unshielding transaction
   1: Error in fee unshielding: Missing unshielding transaction

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:64

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
```

<img width="1171" alt="Screen Shot 2024-02-27 at 2 22 46 AM" src="https://github.com/anoma/namada/assets/83369878/61f74f6e-855c-4ba1-b0ba-e6240190b5c7">

When removing the ``--disposable-gas-payer`` it is successful

```
namada client transfer --source $WALLET_SHIELDED --target $WALLET --token naan  --amount 2  --memo $CREW_PUBLIC_KEY --node $NODE --signing-keys $WALLET 


converting current asset type to latest asset type...
Transaction added to mempool.
Wrapper transaction hash: E17DEE0CC3F5A73EF7F609241AD0F988122A999357C8465F058DB73D5ADF711D
Inner transaction hash: 0C82AF1F9488A2DBA8B6BF86BEDAE22BEEAD7A4B1CFF17790B3BB24B91A3DFE6
Wrapper transaction accepted at height 78071. Used 74 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 78072. Used 10179 gas.
```

Tagging team to please look into this @brentstone @Fraccaman. Apologies for reporting one more bug 😅 . I think its a bug, but please let me know If I am missing something 🙂

**Comment by Rigorously** [comment]
Same with withdraw. Although I wonder what the point of using `disposable-gas-payer` is when being unable to delegate from a non-transparent address to begin with, since the delegator's address will be public anyway.

**Comment by grarco** [comment]
@spidey-169 Did you try with

`--gas-spending-key $WALLET_SHIELDED` ?

**Comment by spidey-169** [comment]
> @spidey-169 Did you try with
> 
> `--gas-spending-key $WALLET_SHIELDED` ?

That fixed it. I guess being up all night will make you do mistakes like these. Thanks @grarco! Will keep testing further if I find something else
