### ISSUE TITLE
namadac shielded-sync run for too long

### ISSUE THREAD

**Issue by quangtuyen88** [anoma/namada#2734]
Hello @brentstone @sug0 .. will we keep using this command in the future? 
Actually, it will solve issue with shield txt being faster after synced but the issue is sync will take more time and sync data is not stored on the server.

```
namadac shielded-sync --node https://namada-rpc.kzvn.xyz
==== Shielded sync started ====


Scanning 11645 of 17136
[###################################################################.................................] ~~ 67 %

```

it took me 3 hours still not able to do full sync.  Can we implement caching and a sync flag to sync data from the last data ?

_Originally posted by @quangtuyen88 in https://github.com/anoma/namada/issues/2705#issuecomment-1966121844_

**Comment by grarco** [comment]
@quangtuyen88 the client should be caching the result of a `sync` command so that the next time it will resume from where it stopped. Are you sure this is not happening for you?

On a side note, we are working on other ways to further improve the performance of this command to make it faster

**Comment by encipher88** [comment]
that's right, when we start balance synchronization it starts from the same place, but it still takes a very long time

**Comment by quangtuyen88** [comment]
Hello @grarco  yes it will resync but I can make sure it will not sync from the last flag : 

```
namadac shielded-sync --node https://namada-rpc.kzvn.xyz
==== Shielded sync started ====


Fetched block 53733 of 83732
[#...................................................................................................] ~~ 1 %
```
last block yesterday already synced at higher 72000 . I did resync today and it started syncing again from block 53732.

after more than 2h still at step scanning

```
 namadac shielded-sync --node https://namada-rpc.kzvn.xyz
==== Shielded sync started ====


Scanning 4514 of 8491
```

**Comment by quangtuyen88** [comment]
Sorry seem I run on the wrong server 

@grarco : I run on another server it will start from block higher than 72000 and scanning also fast.

```
namadac shielded-sync --node https://namada-rpc.kzvn.xyz
==== Shielded sync started ====


Scanning 121 of 598
[####################................................................................................] ~~ 20 %
```

**Comment by grarco** [comment]
@encipher88 downloading the context from a peer is not a feasible solution because its content depends on your specific keys

**Comment by encipher88** [comment]
@grarco ok i understand now

**Comment by quangtuyen88** [comment]
Hello @grarco do we have an update for this? 
if we can't implement a host for caching shield transactions can we add a flag to since from to and implement sync faster ?  Not sure why we need to sync all shield txt on client side
ex : 
` namadac shielded-sync 10000 50000`
also I created ticket for a resource use when running `namadac shielded-sync` https://github.com/anoma/namada/issues/2874

**Comment by brentstone** [comment]
This is documented in several other issues at this point, and we are working on solutions for mainnet. Closing now.
