### ISSUE TITLE
ROIDS are not displayed in the RANKING

### ISSUE THREAD

**Issue by AlexITProf** [anoma/namada#2745]
I'm a PILOT.
My addresses are in balances.toml
Transparent Address:
tnam1qrqql8vdv45n9h9l4ga44anz2rzcewmq3qff3v55
Public Key:
tpknam1qq3c5m079as9dfd84ppflx49v77l4ytw4r3dwmrhe8lmgzf7mkrtwetylzh

I launched my node in the shielded-expedition network.b40d8e9055, activated the validator -
tnam1q8d5a3cuyheehe5vjmun0ttysqtsp25xeuzyw9jl, bonded NAAN into it, was active
for several epochs.

Launched my node in the shielded-expedition.88f17d1d14 network, activated the validator -
tnam1q928ej8yftmn0lh6fzel4v8wm8k4nhzduydr5uk3 bonded NAAN into it, was active
for several epochs before the network was cruised on block 6288.

After restarting the shielded-expedition.88f17d1d14 network, I activated the validator -
tnam1q8k3lk3x7vgwpsdtt4e3926m9lml447z3v52v86w bonded NAAN in it,
unbonded from the validator tnam1q928ej8yftmn0lh6fzel4v8wm8k4nhzduydr5uk3 and
bonded this amount in the new validator tnam1q8k3lk3x7vgwpsdtt4e3926m9lml447z3v52v86w.

There were several more network crashes, for example, on blocks - 13315, 20768, 
but I could always get out of jail if I got into it.

After another network crash, I went to jail and I can't get out of it -
I made a comment in Issue #2642 

Also on the shielded-expedition.88f17d1d14 network, I participated in many
votes and offered my own. Performed other PILOT & CREW tasks.  I'm also working on a Class S assignment.

But why have I never seen a single ROID on my RANKING address?

**Comment by Fraccaman** [comment]
This is not the place to discuss nebb related issues. Please visit discord. Btw, a quick check with ur nebb player public key revealed that you are indeed a valid player but no transaction/task has been registered under ur account, meaning that probably you forgot about the `--memo ...` condition.
