### ISSUE TITLE
Withdraw bug #security

### ISSUE THREAD

**Issue by NodeValidatorVN** [anoma/namada#2754]
Thank you for the bug report. Please provide any information that may be relevant to the issue you're experiencing.
When I executed the "withdraw reward" command at epoch 21 (Last committed epoch: 21) before the deadline required for epoch 28 (Amount 1.500000 withdrawable starting from epoch 28), a transaction was successfully created but the reward was not received as expected. Ideally, the transaction should not have been executed.

Transaction tx:
namadac unbond --source $WALLET \
    --validator $VALIDATOR_ADDRESS \
    --amount 1.5 \
    --memo $MEMO \
    --node $NODE
Bond amount available for unbonding: 129.000000 NAM
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: A01A2BEF59F38940DEF839D67A805C2CCE217D86C18E697EDE8D38CC0D9A9958
Inner transaction hash: 6A153DD8B8D444F8C5417DA38A67AF1F21BB7BCABE20D82DA90BB01E1E3AF5F7
Wrapper transaction accepted at height 85563. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 85564. Used 9919 gas.
Amount 1.500000 withdrawable starting from epoch 28

namadac withdraw --source $WALLET \
    --validator $VALIDATOR_ADDRESS \
    --memo $MEMO \
    --node $NODE
Found 4.500000 tokens that can be withdrawn.
Submitting transaction to withdraw them...
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 537DE0A854712EFEFFD70CA28DB1AE8982CB69B0AA8748126FB4325555C46AF8
Inner transaction hash: 281299339E059566887BA0745F6F04034864F78B3F27EE72F74B6F6BF1652489
Wrapper transaction accepted at height 85575. Used 23 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 85576. Used 4205 gas.

Video for example: https://youtu.be/05OGx94AUBQ

**Comment by brentstone** [comment]
Hi, this was also reported in #2636. It is just a client bug, and it is fixed in #2748. In summary, the "Found 10.000000 tokens that can be withdrawn" was a bug. Your transaction was indeed executing but essentially was a no-op as there is nothing to actually withdraw until a later epoch.

I'll close this now.
