### ISSUE TITLE
Missing pgf steward 

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [anoma/namada#2772]
Missing is our first approved proposal as pgf steward 

namadac query-pgf --node https://rpc.namadascan.io |grep "tnam1qy24smlm8tdg8vawx8xh30fxa8kcwnudkvufz9zn" 

Proposal Id: 40
    passed with 66360338.798691 yay votes, 44871624.015204 nay votes and 2636031.500000 abstain votes, total voting power: 293666587.399925, threshold (fraction) of total voting power needed to tally: 97888862.466544 (0.333333333333)

**Comment by cwgoes** [comment]
No action appears to be necessary, but reopen if you think one is.
