### ISSUE TITLE
Quering delegations could stop the node

### ISSUE THREAD

**Issue by nodiums** [anoma/namada#2773]
While developing tools we found that while executing
namadac delegations --owner ${ownerAddress} --node ${localrpcEndpoint}
in case ownerAddress is valid address like tnam1qyueg5eyjv2lxujzy064g29drrl38nydzq54u4ah but with changed any letter in it - rpc will halt, like wen in infinite loop

This issue seems to be the same like #2716 but at this case not only validator address makes this bug

**Comment by Fraccaman** [comment]
which namada version are u running?

**Comment by nodiums** [comment]
> which namada version are u running?

as i can see fix for routers was already merged.
can't reproduce this now since chain is halted.

**Comment by brentstone** [comment]
I just tested this against my node, which is running 0.31.8, by changing one letter in your address above:
```
target/release/namadac delegations --owner tnam1qyueg5eyjv2lxujzy064g29drrl38nydzq53u4ah --node http://159.203.161.252:26657
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: "Unknown address tnam1qyueg5eyjv2lxujzy064g29drrl38nydzq53u4ah"
Location: crates/apps/src/lib/cli/context.rs:245

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

So I think perhaps this is no longer an issue.
