### ISSUE TITLE
Track MASP anchor hashes in app hash

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2794]
Per discussion

Also may need to do this for the commitment tree.

**Comment by brentstone** [comment]
Also consider doing this for the commitment tree

**Comment by grarco** [comment]
Yes this was intended for both the trees even though the conversion one should have already been addressed in the pr mentioned above

**Comment by cwgoes** [comment]
We should do this in phase 1, otherwise it might require a hard fork.

**Comment by grarco** [comment]
Yes should be quick
