### ISSUE TITLE
State Migration Brainstorming

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#2798]
We need state migration code and procedures in preparation for a hard-fork of the SE after the PRs in #2688 are merged.

- A VP change will be involved. We will need to change the following key-vals in storage:
  - wasm/hash/vp_user.wasm
  - wasm/name/vp_user.wasm
  - <parameters_address>/vp_allowlist
  - <account_address>/?
  - wasm/code/<hash>
- It should check the current node app hash to be equal to some specified app hash before applying the changes
- It should check the app hash after the changes to be equal to some specified app hash app

**Comment by cwgoes** [comment]
The state migration was performed!
