### ISSUE TITLE
no size limit on validator metadata storage

### ISSUE THREAD

**Issue by thibault-ketterer** [anoma/namada#2799]
There is an issue in the validator change metada storage
there is no size limit on the size you could store in the validator metadata fields 
email / discordid / description / website / avatar

I think it may lead to problems, storage oversize, waste of BC space.

https://github.com/anoma/namada/blob/2535c9c8bb899f4f3ae0c9e9accaf24f30e8bff4/crates/proof_of_stake/src/storage.rs#L680

I made some tests on the the only limitation I had was the tx max size, but I was able to store 1MB of "A" in the description field
but my local campfire did not crashed

I have a client that writes the 1MB of data in the desciption field you need it

just hacked cli.rs to send 1MB instead of the command line arg it received
![image](https://github.com/anoma/namada/assets/4283686/a0ad7fa9-503e-47d9-81fe-fa3dc679e127)

I think you should truncate the data to whatever size you think is good for the different fields

note: the class S bug has been reported this night
moniker Lankou
memo tpknam1qp657jtd7tzkadzua0wqr6f5cewrlrah08fn7ny92vcfjuh3lcehvnspw8y

**Comment by brentstone** [comment]
This is also noted in #2800, with the accompanying #2845 that will be included in the next release.
