### ISSUE TITLE
Emit a governance event once a proposal is submitted

### ISSUE THREAD

**Issue by Fraccaman** [anoma/namada#2801]
We should emit a governance events when a proposal is accepted on chain. The event should specify the proposal id and proposal type.

**Comment by cpp-phoenix** [comment]
Hi, I would like to work on it

**Comment by Fraccaman** [comment]
this issue requires a bigger refactor, not so easy. You are better off choosing another one :)

**Comment by Fraccaman** [comment]
Done in #3104
