### ISSUE TITLE
Bypassing Commission Check SUM=1 in `update-steward-rewards` CLI

### ISSUE THREAD

**Issue by 0x4r45h** [anoma/namada#2807]
```json
{
  "reward_distribution": {
    "tnam1q9xanp32tspg4ruhpffq7rc5us0yxdcqpulwevgq": "0.9",
    "tnam1q9jpj9u5p6ugjylarkwmj9tsxr0pjlgpn5wa8ff0": "0.2",
    "tnam1qxeshg4ua9g5z653fzkjwtcpvlr3t76r0u5e7g7w": "-0.1"
  }
}
```
if you pass a commission file like this to `namadac update-steward-rewards` command, the CLI will dispatch the tx even without the `--force`  flag     

While the transaction will eventually be rejected by VPs, I believe it's worth investigating similar patterns in other parts of the code.   

I also encountered an ambiguity: when you set the total reward distribution to something smaller than 1, such as '0.6', what happens to the remaining '0.4'?

Version:
Namada v0.31.6

**Comment by zenodeapp** [comment]
Interesting!
