### ISSUE TITLE
Error with showing the balance of a particular token.

### ISSUE THREAD

**Issue by DmitriiRabeckii** [anoma/namada#2809]
The first thing I found was when entering a command to show my wallet balance, for a specific token:
**`namada client balance --owner $VALIDATOR_ALIAS --token naan --node https://rpc.crazydimka.xyz`**
I get a lot of errors when I try to specify my own token, bad (--token naan).
![2024-03-05_01-37-37](https://github.com/anoma/namada/assets/25347359/892b8ad4-a69d-415d-9076-a4145f531525)
But I have it added to my wallet.toml
![2024-03-05_01-38-45](https://github.com/anoma/namada/assets/25347359/cd515ccc-d662-47fc-8b2e-30ee338b41db)
But if I don't specify which token to show me, it works fine.
**`namada client balance --owner $VALIDATOR_ALIAS --node https://rpc.crazydimka.xyz/`**
**BUT, IMPORTANTLY, then I don't get a specific coin, for example, when I do a lot of different ibc transactions and I need to find a specific token on my balance.
So I think this is a bug that I have noticed and it is worthy of a ROID rating.**

**Comment by yito88** [comment]
This will be fixed in #2729
