### ISSUE TITLE
bug：error in the docker images amada-v0.31.6

### ISSUE THREAD

**Issue by shuoer86** [anoma/namada#2811]
When running `namadac` command in the docker container from image `ghcr.io/anoma/namada:namada-v0.31.6`, 

it failed with the following error.

`namadac: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by hkey0** [comment]
This problem is not related to namada or namadac.
https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by shuoer86** [comment]
@hkey0 @cwgoes thanks for your discussions. 

But when we build namada or namdac, we need the related dependent libs.

And at least, we need to add the libs into the docker image when we release the image.

**Comment by shuoer86** [comment]
@cwgoes could you help to re-open it, or if not, could you tell me which repo to discuss and release this namada docker images?

**Comment by shuoer86** [comment]
> This problem is not related to namada or namadac. https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

we need to add the libs into namada image, otherwise, the namada container fails to run.

**Comment by shuoer86** [comment]
> This problem is not related to namada or namadac. https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

I don't agree with you. We need make all the libs and enviroments ready for docker images.
