### ISSUE TITLE
Disable custom wasm code execution in the RPC

### ISSUE THREAD

**Issue by sug0** [anoma/namada#2815]
- [ ] Disable custom wasm execution in dry ran txs.
- [ ] Remove `TxCustom` from the sdk args.

**Comment by cwgoes** [comment]
@Fraccaman to ask @sug0

**Comment by sug0** [comment]
@cwgoes @Fraccaman this issue was created before we had gas metering at the instruction level in wasm. this allowed you to submit transactions with infinite loops, DoSing the node you submitted the tx to; now, you'll eventually run out of gas, when dry running a tx with an infinite loop. I think it's fine to allow the execution of arbitrary wasms in the RPC, which might be useful to estimate the gas cost of a governance proposal. most nodes will probably want to disable this functionality, though, since it might have a significant CPU cost

**Comment by Fraccaman** [comment]
perfect thanks! Ill close this :)
