### ISSUE TITLE
Trying to check viewing key balance results in a crush

### ISSUE THREAD

**Issue by TerzoMillenio** [anoma/namada#2830]
I tried the following command and got the same result on both 0.31.8 and 0.31.6:
root@root:~# namadac balance --owner zvknam1qwq5x2aeqqqqqqqrwt8q4nga8smeyh2666855gxjhcmaxz4wutfvj6evpt6j89fvsm5ckrv0mkft38vxm7xx9prjajh2cn6aacpd9vac2j4v0vk2eqxkq6886merzclgng2y5g24damlzrh3sygplmjuezrctslyhm275srzw4t4hqh0k86qfl6tefqukgydfvgyl3y72w7tjmgfrxyzw4unhf0fq94y2knzhe9kctnfuhj8fus684lm9cs6f4qw78gdm9jf7vlahzc47mgge --node http://127.0.0.1:26657
Last committed epoch: 23
The application panicked (crashed).
Message:  context should contain viewing key
Location: /home/runner/work/namada/namada/crates/apps/src/lib/client/rpc.rs:1160

What happens is the node freezes for a little while and then panics.
I wonder if that's me doing something wrong or that is a bug, Probably the second, because the application should not crash no matter what I request.

**Comment by Fraccaman** [comment]
`balance` command was refactored in #2886.
