### ISSUE TITLE
Investigate whether we can create a second MASP epoch tracker

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#2833]
h/t @gavinly 

Investigate whether we can create a second MASP epoch, where `masp_epoch = regular_epoch % n` (`mod n`), where `n` could be, for example, `4` - the objective being to allow faster epochs without letting the conversion table grow too much.

**Comment by cwgoes** [comment]
@grarco any idea of how difficult this is?

**Comment by grarco** [comment]
We are still waiting for a confirmation on whether this is actually needed

**Comment by cwgoes** [comment]
A confirmation from whom?

**Comment by grarco** [comment]
@gavinly

**Comment by gavinly** [comment]
i'm ambivalent about prioritizing an epoch time decrease: it doesn't have to be a priority, but i'm concerned that it could be stuck like this forever, once it's the default (politically and/or dev priority). is there some in-between option that wouldn't require creating a second MASP epoch?

**Comment by grarco** [comment]
I agree there's no other option. I'd say it takes a few days (but hard to say for certain until I start to work on this)

**Comment by cwgoes** [comment]
Let's revaluate this again next week after other definitely necessary work is completed.
