### ISSUE TITLE
Bug/feat: shielded-sync still requires `--node` or is this a feature?

### ISSUE THREAD

**Issue by zenodeapp** [anoma/namada#2867]
Is it normal for `shielded-sync` to require the `--node` field. This is probably still a leftover issue from 0.31.6?

Or are shielded sync's going to be linked to RPCs? (a potential solution for having to keep syncing like this and allowing shielded accounts to be 'accessible' outside of the CLI?).

Or like perhaps it's an idea to create an entire class of its own. Not RPCs, but having nodes that are in charge of keeping viewing keys up-to-speed with the blockchain.

**Comment by quangtuyen88** [comment]
It should work without `--node` also this already discussed in this ticket https://github.com/anoma/namada/issues/2705

**Comment by zenodeapp** [comment]
> It should work without `--node` also this already discussed in this ticket #2705

Yeah, except for the fact that it doesn't.

**Comment by quangtuyen88** [comment]
What do you mean? I'm running command without `--node`

**Comment by zenodeapp** [comment]
> What do you mean? I'm running command without `--node`

Is your node on the default port? It might be due to this that it works for you but doesn't for me.

**Comment by quangtuyen88** [comment]
Yes default port and my local server not public RPC. if you change port you need to point `namadac` to your special port for every command.

**Comment by zenodeapp** [comment]
> Yes default port and my local server not public RPC. if you change port you need to point `namadac` to your special port for every command. 

This is not the case for a while. Can do all sorts of transactions without `--node`. So found it interesting that `shielded-sync` is the only command for me needing to add it.

Think back then they made it parse the port from the config in order to use the correct port. I might be mistaken to what they did exactly, but I'm on a custom port, don't have a variable set for this and don't need to use the option/arg except for shielded sync.

**Comment by cwgoes** [comment]
@zenodeapp Is this still an issue?

**Comment by zenodeapp** [comment]
> @zenodeapp Is this still an issue?

Oh wow, I'm only seeing this just now. Apologies!
This is no longer an issue, I just checked this out on Campfire.

I'll close this, thanks.
