### ISSUE TITLE
Borsh serialize all values written to storage

### ISSUE THREAD

**Issue by sug0** [anoma/namada#2868]
Currently, the raw bytes of some values in Namada (e.g. VP and TX wasm code) are written to storage instead of their borsh serialized byte array. This poses a challenge for the migration software in Namada, which checks the types of updated key:value pairs using their borsh deserializers.

We should encode all values in storage with borsh to fix these issues.

**Comment by cwgoes** [comment]
@yito88 how long do you estimate is remaining here?

**Comment by yito88** [comment]
@cwgoes done

**Comment by yito88** [comment]
Some IBC-related data are still not-borsh serialized because they should be proven for ICS-23
