### ISSUE TITLE
MASP Shield to Shield

### ISSUE THREAD

**Issue by jipan76** [anoma/namada#2869]
When shield to shield 

Error:
   0: The balance of the source tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah is lower than the amount to be transferred. Amount to transfer is 2.000000 tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee
   1: The balance of the source tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah is lower than the amount to be transferred. Amount to transfer is 2.000000 tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee

**Comment by quangtuyen88** [comment]
You need to run `namadac shielded-sync` first before do shield txt

**Comment by opsecx** [comment]
I think maybe ask in the discord before creating bug reports for any issue you encounter.
