### ISSUE TITLE
Memo not getting sent to an ibc transfer

### ISSUE THREAD

**Issue by cpp-phoenix** [anoma/namada#2871]
The memo is not getting sent with the ibc-transfer call in v0.31.9 . It was working in previous version of namada v0.31.6 .

Command used:
```
namadac ibc-transfer --source phoenixv110 --receiver osmo1hrk8fvf4c037geylfk2hnqahq7h29m4mkndmlm --token naan --amount 1 --channel-id channel-641 --memo tpknam1qq78mp640t445hjju35sz8kjhs2c9wc05jxuelx6e28kq4xunepfjdc8kcd --node https://namada-rpc.rpc-node.xyz
```
**Latest Txn**: https://www.mintscan.io/osmosis-testnet/tx/4ADE5732EBBA14BA374036BC75AC88705B0BC0D4EE756775D3E75173FF2FB790?height=5907869

**Old Txn**: https://www.mintscan.io/osmosis-testnet/tx/4B506CD493DF53E4CC765453AA5C94E8E7C3EE0B1B56B0D6B288DF3FFB1B32FD?height=5608057

**Comment by quangtuyen88** [comment]
I think both txt mention above is type ` IBC Update Client` are you sure that is txt made by `namadac ibc-transfer` ?

**Comment by cpp-phoenix** [comment]
Hey @quangtuyen88, If you check the IBC Received section then you can see all the details of the transfer from Namada to Osmosis. Also, in the screenshot below you can see the Namada address that I sent in the memo which I initiated with the old version i.e v0.31.6. 

But the memos are not getting sent in new version v0.31.9. I tried multiple times. Please let me know if there are any other doubts.![Uploading 311505409...]

**Comment by opsecx** [comment]
could this be caused by the relayer using a version of hermes that doesn't have the long memo field available? (there's a specific hermes fork that should be used here)

**Comment by cpp-phoenix** [comment]
@opsecx, Did you try ibc-transfer with new namada version. Is the memo visible for you. If so then can you tell me your hermes version

**Comment by zenodeapp** [comment]
> Hey @quangtuyen88, If you check the IBC Received section then you can see all the details of the transfer from Namada to Osmosis. Also, in the screenshot below you can see the Namada address that I sent in the memo which I initiated with the old version i.e v0.31.6. 
> 
> But the memos are not getting sent in new version v0.31.9. I tried multiple times. Please let me know if there are any other doubts.![image](https://github.com/anoma/namada/assets/32295047/99af5540-e558-4d47-bfc0-64872e5dc5a9)

Hey this is my address in the memo 😅 in that screenshot. Might this be back when my hermes was on steroids relaying on all channels?

**Comment by cwgoes** [comment]
@yito88 is there any issue here?

**Comment by yito88** [comment]
Now a memo can be set to the ICS-20 transfer packet with `--memo` as the Namada transaction's memo section
