### ISSUE TITLE
Shielded Sync isn't working: Fails with a Querying error after a certain block

### ISSUE THREAD

**Issue by spidey-169** [anoma/namada#2872]
I am trying to execute Shielded transaction but running shielded-sync is failing. I have tried using my local node or an RPC node but the shielded sync stops at a certain bloc with the following error.

```
namadac shielded-sync --node $NODE
```

```
==== Shielded sync started ====


Fetched block 88010 of 100522
[#######################################################################################.............] ~~ 87 %Error: 
   0: Querying error: No response given in the query: 
         0: response error
         1: Internal error: read message: read tcp 127.0.0.1:45438->127.0.0.1:26658: read: connection reset by peer (code: -32603)

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.
   1: No response given in the query: 
         0: response error
         1: Internal error: read message: read tcp 127.0.0.1:45438->127.0.0.1:26658: read: connection reset by peer (code: -32603)

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.
```

I have restarted my node and tried multiple times, but still can't see to sync to perform shielded txns. Would appreciate if the team can check on this.

**Comment by quangtuyen88** [comment]
I don't have that issue 

```
namadac shielded-sync
==== Shielded sync started ====


Scanning 7693 of 7693
[####################################################################################################] ~~ 100 %Syncing finished
```
Can do shield txt after that . The connection issue maybe has issue with connecting to your RPC node.

**Comment by spidey-169** [comment]
> I don't have that issue
> 
> ```
> namadac shielded-sync
> ==== Shielded sync started ====
> 
> 
> Scanning 7693 of 7693
> [####################################################################################################] ~~ 100 %Syncing finished
> ```
> 
> Can do shield txt after that . The connection issue maybe has issue with connecting to your RPC node.

I tried in using an external node and that gave me the above error. I am now trying again without the ``--node`` flag. Will keep you posted when that finishes. Its still ongoing, will update here what happens with that

**Comment by spidey-169** [comment]
> I don't have that issue
> 
> ```
> namadac shielded-sync
> ==== Shielded sync started ====
> 
> 
> Scanning 7693 of 7693
> [####################################################################################################] ~~ 100 %Syncing finished
> ```
> 
> Can do shield txt after that . The connection issue maybe has issue with connecting to your RPC node.

It failed in my normal node as well. Don't know whats the issue. I see others in the discord facing this too

**Comment by quangtuyen88** [comment]
I tried on 2 nodes without issue.

**Comment by zenodeapp** [comment]
I had this happen today as well with two nodes, both at the same time.
