### ISSUE TITLE
namadac shield-sync error

### ISSUE THREAD

**Issue by jipan76** [anoma/namada#2875]
I run "namadac shielded-sync" and got this error:

`Fetched block 37365 of 102035
[####################################................................................................] ~~ 36 %Error: 
   0: Querying error: No response given in the query: 
         0: HTTP error
         1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.
   1: No response given in the query: 
         0: HTTP error
         1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed

      Location:
         /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

      Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
      Run with RUST_BACKTRACE=full to include source snippets.

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:341

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.`

I try run with node "namadac shielded-sync --node https://rpc.kadieu.xyz" and got same error

**Comment by spidey-169** [comment]
Yes, this seems to be the same error as the one I posted https://github.com/anoma/namada/issues/2872
