### ISSUE TITLE
Not able to sync a viewing key that's not imported?

### ISSUE THREAD

**Issue by zenodeapp** [anoma/namada#2876]
I really don't like to create so many issues.
But this comes from #2711, where I go through potential MASP improvements and have to treat the following as a separate issue.

Is the "issue" below a bug or expected behavior (_or third, I screwed something up and it should've worked 😂?_). If it's intended not to work, then it would save lots of time to not allow the sync in the first place. 

> [...] By the way, I tried to sync a viewing key I did not own in the CLI. This went through the whole chain, but as soon as I again ran the sync it started all over again! Isn't it possible to perform a shielded sync for a not imported viewing key? Asking this for trying to manoeuvre through the building of the IBC app. [...]

_Originally posted by @zenodeapp in https://github.com/anoma/namada/issues/2711#issuecomment-1987167535_

**Comment by phy-chain** [comment]
Given the way the shielded context works, I would assume that this is normal. You can as many spending/view keys to your shielded context I think ? So if you sync for a specific key, the sync goes through the whole history, and gather data for that key, then add it to the context.

**Comment by cwgoes** [comment]
cc @batconjurer Is this particular issue fixed by your shielded sync work?

**Comment by batconjurer** [comment]
> cc @batconjurer Is this particular issue fixed by your shielded sync work?

yes
