### ISSUE TITLE
Unbonding amount

### ISSUE THREAD

**Issue by StoneMac65** [anoma/namada#2878]
I bonded 29500 naan to my own validator using my implicit account, since then I can not unbond those amounts and cant even see that. the only option I see is 1000 naan which I self bonded using my validator account to vote for proposal 266 (which apparently was another bug)

if I use 

```
namadac unbond --validator stoneva --amount 1 
Looking-up public key of tnam1q86qrpu529x8hlg2dh2fjjvjs0w7pm2gty49c73r from the ledger...
Bond amount available for unbonding: 1000.000000 NAM
Enter your decryption password: 
```

or 

 ```
namadac unbond --validator stoneva --amount 1 --signing-keys stonese
Bond amount available for unbonding: 1000.000000 NAM
Enter your decryption password: 
```

or

```
namadac unbond --validator stoneva --amount 1 --alias stonese
Looking-up public key of tnam1q86qrpu529x8hlg2dh2fjjvjs0w7pm2gty49c73r from the ledger...
Bond amount available for unbonding: 1000.000000 NAM
Enter your decryption password: 
```
 I get the same resualt which is only showing the amount of self-delegation from my validator to itself and not delegations from my Imlicit account to my validator
 
 before self delegation using validator account I used to face this error
 
```
   0: Querying error: No response given in the query: Info log: RPC error: Cannot find bond, error code: 1
   1: No response given in the query: Info log: RPC error: Cannot find bond, error code: 1
```

**Comment by StoneMac65** [comment]
```
namadac validator-state --validator stoneva
Validator tnam1q86qrpu529x8hlg2dh2fjjvjs0w7pm2gty49c73r is in the consensus set
```

```

Delegations from tnam1qr4vlrtptct4tzxqv5fpm4uhepuuj0ynzup93v2y to tnam1q86qrpu529x8hlg2dh2fjjvjs0w7pm2gty49c73r:
  Remaining active bond from epoch 3: Δ 28001.000000 (slashed 0.000000)
  Remaining active bond from epoch 4: Δ 400.000000 (slashed 0.000000)
  Remaining active bond from epoch 5: Δ 998.000000 (slashed 0.000000)
  Remaining active bond from epoch 13: Δ 97.000000 (slashed 0.000000)
Active (slashable) bonds total: 29496.000000
Bonds total: 29496.000000
```

**Comment by brentstone** [comment]
Your implicit account and you validator account are completely separate addresses and accounts. The protocol does not know they are related. When you run `namadac unbond` with only the `--validator` arg and no `--source`, it is interpreted as unbonding only available self-bonds, which I think you suggest is showing correctly.

In order to unbond the delegations you made from the implicit account, you must use `namadac unbond --source <implicit_address> --validator stoneva`

**Comment by StoneMac65** [comment]
> Your implicit account and you validator account are completely separate addresses and accounts. The protocol does not know they are related and both owned by you. When you run `namadac unbond` with only the `--validator` arg and no `--source`, it is interpreted as unbonding only available self-bonds, which I think you suggest is showing correctly.
> 
> In order to unbond the delegations you made from the implicit account, you must use `namadac unbond --source tnam1qr4vlrtptct4tzxqv5fpm4uhepuuj0ynzup93v2y --validator stoneva`

I understand the --source flag usage is mandatory in this situation but before network resync I could see the unboding amount of a validator which I redelegated to without that flag. If I redelegate the token from my own validator to another, the source of that amount is my implicit or validator account?

**Comment by brentstone** [comment]
Hmm in the most recent release and resync, no code was included that touched any of this stuff I don't believe. In general, when you redelegate you are explicitly providing a source/owner, so it depends whose bonds you are redelegating explicitly. However, I can tell you that the protocol forbids validators from bonding to another validator, so you could have only redelegated the bonds from implicit address --> validator address. Hope this helps explain things.
