### ISSUE TITLE
governance proposals end at the end of the designated Epoch instead of the start

### ISSUE THREAD

**Issue by gavinly** [anoma/namada#2884]
the voting period for a governance proposal is not intuitive

for example, the Shielded Expedition's Prop266 governance proposal was set to run from Epoch 24 to Epoch 28, but didn't end until Epoch 29 started. it's confusing to me, because if i specify that i want a proposal to start at Epoch 24, it should not start at the end of Epoch 24, and so when i specify that i want the proposal to end at Epoch 28, i expect that it should be when Epoch 28 starts.

this should either be updated in the code or in the CLI

**Comment by brentstone** [comment]
I've addressed something similar to this in #2630, when I was annoyed by the name of the term `grace_epoch` and the fact that a governance proposal is executed at the beginning of the epoch following the `grace_epoch`. In there, I changed the name to `activation_epoch`, and the governance proposal is executed at the beginning of `activation_epoch`.

Happy to change the voting end epoch convention in there too if it seems that it would be more intuitive for that epoch to be the first epoch in which voting stops.
