### ISSUE TITLE
Init proposal PFG Funding unlimited amount

### ISSUE THREAD

**Issue by substance07** [anoma/namada#2885]
I have successfully created proposal #315 with a large amount, is it a bug?
`Proposal Id: 315
Type: PGF funding
Author: tnam1qrhnj4cw0d6agek9v8yxs3p2arxynmc3ucn5ekua
Content: {"abstract": "", "authors": "", "created": "2024-03-09T00:00:01Z", "details": "I test new bug for PFG Funding", "discussions-to": "", "license": "MIT", "motivation": "", "title": "Unlimit for PFG Funding Testing"}
Start Epoch: 30
End Epoch: 32
Grace Epoch: 34
Status: pending
Data: Actions:
  Continuous: Add(Internal address=tnam1qrhnj4cw0d6agek9v8yxs3p2arxynmc3ucn5ekua, amount=100000000000000000000000)
  Retroactive: Internal address=tnam1qrhnj4cw0d6agek9v8yxs3p2arxynmc3ucn5ekua, amount=150000000000000000`

**Comment by Fraccaman** [comment]
PGF proposal can request any amount of tokens, if the PGF account has not enough balance, the transfer will fail
