### ISSUE TITLE
Proposal to Improve Query Performance by Removing Redundant Code

### ISSUE THREAD

**Issue by duyhla** [anoma/namada#2887]
Improve balance query #2886 

Upon reviewing our codebase, I've noticed that querying transparent balances might not always be necessary, and it could significantly slow down the overall process due to the large amount of data involved. Therefore, I suggest removing the section of code responsible for querying transparent balances entirely.

By removing the call to query_transparent_balance and query_shielded_balance, we can potentially improve the overall performance of our querying process, especially when dealing with large datasets. This optimization ensures that we only query the balances that are essential for our operations, thus reducing unnecessary processing time and resource consumption.

**Comment by danhnguyen1-tiki** [comment]
It's useful. I run "namadac balance" and get over 10 GB response. My node is lagging and got stuck. My network also slows down.

**Comment by danhnguyen1-tiki** [comment]
I have checked. I spend $0.25 for this command (network fee of AWS). I can't imagine when we have a million accounts =]]

**Comment by brentstone** [comment]
Closing, as progress here will be tracked in #3014.
