### ISSUE TITLE
Error when Voting on Proposal with Changed Validator Consensus Keys

### ISSUE THREAD

**Issue by zaki9501** [anoma/namada#2888]
**Bug Description:**
I encountered an issue while attempting to vote on a proposal using the validator address `tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy` to which I have delegated. The delegation was made at epoch 26, and the validator is currently part of the consensus set. However, when trying to vote on a proposal using this validator, the transaction was rejected by the Validator Peers (VPs) with the following error message:
the exact command I'm using to cote: 

Transaction was rejected by VPs: [
"tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy"
].
Changed keys: [
"#tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6/proposal/316/vote/#tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy/#tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy"
]

**Environment Information:**
- Namada Version: v0.31.9
- Operating System:  Ubuntu 22.04
- Validator Address: `tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy`

**Comment by opsecx** [comment]
For more context (from discord), the situation is op have delegations only to jailed validators and this unjailed validator where the error occurs. Suspect the change consensus keys bug is still in play somehow.
