### ISSUE TITLE
Forced transfers exceeding balance are regarded as successful

### ISSUE THREAD

**Issue by Rigorously** [anoma/namada#2893]
A forced transfer with an amount exceeding balance and/or using a non-token address as token such as your implicit address will be rejected, however the transaction is deemed successful.

```
namadac transfer --source rigorous --target rigorous --token rigorous --amount 99999999 --force
Submitting a tx to reveal the public key for address tnam1qrqgs5e67esl3yjdq3dccls0470ctcm6m5kx4cal...
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: FEFDA1B79C8C324CC8FEF94663B1F12BA8A478A061ADBAE04BFD8BFD6C38F262
Inner transaction hash: BD93013E23E86E0E0B1478747A1F95FCDA8F70770F51D7B5F067F1423FE86DEA
Wrapper transaction accepted at height 116693. Used 20 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1qrqgs5e67esl3yjdq3dccls0470ctcm6m5kx4cal"
].
Changed keys: [
  "#tnam1qrqgs5e67esl3yjdq3dccls0470ctcm6m5kx4cal/public_keys/data/00"
]
No balance found for the source tnam1qrqgs5e67esl3yjdq3dccls0470ctcm6m5kx4cal of token tnam1qrqgs5e67esl3yjdq3dccls0470ctcm6m5kx4cal
Transaction added to mempool.
Wrapper transaction hash: 8C47AB297BF5F2F3F4D0F76B34F60918A0D53A9ED91E4523E4F0351464F56733
Inner transaction hash: 8682B469E837603CFB3BD11D9D6EDF62D1261920FCC359DE11F7BA2C47396B86
Wrapper transaction accepted at height 116695. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 116696. Used 3397 gas.
```

https://namascan.com/tx/8682B469E837603CFB3BD11D9D6EDF62D1261920FCC359DE11F7BA2C47396B86

![image](https://github.com/anoma/namada/assets/31181988/2a5e11f6-de82-4f1d-876c-68a500958b59)

![image](https://github.com/anoma/namada/assets/31181988/97175e23-47c7-4c58-81a2-49a947e8031b)

**Comment by quangtuyen88** [comment]
The weird is it's transfer txt but log print : 

```
Submitting a tx to reveal the public key for address 
```

**Comment by Fraccaman** [comment]
isn't the transaction hash `BD93013E23E86E0E0B1478747A1F95FCDA8F70770F51D7B5F067F1423FE86DEA` ? but the namadascan urls points to a different hash

**Comment by Rigorously** [comment]
I did not explicitly execute `reveal public key`. It was done automatically by the `transfer` command with the inner transaction hash `8682B469E837603CFB3BD11D9D6EDF62D1261920FCC359DE11F7BA2C47396B86`.

Namadexer shows that `Reveal Pk` failed, while the `Transfer` was successful.

![image](https://github.com/anoma/namada/assets/31181988/08937e7f-7c60-4d6d-82c2-2b47d3d4a444)

Here is the transaction log of the automatic `reveal public key` on Namascan:

https://namascan.com/tx/BD93013E23E86E0E0B1478747A1F95FCDA8F70770F51D7B5F067F1423FE86DEA

![image](https://github.com/anoma/namada/assets/31181988/0304e1fd-d6d2-4e79-a7b8-dbbe97ea5823)

And finally, on a tool I am working on, it shows a quite big sum of Naan sent and received with my account, after trying out how far I could push the `transfer` command (256-bit with a couple decimals).

![image](https://github.com/anoma/namada/assets/31181988/01c19130-a60e-43b7-a2ec-71c0239814b1)

**Comment by Fraccaman** [comment]
got it, we can look into this, thanks for opening an issue

**Comment by opsecx** [comment]
I wonder if this in reality is a Namadexer issue. The tools above draw their data from indexer afaik. (at least mine does - the tool Rigorous is working on)

**Comment by Rigorously** [comment]
> I wonder if this in reality is a Namadexer issue. The tools above draw their data from indexer afaik. (at least mine does - the tool Rigorous is working on)

In the first post you can see that `namadac` also says that the automatic `Submitting a tx to reveal the public key` transaction was rejected, while the `transfer` transaction that comes after that was added to the mempool and successfully applied.

**Comment by Rigorously** [comment]
Opened a separate issue for the `Submitting a tx to reveal the public key` when using `--force`.
https://github.com/anoma/namada/issues/2919

**Comment by cwgoes** [comment]
Should no longer be an issue.
