### ISSUE TITLE
storage hash cons values

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#29]
Allow to hash cons' storage to remove redundancy. The obvious one is the accounts' validity predicates, which currently take most of the space. We might want to use it for other things too in future, but probably not all the storage values would benefit from it.

Related issue anoma/anoma#285.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762978342503) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
We should definitely do this, but it's not a launch requirement for Namada. If we end up with many different copies of the multisignature VP being deployed, though, would that consume a lot of storage?

**Comment by cwgoes** [comment]
@yito88 can you look into this in conjunction with investigating the rocksdb issue? we don't need to implement hash consing, but we should first do a rough estimate of storage usage if we deploy a bunch of multisigs (+ maybe it's easy to deduplicate the code there / maybe this is happening already?)
