### ISSUE TITLE
RAM usage is increased 

### ISSUE THREAD

**Issue by encipher88** [anoma/namada#2901]
![Screenshot_435](https://github.com/anoma/namada/assets/36136421/4b011496-6793-4c59-a922-5abf962d0f04)
after rewards on usage RAM is up to 27gb , is it memory bug or its normal ?

**Comment by Fraccaman** [comment]
this might depends on your rocksdb cache size too

**Comment by opsecx** [comment]
> ![Screenshot_435](https://github.com/anoma/namada/assets/36136421/4b011496-6793-4c59-a922-5abf962d0f04)
> 
> after rewards on usage RAM is up to 27gb , is it memory bug or its normal ?

getting similar here but different context. https://github.com/anoma/namada/issues/2950

**Comment by brentstone** [comment]
Going to close as #2950 seems to suffice for tracking this.
