### ISSUE TITLE
cors_allowed_origins in config.toml is not working

### ISSUE THREAD

**Issue by stanisloe** [anoma/namada#2903]
Default rpc parameters in config.toml are the following
```
[ledger.cometbft.rpc] 
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = []
cors_allowed_methods = ["HEAD"  "GET"  "POST"]
```

Even though `cors_allowed_origins = []` should not allow any hosts to query rpc, rpc endpoint is still available. This might cause network stability issues as a simple query can halt validator node which happened during shielded expedition already with my validator [ disclaimer: no validator node was jailed during this incident ].
This is the default config for all cosmos nodes I've worked with and is expected to have rpc port closed, but as it is not the case with namada, during the start of the chain many validators might have this config and the network will be at risk of halting.

As a workaround I'm currently using this `laddr` to avoid spam requests to my validator

```
laddr = "tcp://127.0.0.1:26657"
```

**Comment by Fraccaman** [comment]
node operator should review the config before start the node. Validator node by default always start with their rpc node open only to local connections.

**Comment by stanisloe** [comment]
Hmm, just tried running new node and it seems like it's being fixed since my last shielded expedition task submission. Great !
