### ISSUE TITLE
Proposed improvements for shielded balances

### ISSUE THREAD

**Issue by CroutonDigital** [anoma/namada#2905]
Proposed improvements for shielded balances

- on cli/extension side, store last processed block and last balance
- update values every block or ten blocks, do not wait for end of process
- expose stale balance and timestamp to increase UX 
- investigate gomomorphic encryption as a way to calculate final balance on node side without going through all the blocks

**Comment by thousandsofthem** [comment]
- When creating new shielded key, set last processed block at around current timestamp, to skip re-validating whole Blockchain

**Comment by brentstone** [comment]
Will close this now, but tracking in #2900.
