### ISSUE TITLE
Voting error, tx goes through

### ISSUE THREAD

**Issue by opsecx** [anoma/namada#2907]
Tried voting on a proposal earlier, and got this error:

1: No response given in the query: 
         0: HTTP error
         1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed.

This is the same error we have been getting on shielded-sync. In spite of the error, the vote is registered as success in shielded nebb and indexer. All other votes around same time went through as expected in client UX this morning.

Putting this up here due to similar errors when shielded-sync, maybe it's a more general sporadic error. (can the timeout be related to config-settings and precomit delta = 0?)

**Comment by opsecx** [comment]
Getting same today on server with lower spec (16GB ram, lies constantly with abt 7GB free), server with higher spec no issues. Following two errors on consecutive voting attempts (votes are again registered as being cast post event):

Waiting for inner transaction result...
Transaction status query deadline of Instant { tv_sec: 3397659, tv_nsec: 122071437 } exceeded
Error: 
0: Timed out waiting for tx to be applied
1: Timed out waiting for tx to be applied

Location:
/home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:188

And later (separate tx/vote):

Enter your decryption password: 
Error: 
   0: Encountered error while broadcasting transaction: 
   0:    0: HTTP error
   0:    1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed

   0: Location:
   0:    /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

   0: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
   0: Run with RUST_BACKTRACE=full to include source snippets.
   1: Encountered error while broadcasting transaction: 
   1:    0: HTTP error
   1:    1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed

   1: Location:
   1:    /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

   1: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
   1: Run with RUST_BACKTRACE=full to include source snippets.

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:188

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by opsecx** [comment]
Others in discord are mentioning similar difficulties, there seems to be some looming performance issues as best can tell

**Comment by cwgoes** [comment]
Thanks for the report. Please reopen if there is a replicable issue here.
