### ISSUE TITLE
Type safety for `block_write_log` 

### ISSUE THREAD

**Issue by grarco** [anoma/namada#2915]
Currently the `block_write_log` field of the write log is defined as:

https://github.com/anoma/namada/blob/cc3edde4d572ff41f19d24b5b7da60406acdfdf4/crates/state/src/write_log.rs#L84

where the storage modification is:

https://github.com/anoma/namada/blob/cc3edde4d572ff41f19d24b5b7da60406acdfdf4/crates/state/src/write_log.rs#L43-L64

The block write log though, can and should never contain an entry of the `StorageModification::Temp` variant. Something similar has been introduced in #2735 with a `PersistentStorageModification` enum. We could think about utilizing this also in the block write log to enforce safety via the type system.

**Comment by yito88** [comment]
That makes sense. By the way, I added `write_temp`  and `read_temp` for IBC operations a long time ago. However, IBC doesn't use them after some fixes. I suppose we can remove them if we don't use them anymore.

**Comment by tzemanovic** [comment]
> That makes sense. By the way, I added `write_temp` and `read_temp` for IBC operations a long time ago. However, IBC doesn't use them after some fixes. I suppose we can remove them if we don't use them anymore.

I might have a new use case for them to help with changes needed for #2629 where I'm gonna use these from txs to signal to VPs the type of tx to simplify validation impl for PoS (and maybe elsewhere too)

**Comment by cwgoes** [comment]
aiming for merge today
