### ISSUE TITLE
The requested data is not being displayed correctly. The **DATA** field appears empty instead of showing the expected content

### ISSUE THREAD

**Issue by Michel-Leidson** [anoma/namada#2924]
**Note**:  Previously, it had been opened in the "shielded-expendition" repository, but now it has been reopened in the correct repository.   https://github.com/anoma/namada-shielded-expedition/issues/354

cat proposal.json
{
"proposal": {
"id": 310,
"content": {
"title": "Integration Proposal",
"authors": "StakePool",
"discussions-to": "forum.namada.net/testnet",
"created": "2024-03-08T12:00:00Z",
"license": "MIT",
"abstract": "This proposal testnet",
"motivation": "Integrating.",
"details": "The proposal techical specifications for the integration.",
"requires": "0"
},
"author": "tnam1q8q0g5j4k9ume9lapusf7wz9z3n7t8g4mszfsmtq",
"voting_start_epoch": 30,
"voting_end_epoch": 32,
"grace_epoch": 34
},
"data": [48,120,54,48,54,48,52,48,53,50,54,48,52,48,56,48,53,49,57,48,56,49,48,49,54,48,52,48,53,50,56,48,54,48,48,98,56,49,53,50,54,48,50,48,48,49,55,102,52,56,54,53,50,48,48,98,56,49,53,50,53,54,48,49,57,48,56,48,53,49,57,48,54,48,49,57,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,8,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,53,50,53,48,54,48,48,98,56,49,5]
}

namada client query-proposal --proposal-id 305 --node http://localhost:26657/
Last committed epoch: 30
Proposal Id: 305
Type: Default
Author: tnam1q8q0g5j4k9ume9lapusf7wz9z3n7t8g4mszfsmtq
Content: {"abstract": "This proposal testnet", "authors": "StakePool", "created": "2024-03-08T12:00:00Z", "details": "The proposal techical specifications for the integration.", "discussions-to": "forum.namada.net/testnet", "license": "MIT", "motivation": "Integrating.", "requires": "0", "title": "Integration Proposal"}
Start Epoch: 30
End Epoch: 32
Grace Epoch: 34
Status: on-going
Data:

**Comment by Fraccaman** [comment]
Done in #2803
