### ISSUE TITLE
Namada command showing wrong output

### ISSUE THREAD

**Issue by UnitedMiners** [anoma/namada#2925]
When executing the command: 
 
 namadac find-validator --tm-address=$(curl -s localhost:33357/status | jq -r .result.validator_info.address)
 
 No validator with Tendermint address 9EB75D1FF20FD14B46A58E220F18FC38EF492159 found.
 
 However this is not correct, as I am running my ndoe on port:33357 see:
 
 
 
 curl localhost:33357/status | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1054  100  1054    0     0   801k      0 --:--:-- --:--:-- --:--:-- 1029k
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "8",
        "block": "11",
        "app": "0"
      },
      "id": "9195361db5911da0c507fe72f633904d27a31c16",
      "listen_addr": "tcp://0.0.0.0:33356",
      "network": "shielded-expedition.88f17d1d14",
      "version": "0.37.2",
      "channels": "40202122233038606100",
      "moniker": "technodrome-v0.31.9",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:33357"
      }
    },
    "sync_info": {
      "latest_block_hash": "3829034EE1AF0C3C69150E9F166A05A558FB547B90343CF3CF0899B0DFB112FE",
      "latest_app_hash": "F14F0137B8FC542DA7CC6467D86B41E55A5AA0CE060E6A87DE95980EBE16C6DB",
      "latest_block_height": "176568",
      "latest_block_time": "2024-03-19T18:23:52.629588902Z",
      "earliest_block_hash": "782DCDEBD5FB5EB74E1832F048E6715B0FE2B9C9FC029885BE054ECD25E01739",
      "earliest_app_hash": "",
      "earliest_block_height": "1",
      "earliest_block_time": "2024-02-06T18:00:00Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "CE4F0D97A9F622B02ACD897424ABA320D4628AC0",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "Voqvw5UsRYwy2ENhdffel49NfAtZ27uxznuTASEjOnM="
      },
      "voting_power": "2004000000"
    }
  }
}

namadac find-validator --tm-address=$(curl -s localhost:33357/status | jq -r .result.validator_info.address)
Found validator address "tnam1q88vn26unjqx2yzerga75jln998ykf3s7gtaagy5".
Consensus key: tpknam1qptg4t7rj5kytrpjmppkza0hm6tc7ntupdvahwa3eeaexqfpyva8xjees5h
Tendermint key: CE4F0D97A9F622B02ACD897424ABA320D4628AC0
Consensus key hash: CE35C34B859641495D35AB60C689C1B2415185EE

If I try to define other ports I receive as output Expected 40 characters in Tendermint address, got 0

**Comment by brentstone** [comment]
I'm a bit confused... you write the same exact command `namadac find-validator --tm-address=$(curl -s localhost:33357/status | jq -r .result.validator_info.address)` for both your failing output and your successful output below that one.
