### ISSUE TITLE
Residual PoS inflation to PGF

### ISSUE THREAD

**Issue by grarco** [anoma/namada#2927]
Currently the residual, undistributed amount of PoS inflation is distributed to the `Governance` address. It's probably better if we distributed this amount to `PGF` instead so that it can be later spent.

For reference: @batconjurer, @cwgoes, @Fraccaman, @brentstone

**Comment by cwgoes** [comment]
What do you mean by "residual/undistributed" - do you mean unclaimed? Or not possible to claim?

**Comment by brentstone** [comment]
Check `proof_of_stake::rewards::update_rewards_products_and_mint_inflation`, due to `Dec` computations, sometimes there is some dust remaining from the inflation minted after distributing the proper shares to each validator. This dust amount is currently sent to the Gov address.

**Comment by cwgoes** [comment]
I see. I think that dust amount can be sent to PGF instead, yes.
