### ISSUE TITLE
priority for implementing State Sync

### ISSUE THREAD

**Issue by gavinly** [anoma/namada#2929]
my understanding is that if the Namada chain has had a hard fork in its history, syncing from scratch will require one of these:

1. sync using pre-fork version of client and wasm until the fork block height, then continue syncing with the new version of client and wasm version. the likely problem is that nobody in the network will still be running the pre-fork version, and there will be no peers to begin syncing with

2. sync post-fork from a hosted snapshot. the hosting dependency involves availability risk (perhaps this could be hosted using IPFS) and also the operator must be aware that they cannot organically sync from scratch

3. state sync enables anyone to begin syncing from a post-fork block height. state sync is not yet implemented in Namada. do we know how this would affect tools and applications that need the entire transaction history? eg. Mintscan

i'd like our operators to be aware and able to handle a consensus-breaking hard fork ahead of mainnet, so i think it would be good to decide how we want to do these for mainnet

**Comment by gavinly** [comment]
@Fraccaman @brentstone does this write-up seem correct?

**Comment by cwgoes** [comment]
Thanks for the priority input - we've mostly finished implementing state sync.
