### ISSUE TITLE
Claiming Rewards Despite Current Rewards Being 0 NAM

### ISSUE THREAD

**Issue by duyhla** [anoma/namada#2930]
## Description
When attempting to claim rewards using the namadac claim-rewards command while the current rewards available for claim are 0 NAM, the command still proceeds to execute and charges gas fees. This behavior is misleading and unnecessary, as there are no rewards to claim.
## Steps to Reproduce
1. Check the current rewards available for claim using the namadac rewards command.
2. Note that the current rewards are 0 NAM.
3. Attempt to claim rewards using the namadac claim-rewards command.
4. Observe that the command proceeds and charges gas fees despite the absence of rewards.
## Expected Behavior
When the current rewards available for claim are 0 NAM, executing the ```namadac claim-rewards``` command should result in a message indicating that there are no rewards to claim and no gas fees should be charged.
## Actual Behavior
Executing the namadac claim-rewards command when the current rewards are 0 NAM proceeds to execute the transaction and charges gas fees.
## Environment
- Operating System: Ubuntu 22.04.4 LTS
- Namada Version: v0.31.9
- Validator Address: tnam1q9ecw38yskyul5ydmj3t4zgj3n0kayx43y5jjk4e
- Command Used:
```bash
namadac claim-rewards --validator tnam1q9ecw38yskyul5ydmj3t4zgj3n0kayx43y5jjk4e --source nguyen
```
## Additional Information
- Wrapper transaction hash: 97B28C3045FCBFB59C367CDC7E2A52A76C4C4225F5F0CB96FB93056AE8F0A1FA
- Inner transaction hash: F4BEE786FCE479DE4B8F9B8D36AD7D07815A1717C4955ED671A65E911E24C94A
- Gas Used: 21 gas (Wrapper transaction), 8647 gas (Inner transaction)
- Transaction Successfully Applied at Height: 187002
## Proposed Solution
Modify the ```namadac claim-rewards``` command to validate the current rewards available for claim. If the rewards are 0 NAM, display a message indicating that there are no rewards to claim and prevent the execution of the transaction to avoid unnecessary gas fees.
## Screenshots
![image](https://github.com/anoma/namada/assets/109505975/189fde5d-67d8-46b6-9849-ac5847ef0c13)

**Comment by quangtuyen88** [comment]
It's duplicated bro
https://github.com/anoma/namada/issues/2897

**Comment by Fraccaman** [comment]
Closing as duplicate.
