### ISSUE TITLE
Able to create same alias that are reserved words.

### ISSUE THREAD

**Issue by chimmykk** [anoma/namada#2949]
Reproduce:
Create a new wallet with alias that are reserved, such as masp, publicgoodfundings etc

rilso@chimmykk ~ % namada wallet gen --alias masp
Enter your encryption password: 
Enter same passphrase again: 
Using HD derivation path m/44'/877'/0'/0'/0'
Safely store your 24 words mnemonic.
hub boil tiny olive replace fossil vintage machine happy slim piano vague patient guilt mobile slam large melody voyage program concert peanut armed finger
The alias masp is reserved.
Failed to generate a keypair.
No changes are persisted. Exiting.

So this clearly failed to generate the keypair as this already is a reserve one   "masp": Internal MASP: tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah

However i can recreate the using HOMOGLYPH
as > namada wallet gen --alias mаѕр

rilso@chimmykk ~ % namada wallet gen --alias mаѕр                                       
Enter your encryption password: 
Enter same passphrase again: 
Using HD derivation path m/44'/877'/0'/0'/0'
Safely store your 24 words mnemonic.
decide cradle lawn outer hard split strategy tell diary flower craft kiwi market cable sand spend goddess evil plunge company galaxy brain army skate
Successfully added a key and an address with alias: "mаѕр"

Output
rilso@chimmykk ~ % namada wallet list
Known transparent keys:
  Alias "tew" (encrypted):
    Public key hash: 699E81FE3494688192378AADC1E911FD8CEAB586
    Public key: tpknam1qzwake3avdzpspnxra0f4zc4y4c4pmnv5qkw05k2g9tw7vzcsv7xupc4wpk
  Alias "mаѕр" (encrypted):
    Public key hash: F77DDA6344372EADA1D18B58EF47B7C2AE459672
    Public key: tpknam1qpn0u9pf4sxpvv82xsarelqsausjrnvkspltszzukqhja0kpw3q02cdjqxj
  Alias "koireng" (encrypted):
    Public key hash: 526F32AC4C8A34A23CFA591D9E4704CDC2FD1912
    Public key: tpknam1qq5qe87yjcj2f7gxcvvknutjt0nkkvheuxvhsdwdwzxq63mkmpgeykyyzhq
Known transparent addresses:
  "ethbridge": Internal EthBridge: tnam1quqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqfgdmms
  "ethbridgepool": Internal EthBridgePool: tnam1pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu35hpf
  "governance": Internal Governance: tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6
  "ibc": Internal IBC: tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4
  "koireng": Implicit: tnam1qpfx7v4vfj9rfg3ulfv3m8j8qnxu9lgezg5mqexw
  "masp": Internal MASP: tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah
  "mаѕр": Implicit: tnam1qrmhmknrgsmjatdp6x943m68klp2u3vkwg272tv7
  "naan": Established: tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee
  "pos": Internal PoS: tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp
  "publicgoodfundings": Internal PublicGoodFundings: tnam1pgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkhgajr
  "tew": Implicit: tnam1qp5eaq07xj2x3qvjx792ms0fz87ce644sc3t7a6a

Final step > and output 

rilso@chimmykk ~ % namada wallet remove --alias masp --do-it
Successfully removed alias: "masp"
muhammednufais@chimmykk ~ % namada wallet list
Known transparent keys:
  Alias "mаѕр" (encrypted):
    Public key hash: F77DDA6344372EADA1D18B58EF47B7C2AE459672
    Public key: tpknam1qpn0u9pf4sxpvv82xsarelqsausjrnvkspltszzukqhja0kpw3q02cdjqxj
  Alias "tew" (encrypted):
    Public key hash: 699E81FE3494688192378AADC1E911FD8CEAB586
    Public key: tpknam1qzwake3avdzpspnxra0f4zc4y4c4pmnv5qkw05k2g9tw7vzcsv7xupc4wpk
  Alias "koireng" (encrypted):
    Public key hash: 526F32AC4C8A34A23CFA591D9E4704CDC2FD1912
    Public key: tpknam1qq5qe87yjcj2f7gxcvvknutjt0nkkvheuxvhsdwdwzxq63mkmpgeykyyzhq
Known transparent addresses:
  "ethbridge": Internal EthBridge: tnam1quqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqfgdmms
  "ethbridgepool": Internal EthBridgePool: tnam1pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu35hpf
  "governance": Internal Governance: tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6
  "ibc": Internal IBC: tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4
  "koireng": Implicit: tnam1qpfx7v4vfj9rfg3ulfv3m8j8qnxu9lgezg5mqexw
  "mаѕр": Implicit: tnam1qrmhmknrgsmjatdp6x943m68klp2u3vkwg272tv7
  "naan": Established: tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee
  "pos": Internal PoS: tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp
  "publicgoodfundings": Internal PublicGoodFundings: tnam1pgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkhgajr
  "tew": Implicit: tnam1qp5eaq07xj2x3qvjx792ms0fz87ce644sc3t7a6a

so the existing wallet internal just got remove. 
The issue and motivation behind here is that > Protected/Reserved words can be still manipulated.

**Comment by Rigorously** [comment]
It exactly did what you asked it to do.

You added an implicit address with an alias  "mаѕр" containing UTF-8 homoglyphs, bytes 6D D0 B0 D1 95 D1 80.

In the last step, you executed the `remove` command with the plain old ASCII "masp" alias with bytes 6D 61 73 70.

That is like adding a new address "wasp", then being surprised the internal "masp" instead of "wasp" is removed when you remove "masp".
