### ISSUE TITLE
High resource allocation for namadan

### ISSUE THREAD

**Issue by opsecx** [anoma/namada#2950]
While getting the aforementioned timeout-errors from the client, I noticed that often while that happens, namadan show up in "top" with allocated 13g in virt and 10g in res. Is this expected behavior? apologies if by design

**Comment by Fraccaman** [comment]
our nodes are running with 8gb of ram and 5.5 are constantly in use. Do u mind sharing your machine resources?

**Comment by opsecx** [comment]
> our nodes are running with 8gb of ram and 5.5 are constantly in use. Do u mind sharing your machine resources? 

sure, got two separate vps running (one crew one pilot), one has 48GB ram with I think 12 vpu, the other has 24GB with 8? vpu. the lower specced one is the one with issues. But they both display this amount of virt mem allocated which seems odd to
me. The lower specced one often fails requests from client. Higher specced one not so much.

**Comment by opsecx** [comment]
> our nodes are running with 8gb of ram and 5.5 are constantly in use. Do u mind sharing your machine resources? 

Are these validators or nodes?

**Comment by Fraccaman** [comment]
I think this could be related to #2955, as we are seeing client request failing on our infra too

**Comment by opsecx** [comment]
I'm starting to wonder if the issue has to do with different dimensionings of my network interfaces. That could be possible. But still the RAM alloc kinda bothers me. As there's about 13g actual free on avg but still it sits in virtmem.

**Comment by opsecx** [comment]
Again today, my 24GB specced server suddenly halts (namadan, not the server) after attempted shielded sync, and I have to reboot the entire thing since namadan isn't shutting down gracefully. I really do think there are some hidden performance issues.

**Comment by opsecx** [comment]
Looking now a bit later, I see current allocations to namadan are around 20GB. There seems to be an increasing resource use as chain moves along. Could there be something akin to a leak somewhere?

**Comment by cwgoes** [comment]
Thanks for the report. This should have since been fixed.
