### ISSUE TITLE
Improve masp scan speed

### ISSUE THREAD

**Issue by opsecx** [anoma/namada#2957]
suggestions to improve masp scan speed (shielded sync):
- if sync fails on fetch (where currently it's highly volatile), have a cache of already fetched data, so it can continue where it left off before halt or
- make sync more resistant to timeouts
- use several cpu threads on scan step after having fetched data. atm the scan part is too "nice" on system resources. this will obviously not improve scan on order/scale (O(n)), but will still cut down time to a lesser factor.

(will be submitting some of these ideas as s-class so don't bother if you see this. if someone else has already suggested these steps lmk and I'll retract)

**Comment by brentstone** [comment]
Will close this here, but tracking in #2900.
