### ISSUE TITLE
Clogging issues on several different operations

### ISSUE THREAD

**Issue by opsecx** [anoma/namada#2961]
There is an increasing incidence of errors thrown from node/rpc when trying to perform several different operations such as:

- voting
- transfers
- balance checks

and probably others. the same errors manifest also in

- shielded sync
(where of course it is most notable due to the high amount of linear fetches in sequence, and the low tolerance of shielded sync to errors on a single fetch, but the problem seems more general).

Today (right before the hard fork) it has been almost impossible to perform shielded syncs of any magnitude, and any other operations have also been fraught with similar errors.

I am running a setup with two different vps (one crew, one pilot) which are dimensioned a little differently. one has 24GB ram and slightly less bandwith (but still plenty), one has 48 GB Ram and a little more bandwith. The errors are more abundantly present on the smaller vps, leading me to suspect a resource clog of some kind.

When running shielded sync parallel with other tasks, a picture forms of the rpc/node/validator peforming well for some seconds, then everything halts (all requests during that timeframe). Ie it seems sometimes it struggles with requests generally and then picks up again. (unfortunately the client tools don't have a lot of tolerance for this).

This references some other issues I will link below.

An example of the error when voting this morning:

errors voting:

 1: Encountered error while broadcasting transaction: 
   1:    0: HTTP error
   1:    1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed

   1: Location:
   1:    /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

   1: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
   1: Run with RUST_BACKTRACE=full to include source snippets.

Location:
   /home/runner/work/namada/namada/crates/apps/src/lib/cli/client.rs:188

**Comment by opsecx** [comment]
https://github.com/anoma/namada/issues/2907

**Comment by opsecx** [comment]
https://github.com/anoma/namada/issues/2872

**Comment by opsecx** [comment]
https://github.com/anoma/namada/issues/2900

**Comment by opsecx** [comment]
Feel like I missed some related issue, feel free to add.

**Comment by opsecx** [comment]
Confirm this is still an issue post fork (v32.1)

**Comment by ChiccoHakk** [comment]
A similar problem often occurs when trying to vote. I noticed that this always happens at times when namadan starts to consume a lot of resources for some reason.
![image](https://github.com/anoma/namada/assets/125027618/bbb8ebde-52fe-41b8-9beb-cc3914b6bba9)
Log:
Error: 
0: Encountered error while broadcasting transaction: 
 0:    HTTP error
 0:    1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed
0:    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs
1: Encountered error while broadcasting transaction: 
1:    0: HTTP error
1:    1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed
1:    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs

**Comment by opsecx** [comment]
> A similar problem often occurs when trying to vote. I confirm - this is still an issue post fork (v32.1). I noticed that this always happens at times when namadan starts to consume a lot of resources for some reason. ![image](https://private-user-images.githubusercontent.com/125027618/321561355-bbb8ebde-52fe-41b8-9beb-cc3914b6bba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDY4NDgsIm5iZiI6MTcxMjg0NjU0OCwicGF0aCI6Ii8xMjUwMjc2MTgvMzIxNTYxMzU1LWJiYjhlYmRlLTUyZmUtNDFiOC05YmViLWNjMzkxNGI2YmJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGI3ODBhNDZlOGZkZTI0NDU1Y2E3ZTdmM2ExYTdiNzNlYjBiNzA2ZDNmOTM1NzgxNjE1YjY5ZmVmODUwOTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FFUYS7O6eofyiRERrTZ57GoK5hZExajaoAe3LLunb6U) Log: Error: 0: Encountered error while broadcasting transaction: 0: 0: HTTP error 0: 1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed 0: Location: 0: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10 0: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it. 0: Run with RUST_BACKTRACE=full to include source snippets. 1: Encountered error while broadcasting transaction: 1: 0: HTTP error 1: 1: error sending request for url (http://127.0.0.1:26657/): connection closed before message completed 1: Location: 1: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10 1: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it. 1: Run with RUST_BACKTRACE=full to include source snippets. Location: /root/namada/crates/apps/src/lib/cli/client.rs:190 Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it. Run with RUST_BACKTRACE=full to include source snippets.

I noticed this too. See also the related issue: https://github.com/anoma/namada/issues/2950
