### ISSUE TITLE
Save block history after hardfork

### ISSUE THREAD

**Issue by nodiums** [anoma/namada#2966]
**Issue:**
Currently, when a hard fork occurs, the chain history from the RPC endpoint is erased, and the earliest height at the RPC becomes the hard fork height. This poses challenges for maintaining historical data accessible through RPC endpoints.

**Proposal:**
Introduce an optional feature where providers can decide during updates whether to retain or erase chain history from RPC endpoints after a hard fork. This would allow providers to choose whether they want to retain the historical data.

**Rationale:**
The current lack of flexibility in history retention poses a risk of completely losing chain history if all peers update without considering the need for historical data. Without this optional feature, the only workaround is to maintain multiple RPC endpoints corresponding to the number of hard forks, which necessitates balancing them via a web server.

**Benefits:**
Flexibility: Providers can tailor their RPC endpoint configurations based on their specific requirements for historical data retention.
Risk Mitigation: Minimize the risk of unintentional loss of chain history due to blanket updates across peers.
Efficiency: Avoid unnecessary duplication of RPC endpoints and streamline maintenance efforts.

**Comment by Fraccaman** [comment]
no history is being lost, by right now the namada client is not able to query for pre-hardfork data
