### ISSUE TITLE
Shielded IBC transfer is rejected since hardfork 

### ISSUE THREAD

**Issue by aquariusluo** [anoma/namada#2968]
Shielded IBC transfer is rejected by VP tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah.

namada verson: v0.32.1
hermes version: 1.7.4+38f41c6

export WALLET_PK=tpknam1qqjgef9zsd0gsyqn3af9nrgxyhapef3cjn5cyxpjcjgtq60de6502p8rf8h
namadaw find --alias $WALLET
Found transparent keys:
  Alias "staking-power" (encrypted):
    Public key hash: C148ACA7B41FEA06FEB813A7AF62763C24EE210A
    Public key: tpknam1qqjgef9zsd0gsyqn3af9nrgxyhapef3cjn5cyxpjcjgtq60de6502p8rf8h
Found transparent address:
  "staking-power": Implicit: tnam1qrq53t98ks075ph7hqf60tmzwc7zfm3ppglalp27

namadac balance --owner my-spending-key-alias
Last committed epoch: 62
converting current asset type to latest asset type...
tnam1p4cm47gnhkhggl54nnfpz793ynuejf7p2cru6sw8 : 3
naan : 25

namadac balance --owner  $WALLET
naan: 584.707602

namadac --base-dir $BASE_DIR \
    ibc-transfer \
    --amount 1 \
    --token naan \
    --source my-spending-key-alias \
    --receiver osmo1z6m8ndunsc6kxyyjh0y2yr48s9lufv9caqe033 \
    --gas-payer $WALLET \
    --channel-id channel-1129 \
    --memo $WALLET_PK
Enter your decryption password: 
converting current asset type to latest asset type...
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 47FB42E7512F33DB21D41431761053F1950011F899F4FC3DA91F56C81D798FD3
Inner transaction hash: 2A75A27AA0E58BA8001643F3087C7A6F7164892302C385382AFB94E26F323C58
Wrapper transaction accepted at height 242858. Used 120 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah"
].
Changed keys: [
  "#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/commitment_tree",
  "#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/nullifiers/5906AA33E54A35066A9473A0797C2FF01DA6B5590232A5C4035023E2DC18AD3C",
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah",
  "#tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee/balance/#tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4",
  "#tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4/commitments/ports/transfer/channels/channel-1129/sequences/7",
  "#tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4/nextSequenceSend/ports/transfer/channels/channel-1129"
]

**Comment by monleru** [comment]
#2967

**Comment by aquariusluo** [comment]
namadac transfer is normal after shielded-sync.

**Comment by monleru** [comment]
> namadac transfer is normal after shielded-sync.

Both actions don't work 

If you were able to send shielded transfer(from shielded) show the transaction tx

**Comment by aquariusluo** [comment]
> > namadac transfer is normal after shielded-sync.
> 
> Both actions don't work
> 
> If you were able to send shielded transfer(from shielded) show the tx hash

Shielding transfer was rejected. Only shielded transfer is good.

**Comment by Michel-Leidson** [comment]
> > namadac transfer is normal after shielded-sync.
> 
> Both actions don't work
> 
> If you were able to send shielded transfer(from shielded) show the tx hash

Done some transactions and it worked normally for me.
Wrapper transaction hash: F1FE6A0895919E33D6FA9D83CD318CE1BD4C5E39923F76D60A4E8B66B2D4BD6F
Inner transaction hash: 13E1BC3EBD98B10F1E8917D9A9DAEA2A64DB0DCD0E5F534B8404AE95E4845080

**Comment by phy-chain** [comment]
Lets group discussion in one place : https://github.com/anoma/namada/issues/2967
