### ISSUE TITLE
RPC can't access blocks pre hard fork

### ISSUE THREAD

**Issue by WayneWayner** [anoma/namada#2969]
### Finding
After the hard fork the rpc node can't access blocks 1-237906. 

```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "height 1 is not available, lowest height is 237907"
  }
}
```
### Issue:
This forces applications and services to change their codebase and run more infrastructure. This might be intended but is also a weak solution. 

### Solution:
Better would be if a single namada rpc node could handle pre and post hardfork requests. Alternatively some namada proxy rpc software which has some internal routing to the correct RPC node ( pre or post fork) would be a workaround to avoid changing codebase of many applications and services.

**Comment by opsecx** [comment]
Second this.

**Comment by brentstone** [comment]
This has been well known, and a warning was given about this in the hard fork communications and instructions. We are working on a n appropriate solution for mainnet.
