### ISSUE TITLE
Shielded sync (panic crashed)

### ISSUE THREAD

**Issue by banananas1vb** [anoma/namada#2970]
What I did:
**1. Created a new shielded address:**
```
namada wallet gen --shielded --alias my-account-shielded3
namada wallet gen-payment-addr --key my-account-shielded3 --alias my-account-shielded-addr3
```
**2. Sent NAAN to my-account-shielded-addr3**
```
namada client transfer --source my-account --target my-account-shielded-addr3 --token NAAN  --node  https://namada-shielded-expedition-rpc.denodes.xyz/ --amount 15
Enter your decryption password:
Transaction added to mempool.
Wrapper transaction hash: 98F4966DC540FB3B47B14D3DCEF3BEBE9DCA038DA728F7D44CA76FCA79FA7EBC
Inner transaction hash: 93250C8D557513AEEEFDBA236A4FE64024D0BFC964D5579B5A1BEDDA190537EC
Wrapper transaction accepted at height 245584. Used 47 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 245585. Used 10160 gas.
```

**3. Start shielded-sync:** (Fethed block went well, when start Scaning it's crashed)
```
namadac shielded-sync --from-height=237907 --node https://rpc-namada.kintsugi-nodes.com
==== Shielded sync started ====


Scanning 1 of 1359
[....................................................................................................] ~~ 0 %The application panicked (crashed).
Message:  no entry found for key
Location: /root/namada/crates/sdk/src/masp.rs:1040

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by jipan76** [comment]
how to solve this?

**Comment by Zipporol** [comment]
> how to solve this?
In the chat today Hades said that it needs to be deleted `shielded.dat`. It is located: `.local/shared/namada/shielded.dat`  And start synchronization again. But I’m not sure if it will help, I haven’t tried this method myself, I didn’t have any problems with synchronization. But I wonder why this failure occurs.

**Comment by Zipporol** [comment]
> how to solve this?

In the chat today Hades said that it needs to be deleted `shielded.dat`. It is located:` .local/shared/namada/shielded.dat` And start synchronization again. But I’m not sure if it will help, I haven’t tried this method myself, I didn’t have any problems with synchronization. But I wonder why this failure occurs.

**Comment by cwgoes** [comment]
Should since be fixed.
