### ISSUE TITLE
client vote-proposal

### ISSUE THREAD

**Issue by AlliWarrior** [anoma/namada#2974]
root@AliWarrior:~# namada client vote-proposal   --vote yay   --address tnam1qz4n02vmv7jy8kv60pwn30f2upvqdp4ux5s0dp8n   --proposal-id 480   --signing-keys my-account   --gas-limit 7900   --memo tpknam1qrprpvtyd8kncg72m6hwe4wv6rjj3kee56tffp7gqw02wv60vrk5q4sxgxp   --node https://namada-rpc.rpc-node.xyz
Enter your decryption password:
Transaction added to mempool.
Wrapper transaction hash: 38961BCE684414871B14FFB67F05989F682FE2687D755548A220441F90645A60
Inner transaction hash: 161D61615EBB5DEDB7C12A4CD9655863A2A8F23E3E607466BAA2C5E7D7043B89
Wrapper transaction accepted at height 259322. Used 23 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6"
].
Changed keys: [
  "#tnam1q5qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrw33g6/proposal/480/vote/#tnam1qyswgrrzk3yjsekwgyl4zecwfyw0hc59s5lh9aa6/#tnam1qz4n02vmv7jy8kv60pwn30f2upvqdp4ux5s0dp8n"
]

**Comment by brentstone** [comment]
You have not provided enough information to properly debug your failed tx. For example, we do not know which epoch you voted in, if your address is a validator, what `my-account` is, etc.
