### ISSUE TITLE
Can't withdraw unbonded tokens after the fork

### ISSUE THREAD

**Issue by aamironov** [anoma/namada#2976]
I was trying to withdraw tokens that were unbonded long time ago, but I am getting error "There are no unbonded bonds ready to withdraw in the current epoch 68.".

Query for bonds:
```root@n8ac0f9:~# namadac bonds --owner tnam1qrzhc7yv9t9a3q8a5tf9f7v9szzv2gm6q58cz602
Last committed epoch: 68
Delegations from tnam1qrzhc7yv9t9a3q8a5tf9f7v9szzv2gm6q58cz602 to tnam1q9rl4e2vxyx6zr2yp3p87uqqyangeljy0s9lu04a:
  Remaining active bond from epoch 5: Δ 495.000000 (slashed 0.000000)
Active (slashable) bonds total: 495.000000
Bonds total: 495.000000

**Unbonded delegations from tnam1qrzhc7yv9t9a3q8a5tf9f7v9szzv2gm6q58cz602:
  Withdrawable from epoch 10 (active from 5): Δ 5.000000 (slashed 0.000000)
Unbonded total: 5.000000
Withdrawable total: 5.000000**

Delegations from tnam1qrzhc7yv9t9a3q8a5tf9f7v9szzv2gm6q58cz602 to tnam1qxr3ajdtxnyld3tlj04wdvxzdjj6x20jl5n5r03d:
  Remaining active bond from epoch 5: Δ 15000.000000 (slashed 0.000000)
Active (slashable) bonds total: 15000.000000
Bonds total: 15000.000000

Withdrawable total: 0.000000

All bonds total active: 15495.000000
All bonds total: 15495.000000
All bonds total slashed: 0.000000
All unbonds total active: 5.000000
All unbonds total: 5.000000
All unbonds total withdrawable: 5.000000
All unbonds total slashed: 0.000000
```

Trying to withdraw tokens:
```root@n8ac0f9:~# namadac withdraw --validator tnam1q9rl4e2vxyx6zr2yp3p87uqqyangeljy0s9lu04a
Looking-up public key of tnam1q9rl4e2vxyx6zr2yp3p87uqqyangeljy0s9lu04a from the ledger...
There are no unbonded bonds ready to withdraw in the current epoch 68.
Error:
   0: There are no unbonded bonds ready to withdraw in the current epoch 68.
   1: There are no unbonded bonds ready to withdraw in the current epoch 68.

Location:
   /root/namada/crates/apps/src/lib/cli/client.rs:238

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by Zipporol** [comment]
Perhaps the RPC is not completely synchronized. Try adding the --node flag to the unbond command and try different RCPs. For example: --node https://namada-se100-rpc.gatadao.com

**Comment by brentstone** [comment]
It would be very helpful if you also provided the commands that you ran that produced these outputs.

Regardless, I think your issue may be that you did not execute the proper withdraw command. You must provide both the source and validator addresses to the withdraw command for all bonds that are not self-bonds. Please try `namadac withdraw --source <source-address> --validator <validator-address>`.

I'm guessing you may have just done `namadac withdraw --validator tnam1q9rl4e2vxyx6zr2yp3p87uqqyangeljy0s9lu04a` or similar, and from your first bonds query output, you can see that there are no self-bonds, i.e. a bond from `tnam1q9rl4e2vxyx6zr2yp3p87uqqyangeljy0s9lu04a` to `tnam1q9rl4e2vxyx6zr2yp3p87uqqyangeljy0s9lu04a`.

**Comment by brentstone** [comment]
Will close now, but please feel free to continue discussion here and ask any questions.
