### ISSUE TITLE
Vote failed after unjail

### ISSUE THREAD

**Issue by cosmowiz** [anoma/namada#2977]
Validator wasn't able to unjail before hardfork
Validator: tnam1q9mqwk6qmgq6rrxycpwr0qpvfn4w56ymdcet22r6

After hardfork unjail took place and I attempt to vote on any proposal:

`namadac vote-proposal --proposal-id 485 --vote yay --address tnam1q9mqwk6qmgq6rrxycpwr0qpvfn4w56ymdcet22r6   --signing-keys cosmowizval`
where
`cosmowizval = tnam1qq9l6feczdscfwdxasddccvr46auz0acfc0r5r96`
But as I see signing-keys are not important

```
Error:
Error: 
   0: Voter address must have delegations

Location:
   /root/namada/crates/apps/src/lib/cli/client.rs:190
```
   While

`namadac bonded-stake --validator tnam1q9mqwk6qmgq6rrxycpwr0qpvfn4w56ymdcet22r6`
```
Last committed epoch: 68
Bonded stake of validator tnam1q9mqwk6qmgq6rrxycpwr0qpvfn4w56ymdcet22r6: 31266.000000
Total bonded stake: 263869130.324318
```
<img width="1573" alt="screenshot" src="https://github.com/anoma/namada/assets/82639358/0e63053c-a2dd-4ba5-9244-56f7b273fc50">

**Comment by opsecx** [comment]
Interesting. Out of curiosity, what happens if you drop the signing-keys param?

**Comment by opsecx** [comment]
Your validator address doesn't have any self-bonds: namadac bonds --owner tnam1q9mqwk6qmgq6rrxycpwr0qpvfn4w56ymdcet22r6
Last committed epoch: 70
All bonds total: 0.000000
All bonds total slashed: 0.000000
All unbonds total: 0.000000
All unbonds total withdrawable: 0.000000
All unbonds total slashed: 0.000000

So this behavior is as expected. You should probably vote with your implicit address if that's where you bonded from. Recommend closing this issue

**Comment by cosmowiz** [comment]
> Your validator address doesn't have any self-bonds: namadac bonds --owner tnam1q9mqwk6qmgq6rrxycpwr0qpvfn4w56ymdcet22r6 Last committed epoch: 70 All bonds total: 0.000000 All bonds total slashed: 0.000000 All unbonds total: 0.000000 All unbonds total withdrawable: 0.000000 All unbonds total slashed: 0.000000
> 
> So this behavior is as expected. You should probably vote with your implicit address if that's where you bonded from. Recommend closing this issue

they how i vote with VP that was delegated to me?

**Comment by opsecx** [comment]
> > Your validator address doesn't have any self-bonds: namadac bonds --owner tnam1q9mqwk6qmgq6rrxycpwr0qpvfn4w56ymdcet22r6 Last committed epoch: 70 All bonds total: 0.000000 All bonds total slashed: 0.000000 All unbonds total: 0.000000 All unbonds total withdrawable: 0.000000 All unbonds total slashed: 0.000000
> 
> > 
> 
> > So this behavior is as expected. You should probably vote with your implicit address if that's where you bonded from. Recommend closing this issue
> 
> 
> 
> they how i vote with VP that was delegated to me?

My understanding is the wallet who bonded to your validator still controls the votes.

**Comment by opsecx** [comment]
can't say I'm 100% on that
