### ISSUE TITLE
Add E2E Test for show-transfers

### ISSUE THREAD

**Issue by murisi** [anoma/namada#300]
The `anomac show-transfers` command displays all accepted transfers on the ledger involving the keys in the wallet. Make an E2E test for this functionality in order to prevent future regressions. The following are some variations to test:
* Historical MASP transactions
* Historical transparent transactions
* Applying no transaction filter
* Filtering by transaction address owners
* Filtering by transaction token
* In ABCI and ABCI++ mode

**Comment by cwgoes** [comment]
@mariari can you check if we have this already or not? (not urgent)
