### ISSUE TITLE
IBC-transfers do not reach the recipient

### ISSUE THREAD

**Issue by TerzoMillenio** [anoma/namada#3007]
I've sent IBC-transfer to my osmosis address

root@root:~# namadac ibc-transfer --receiver osmo16h4gj7yqef90452hlwen3lpyl9nup46xhychg5 --source a --token NAAN --amount 1 --memo $MEMO --channel-id channel-995
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 32F755E3430DC301573F2C4AE061405FB06661D4CDECEF05BA013DB4F2597731
Inner transaction hash: 3C9C8FC33A9008ED5A011674499E66E896E05DF71979EFDEF1F47D072C82555A
Wrapper transaction accepted at height 301871. Used 26 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 301872. Used 6193 gas.

As you can see, transaction was successfully applied, but there's no transactions on mintscan
https://www.mintscan.io/osmosis-testnet/address/osmo16h4gj7yqef90452hlwen3lpyl9nup46xhychg5

I've tried other channels and the result is the same

**Comment by yito88** [comment]
@TerzoMillenio Thank you.
Could you try `--memo-path` to set the memo with the file path to the ICS-20 packet?
`--memo` is for the Namada tx's memo field, not for IBC transfer.

**Comment by yito88** [comment]
From Namada side, the sending succeeded. Do you know any idea about Hermes for the channel `channel-995`?

**Comment by TerzoMillenio** [comment]
I created a channel to theta-testnet-001 also. Doesn't work either. We have transactions going out from Namada, but never reaching the recipient on target chain. This is the target address we set in the command: https://www.mintscan.io/cosmoshub-testnet/address/cosmos1f9d03fen0hqfwp6lctyrrvpnx86ptjcpcwnrv0. Relayer cosmos address: https://www.mintscan.io/cosmoshub-testnet/address/cosmos13lmtw0rkldz84q6e9gxd77snl02rawew4lx226. Transaction on Namada: https://testnet-explorer.madakimi.mobi/transactions/F3E054A6DD0FEA5CE39C6CB7B6B8CE055FD7F7AFC09D396D9AB18645808D9200. However, the inner transaction on this explorer shows error status, even though the CLI shows this:
Transaction added to mempool.
Wrapper transaction hash: F3E054A6DD0FEA5CE39C6CB7B6B8CE055FD7F7AFC09D396D9AB18645808D9200
Inner transaction hash: 1947A2C47CFDB02F550D2884AA7BF9D7F938BC9A5F1D7592EC4415518215842B
Wrapper transaction accepted at height 390593. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 390594. Used 6193 gas.

**Comment by yito88** [comment]
@TerzoMillenio Thank you. Could you share the logs of Hermes(relayer) for the channel?

**Comment by TerzoMillenio** [comment]
> @TerzoMillenio Thank you. Could you share the logs of Hermes(relayer) for the channel?

What kind of log?

**Comment by TerzoMillenio** [comment]
![photo_2024-04-17_02-11-32](https://github.com/anoma/namada/assets/117123314/4758ff7a-0546-4832-a017-f4c1b7e21199)

**Comment by TerzoMillenio** [comment]
I made another channel, logs are clear


![photo_2024-04-17_02-28-01](https://github.com/anoma/namada/assets/117123314/c06f6fb7-07c0-4258-acd8-29b4ec224c12)
![photo_2024-04-17_02-28-09](https://github.com/anoma/namada/assets/117123314/353ac488-60dd-4c9e-9363-1d5df7dc3d81)

tx from namada sent successfully, but still doesn't reach destination 
namadac ibc-transfer --source a --receiver cosmos1f9d03fen0hqfwp6lctyrrvpnx86ptjcpcwnrv0 --token NAAN --amount 50 --channel-id channel-1333
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 9423F387B45A0660D04A7DF7290378BFEA77C8BCB2CD8E706D0FDF18F21B3866
Inner transaction hash: 5C28E82343AB6B2D694B075B213B76352081270DE73E4E19CEEA9E02CF7E0788
Wrapper transaction accepted at height 399268. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 399269. Used 6193 gas.

Same result using RPC

namadac ibc-transfer --source a --receiver cosmos1f9d03fen0hqfwp6lctyrrvpnx86ptjcpcwnrv0 --token NAAN --amount 50 --channel-id channel-1333 --node https://namada-testnet-rpc.itrocket.net:443
Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: DF8DD8E294E143E5E6A5D351EA30B8CA75645CB10D981567A38E522D14730D91
Inner transaction hash: 863133229744DFF54DFC3125FA39481CF940DBA467E8A0BF3E8C3006D02EAC15
Wrapper transaction accepted at height 399282. Used 24 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 399283. Used 6193 gas.


https://www.mintscan.io/cosmoshub-testnet/address/cosmos1f9d03fen0hqfwp6lctyrrvpnx86ptjcpcwnrv0

there are enought NAAN and ATOM on relayer's wallets

**Comment by yito88** [comment]
@TerzoMillenio I'd like to see the logs of `hermes start` that should relay IBC packets.

**Comment by TerzoMillenio** [comment]
> @TerzoMillenio I'd like to see the logs of `hermes start` that should relay IBC packets.

[hermes.log](https://github.com/anoma/namada/files/15021793/hermes.log)

**Comment by McDaan** [comment]
> > @TerzoMillenio I'd like to see the logs of `hermes start` that should relay IBC packets.
> 
> [hermes.log](https://github.com/anoma/namada/files/15021793/hermes.log)

@TerzoMillenio You have not established the filter packets config nor the

**Comment by cwgoes** [comment]
No action appears to be necessary here - please reopen if otherwise.
