### ISSUE TITLE
Init Validator transaction got rejected

### ISSUE THREAD

**Issue by the-laziest** [anoma/namada#3008]
Tried to run init-validator command and every time it was rejected.
Tried to sign it with different accounts, even new one.

Command:
`namadac init-validator --threshold 1 --email testvalidator@gmail.com --commission-rate 0.1 --max-commission-rate-change 0.1 --signing-keys $ALIAS --memo $MEMO --node $NODE --unsafe-dont-encrypt`

Result:

Transaction added to mempool.
Wrapper transaction hash: F1CE848F92CF3ED4F6C239ABCED2103BB42F12886E11F8F07D41B4DDD4D057BD
Inner transaction hash: 0D663F0EA052446B6560363BCC6CF822B98F029E9AF196ECFBDA5F32348A3A63
Wrapper transaction accepted at height 304622. Used 22 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 304623. Used 3147 gas.
The transaction initialized 1 new account
Choose an alias for tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp: testing
Added alias testing for address tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp.
Generating consensus key...
Warning: The keypair will NOT be encrypted.
Generating Eth cold key...
Warning: The keypair will NOT be encrypted.
Generating Eth hot key...
Warning: The keypair will NOT be encrypted.
Generating protocol signing key...
Storing protocol key in the wallet...
Warning: The keypair will NOT be encrypted.
Transaction added to mempool.
Wrapper transaction hash: 26CA097889781240C5D7B20C8F6B1493D65D6098621CAA7A9A4CE0484D16DF99
Inner transaction hash: 725E3409A2F545C8C58B28D6F93184214DA6F3081399CEB086AD689816816236
Wrapper transaction accepted at height 304624. Used 35 gas.
Waiting for inner transaction result...
Transaction was rejected by VPs: [
  "tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp"
].
Changed keys: [
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/address_raw_hash/7FA107FFD89B5EAF4F3B415963BDBFA7C076EDB4",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/consensus_keys/tpknam1qz4qz3y5g5rnp2ghjw29ce9ensgla8k2rws567e65llt3ytddpwfkmw2xn4",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/commission_rate/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/commission_rate/lazy_map/data/000000000004U",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/commission_rate/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/consensus_key/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/consensus_key/lazy_map/data/000000000004U",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/consensus_key/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/deltas/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/deltas/lazy_map/data/000000000004U",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/deltas/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/email",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/eth_cold_key/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/eth_cold_key/lazy_map/data/000000000004U",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/eth_cold_key/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/eth_hot_key/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/eth_hot_key/lazy_map/data/000000000004U",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/eth_hot_key/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/max_commission_rate_change",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/state/last_update",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/state/lazy_map/data/000000000004U",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/state/oldest_epoch",
  "#tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp/validator_addresses/lazy_map/data/000000000004U/#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp",
  "#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/protocol_public_keys/last_update",
  "#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/protocol_public_keys/lazy_map/data/000000000004U",
  "#tnam1qxg69aq3tmgvg4xhm7aa7k3kr5588xwvvsq43fmp/protocol_public_keys/oldest_epoch"
]

**Comment by cwgoes** [comment]
This should be fixed - thank you for the report.
