### ISSUE TITLE
ABCI++ Transaction History

### ISSUE THREAD

**Issue by murisi** [anoma/namada#301]
The `anomac show-transfers` subcommand fully worked on the MASP client branch before the rebase. Now that the rebase is complete, the ABCI++ mode functionality to print historical transparent transfers does not work. More specifically, the following error is produced:
```
2022-08-09T09:21:00.388114Z  INFO namada_apps::cli::context: Chain ID: namada-masp-0.2.b2311cf35ca1be
The application panicked (crashed).
Message:  Unable to query for transactions: 
   0: response error
   1: Internal error: transaction searching is disabled due to no kvEventSink (code: -32603)

Location:
   .../.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Location: .../namada/apps/src/lib/client/rpc.rs:208
```
This is probably due to changes to the Tendermint configuration (in Anoma) in the intervening time (see: https://docs.tendermint.com/master/nodes/configuration.html#indexing-settings ). Possible solutions include re-enabling the KV indexer, or disabling the transparent transaction search at line 208 (shielded transaction history printing should still continue functioning if this were done).

If this bug is fixed without disabling the search but transparent transaction histories still always show up blank in ABCI++ mode, then the relevant transaction events are likely not being lodged. This would probably be due to breaking changes in Tendermint's methods and event creation API that affect this subcommand's execution in ABCI++ mode.

One way to address this potential latter issue might be to somehow alter the `FinalizeBlock` method in `apps/src/lib/node/ledger/shims/abcipp_shim.rs` to attach events to each submitted transaction. See: https://github.com/tendermint/tendermint/blob/2b5329ae47a092941c18b3663ebedf0d387abce7/spec/abci%2B%2B/abci%2B%2B_basic_concepts.md#events

**Comment by cwgoes** [comment]
No longer applicable (thanks for the additional report though :) )
