### ISSUE TITLE
Failure of the transaction in the mempool. 

### ISSUE THREAD

**Issue by Michel-Leidson** [anoma/namada#3012]
During the execution of the command:

_namada client transfer --source tnam1qpq57evekd7gaf56pltrh52pv9rzzrygas704ykx --target znam1qqf53pj3tvnw3gctup5gstgj76m3alr23chxgl7sw57gn45n3cl6lhpultk8rdkdvr4r4fq4h5ev5 --token naan --amount 1 --gas-payer wallet-testnet-1 --gas-spending-key wallet-shielded_

`Error: 
   0: Encountered error while broadcasting transaction: 
   0:    0: server error: {
        "code":12,
        "data":"",
        "log":"Mempool validation failed: Error trying to apply a transaction: Fee ushielding error: The provided unshielding tx is invalid: Some VPs rejected fee unshielding: {\n    Internal MASP: tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah,\n}",
        "hash":"14DADE2D6963A787AAC32AB5ABC22F3B1F4D2614851C0E7B11776C6B88C527E8"
    }
`
**namadac balance --owner wallet-shielded
Last committed epoch: 79
naan : 101**

There seems to be an issue related to the 'unshielding' of the gas fee, indicating that the provided unshielding transaction for the gas fee is invalid. 
The same error occurs when using disposable gas payer to pay transaction fees.

**Comment by Rigorously** [comment]
Unshielding is broken since the hard fork, along with other shielded transactions:
https://github.com/anoma/namada/issues/2967
