### ISSUE TITLE
Need CometBFT RPC access to pre-hard fork block heights

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#3013]
With the existing migration infrastructure, after a hard fork, we cannot make RPC calls to CometBFT to query blocks before a hard fork, as experienced with `shielded-sync` in the SE.

**Comment by batconjurer** [comment]
So hardforking actually deletes all cometbft data prior to the hardfork.

**Comment by brentstone** [comment]
Do we know exactly how chains like Cosmos hard-fork then and what they do or don't lose upon doing so?

**Comment by batconjurer** [comment]
I think we have to accept that we will need full nodes on old chains
