### ISSUE TITLE
Refactor `namadac balance`

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#3014]
- [x] Require the `owner` argument, as the current impl without this arg provided tries to loop over the balances of all accounts, which is way too intensive and should not be allowed
- [ ] MASP strategy is too intensive and should be changed
  - #2900
- [x] Non-native (IBC) token strategy is also too intensive, should not be scanning over all tokens in the chain for balances.

Previous related issues:
- #2887 
- #2809
- #2666

**Comment by brentstone** [comment]
@Fraccaman @cwgoes I think this should probably be a Phase 1 priority, what do you think?

**Comment by danhnguyen1-tiki** [comment]
This maybe duplicated with #2887.

**Comment by cwgoes** [comment]
Decisions 2024.04.24:
- Require `--owner` always (which will be a transparent or shielded address)
     - Implies shielded/transparent 
- Require `--token` always
- Clean up / clarify error messages
- Clarify in the description what the command does and does not do
    - Does not scan all tokens
