### ISSUE TITLE
namadac balance --owner $Shielded-aadress keeps printing  "Converting Current Asset Type to Latest Asset Type"  After Namada Hard Fork

### ISSUE THREAD

**Issue by zaki9501** [anoma/namada#3019]
Description:
After the recent Namada hard fork, users are experiencing an issue with the namadac balance command. When attempting to check the shielded balance using this command, instead of displaying the shielded asset value, the command continuously prints the message "converting current asset type to latest asset type..." without providing the expected output. It is unclear whether this behavior is due to a bug or a glitch, but the command should provide the expected output as it did before the Namada hard fork.

Steps to Reproduce:

Execute the command namadac balance --owner $address to check the shielded balance, where $address is the address for which the balance is being queried.
Observe the output of the command, which continuously prints the message "converting current asset type to latest asset type..." without displaying the shielded asset value.
Expected Behavior:
The namadac balance command should accurately retrieve and display the shielded balance associated with the specified address, as it did before the Namada hard fork.

Actual Behavior:
Instead of displaying the shielded asset value, the command continuously prints the message "converting current asset type to latest asset type..." without providing the expected output.

Additional Information:

This issue started occurring after the recent Namada hard fork.
Users have reported encountering this issue consistently.
The problem seems to be specific to the retrieval and processing of shielded balance data.
The issue persists even after updating to the latest version of the Namada software.
Workaround:
As a workaround, users can try alternative methods to retrieve shielded balance data or consult community forums for potential solutions.

Impact:
This issue affects users who rely on the namadac balance command to check their shielded asset balances, potentially causing inconvenience and hindering their ability to monitor their assets accurately.

Next Steps:

Investigate the root cause of the issue, particularly any changes introduced during the Namada hard fork that may have impacted the namadac balance command.
Develop and implement a fix to address the issue and restore the expected behavior of the command.
Test the fix thoroughly to ensure that it resolves the issue without introducing any regressions.
Release the fix as part of a software update to provide users with a solution to the problem.
**version** v0.32.1
**Attachments:**
namadac balance --owner zvknam1qw0ufd22qqqqpqqn5pp03dkflh6w7m3rh8ut6mk9jefw2fy86v0hnphljl0n82t7x84hw02tumqeeqsa688rzw63f0cel739d6g2gy9g0gfrl2spcepv6yzyp0sllrajefj56nse0p60vdqut07m9qcvrj2gfza8pfrz3fxx4c6yd33swl3aqntn7d7x4jn7phth6mx03gfjkywhu07yxyex03wsfvmfn76356lc3pe594kku6x78apklmf5a0dwust9usx8fweng4s08hwmu
Last committed epoch: 80
converting current asset type to latest asset type...
converting current asset type to latest asset type...
converting current asset type to latest asset type...
converting current asset type to latest asset type...
converting current asset type to latest asset type...
converting current asset type to latest asset type...
converting current asset type to latest asset type...
converting current asset type to latest asset type...

**Comment by zaki9501** [comment]
> Description: After the recent Namada hard fork, users are experiencing an issue with the namadac balance command. When attempting to check the shielded balance using this command, instead of displaying the shielded asset value, the command continuously prints the message "converting current asset type to latest asset type..." without providing the expected output. It is unclear whether this behavior is due to a bug or a glitch, but the command should provide the expected output as it did before the Namada hard fork.
> 
> Steps to Reproduce:
> 
> Execute the command namadac balance --owner $address to check the shielded balance, where $address is the address for which the balance is being queried. Observe the output of the command, which continuously prints the message "converting current asset type to latest asset type..." without displaying the shielded asset value. Expected Behavior: The namadac balance command should accurately retrieve and display the shielded balance associated with the specified address, as it did before the Namada hard fork.
> 
> Actual Behavior: Instead of displaying the shielded asset value, the command continuously prints the message "converting current asset type to latest asset type..." without providing the expected output.
> 
> Additional Information:
> 
> This issue started occurring after the recent Namada hard fork. Users have reported encountering this issue consistently. The problem seems to be specific to the retrieval and processing of shielded balance data. The issue persists even after updating to the latest version of the Namada software. Workaround: As a workaround, users can try alternative methods to retrieve shielded balance data or consult community forums for potential solutions.
> 
> Impact: This issue affects users who rely on the namadac balance command to check their shielded asset balances, potentially causing inconvenience and hindering their ability to monitor their assets accurately.
> 
> Next Steps:
> 
> Investigate the root cause of the issue, particularly any changes introduced during the Namada hard fork that may have impacted the namadac balance command. Develop and implement a fix to address the issue and restore the expected behavior of the command. Test the fix thoroughly to ensure that it resolves the issue without introducing any regressions. Release the fix as part of a software update to provide users with a solution to the problem. **version** v0.32.1 **Attachments:** namadac balance --owner zvknam1qw0ufd22qqqqpqqn5pp03dkflh6w7m3rh8ut6mk9jefw2fy86v0hnphljl0n82t7x84hw02tumqeeqsa688rzw63f0cel739d6g2gy9g0gfrl2spcepv6yzyp0sllrajefj56nse0p60vdqut07m9qcvrj2gfza8pfrz3fxx4c6yd33swl3aqntn7d7x4jn7phth6mx03gfjkywhu07yxyex03wsfvmfn76356lc3pe594kku6x78apklmf5a0dwust9usx8fweng4s08hwmu Last committed epoch: 80 converting current asset type to latest asset type... converting current asset type to latest asset type... converting current asset type to latest asset type... converting current asset type to latest asset type... converting current asset type to latest asset type... converting current asset type to latest asset type... converting current asset type to latest asset type... converting current asset type to latest asset type...

![Screenshot (175)](https://github.com/anoma/namada/assets/80619916/8f3a39ca-d771-4266-9148-d2d14ff456bf)
tried with spending key alisa too but same output

**Comment by Rigorously** [comment]
Try adding ` --no-conversions`

**Comment by zaki9501** [comment]
> Try adding ` --no-conversions`
> 
> You might then get something like `tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee | 2 : 2.3`

Last committed epoch: 83
tnam1p45l2n0tvd7nyvl75zl53a3w35s9qt8u8s4y5cmr : 5200000
tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee : 200000
tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee | 45 : 69
tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee | 49 : 60
tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee | 53 : 40

**Comment by cwgoes** [comment]
The balance command has been reworked; this should be fixed. Thank you for the reports.
