### ISSUE TITLE
namadac commission-rate failing

### ISSUE THREAD

**Issue by honeygoyal120** [anoma/namada#3022]
## Trying to change the commission-rate of validator says the address is not a validator
```root@vmi1485351:~# namadac commission-rate --validator 1```
### Output:
Address tnam1qy58exql4j3wytpfstyvj76umxd8avzq3qlxn2vm is not a validator (did not find commission rate and max change)

## While the become-validator command says that the address is already a validator

```root@vmi1485351:~# namada client become-validator --address 1 --signing-keys phoenixv110 --commission-rate 1 --max-commission-rate-change 1 --email bhola@gmail.com --memo tpknam1qq78mp640t445hjju35sz8kjhs2c9wc05jxuelx6e28kq4xunepfjdc8kcd --node https://namada.makingmemories.xyz```
### Output:
The given address tnam1qy58exql4j3wytpfstyvj76umxd8avzq3qlxn2vm is already a validator

**Comment by brentstone** [comment]
Hmm. first why are you passing `1` as the `--validator` arg? Did you ever initialize this address `tnam1qy58exql4j3wytpfstyvj76umxd8avzq3qlxn2vm` as a validator before as well?

**Comment by brentstone** [comment]
Can you try bonding to it and/or giving it some tokens?

**Comment by brentstone** [comment]
Ok I see what is going on here. You initialized your validator in epoch 84, and the SE is currently at epoch 85. Your validator account will only become active at the pipeline epoch relative to when you initialized it (2 epochs later), so at epoch 86. In this current epoch, your address is not yet a validator account. However, passing `--epoch 86` to some commands will give you the information you desire. For example,

```
namadac commission-rate --validator tnam1q9a5venpywpv6ahpzsqf6khxur543frw6syds0s3 --epoch 86 --node $MYNODE                
Validator tnam1q9a5venpywpv6ahpzsqf6khxur543frw6syds0s3 commission rate: 0.05, max change per epoch: 0.01
```

```
namadac validator-state --validator tnam1q9a5venpywpv6ahpzsqf6khxur543frw6syds0s3 --epoch 86 --node $MYNODE
Validator tnam1q9a5venpywpv6ahpzsqf6khxur543frw6syds0s3 is in the below-capacity set
```

**Comment by brentstone** [comment]
Btw, `namadac commission-rate` is used to just query the commission info. If you want to change it, you need to use `namadac change-commission-rate`
