### ISSUE TITLE
osmosisd doesn't support memo field for shielded ibc-transfer

### ISSUE THREAD

**Issue by givingmittal** [anoma/namada#3038]
## Cosmos binary gaiad supports --memo in the command as below:
``` memo=$(cat ${memo_path})
gaiad tx ibc-transfer transfer \
  ${CHANNEL_ID} \
  ${RECEIVER_PAYMENT_ADDRESS} \
  ${AMOUNT}${IBC_TOKEN_ADDRESS} \
  --from ${COSMOS_ALIAS} \
  --memo ${memo} \
  --node ${COSMOS_RPC_ENDPOINT} \
  --fees 5000uatom 
```
  
## But in case of Osmosis ibc --memo is not supported by osmosisd binary. There should be an alternative to provide the output generated by the below command to osmosis ibc.
```
namadac --base-dir ${BASE_DIR_B} ibc-gen-shielded \
  --output-folder-path ${OUTPUT_PATH} \
  --target ${payment_addr_b} \
  --token apfel \
  --amount 100 \
  --port-id transfer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDRESS_B}
```

**Comment by yito88** [comment]
@givingmittal I tried `osmosisd tx ibc-transfer transfer` with `--memo` option and the shielding IBC transfer worked well. What error did you get?

Here is a part of my script. `${COSMOS_CMD}` can be `osmosisd`.

```
echo "~~ Generate the proof from Namada for the following transfer ~~"
resp=$(${NAMADAC} --base-dir ${NAMADA_BASE_DIR} ibc-gen-shielded \
  --output-folder-path ${NAMADA_BASE_DIR} \
  --target ${payment_addr_a} \
  --token ${COSMOS_DENOM} \
  --amount 10 \
  --port-id transfer \
  --channel-id ${namada_channel} \
  --node ${namada_rpc_addr})
memo_path=$(echo $resp | awk '{print $8}')

echo "~~ Shielding transfer 10 from Cosmos to Namada ~~"
memo=$(cat ${memo_path})
${COSMOS_CMD} tx ibc-transfer transfer \
  transfer \
  ${cosmos_channel} \
  ${payment_addr_a} \
  10${COSMOS_DENOM} \
  --from ${COSMOS_RELAYER_ACC} \
  --memo ${memo} \
  --keyring-backend test \
  -y \
  --node ${cosmos_rpc_addr} \
  --chain-id ${cosmos_chain_id} \
  --gas-prices ${COSMOS_GAS_PRICES}
```

**Comment by yito88** [comment]
Anyway, we will not use the memo field in an ICS-20 packet for a shielding IBC transfer after #2631.

**Comment by ValarDragon** [comment]
I thought the ICS 20 memo is --note, and --memo is the tx memo

**Comment by McDaan** [comment]
I can confirm that `--note` doesn't work for inputting the generated memo proof for shielding IBC transfers. It outputs that exceeds the size limit for the field.

**Comment by givingmittal** [comment]
@yito88 The osmosisd binary doesn't accept --memo file. Please try with osmosisd command once

**Comment by McDaan** [comment]
> @yito88 The osmosisd binary doesn't accept --memo file. Please try with osmosisd command once

What do you mean? It does accept it, otherwise shielding IBC transfers couldn't went through.

**Comment by yito88** [comment]
@givingmittal I tried it and IBC transfers worked. Did you mean that we couldn't give the file path to `--memo`? Namada's `--memo-path` needs a file path, but `osmosisd` (also `gaiad`) requires the content of the file as a string. If so, you have to give the content of the file, e.g. `--memo $(cat ${memo_path})`
