### ISSUE TITLE
Add E2E Tests for MASP Wallet

### ISSUE THREAD

**Issue by murisi** [anoma/namada#305]
Make E2E tests for MASP wallet functionality to prevent future regressions. It should essentially test all subcommands of `anomaw masp`. I.e. under various CLI parameters, it should test the correct functioning of:
* `namadaw masp gen-addr ...`
* `namadaw masp add ...`
* `namadaw masp gen-key ...`
* `namadaw masp list-keys ...`
* `namadaw masp list-addrs ...`
* `namadaw masp find ...`

See transparent wallet E2E tests at `tests/src/e2e/wallet_tests.rs` for guidance on how to do this.

**Comment by karbyshev** [comment]
The wallet CLI structure has been changed #2135

**Comment by brentstone** [comment]
@murisi @batconjurer @grarco @Fraccaman how relevant is this issue still?
