### ISSUE TITLE
Finding Security Vulnerabilities about PGF Fundings

### ISSUE THREAD

**Issue by tphat2616** [anoma/namada#3054]
# PGF Fundings have no upper limit and Security Vulnerabilitie with this.

Currently, I notice that there is no strict upper limit enforced when creating proposals for PGF funding. This is a rather serious issue. Please pay attention to the attached image: one proposal is rewarded up to 200 million tokens when approved. What would happen if I create a proposal with a reward of 2 billion tokens while Namada's max supply is 1 billion tokens?

<img width="1440" alt="Screenshot 2024-03-12 at 13 20 51" src="https://github.com/anoma/namada/assets/32483104/f57bc146-c3e5-4839-a2ab-dc48bfd63323">

**Comment by Fraccaman** [comment]
you can request any amount of nam via pgf but:
