### ISSUE TITLE
Space Efficient Transaction Signing

### ISSUE THREAD

**Issue by murisi** [anoma/namada#306]
Somehow reduce the sizes of transaction payloads that need to be signed without losing key information like destination addresses, amounts, and token types. Doing this is necessary to reduce the amount of data that needs to be transmitted to and processed by hardware wallets. The large `code` field inside transactions and the fact that entire transactions are embedded into `WrapperTx`s may be obstacles in achieving this. Hashing data may help in resolving this somewhat... See work in this direction at https://github.com/anoma/anoma/pull/1247 and https://github.com/anoma/anoma/pull/1237 .

**Comment by cwgoes** [comment]
@juped have we done this already?

**Comment by cwgoes** [comment]
Out-of-date.
