### ISSUE TITLE
MASP VP should support governance changes

### ISSUE THREAD

**Issue by grarco** [anoma/namada#3068]
After #2601, governance proposals are allowed to change the asset map of masp for the conversions. At the moment though, the masp vp rejects these changes. We need to update it to support proposals.

In doing so, we could also refactor the VP itself to iterate on the keys as variants of an enum `KeyType` to make it more similar to the other VPs we have.

**Comment by cwgoes** [comment]
We need to do this in phase 1 so we can test the phase transitions.

**Comment by murisi** [comment]
> @murisi do you know how long this will take? any chance you could do it quickly?

I expect this to take maybe 2 or 3 days. I'd already started on making the MASP VP more similar to other VPs. And I don't see why allowing the MASP asset map to be changed should be difficult.

**Comment by brentstone** [comment]
Any chance we could prioritize this, especially for next release? I ask because we have an e2e test `proposal_ibc_token_inflation` that is failing without this, and don't want to be in the dark about that for too long. @murisi
