### ISSUE TITLE
Resetting connection to RPC node, crashes the node. 

### ISSUE THREAD

**Issue by nick-u410** [anoma/namada#3077]
Tested on the SE chain
Version of node: Namada 0.32.1

When running a program that fetches each block from the rpc node, if you close the program mid run, it resets the connection to the RPC node which apparently crashes it. I can consistently reproduce this. 

A third party should not be able to crash my node simply due to resetting a connection, a user could bot this and take down all public RPC nodes. 

![Screenshot 2024-04-12 at 10 56 15 AM](https://github.com/anoma/namada/assets/115743920/3f8da26e-3c5f-4480-98ce-a942c3225cb4)
![Screenshot 2024-04-12 at 10 56 36 AM](https://github.com/anoma/namada/assets/115743920/6fa33660-4297-4efd-9964-c821396c14e1)

Other users in discord are also experiencing this 
https://discord.com/channels/833618405537218590/1192974425423892550/1209072443243888720
https://discord.com/channels/833618405537218590/1192974425423892550/1206927791388626945
https://discord.com/channels/833618405537218590/1186723196527980687/1186732226478624919
https://discord.com/channels/833618405537218590/996760681892290611/1186368562244358164

**Comment by Fraccaman** [comment]
This is probably a problem in tower-abci (one of our dependecy) as @sug0 was pointing out. We need to investigate. Thanks for reporting!

**Comment by brentstone** [comment]
@tzemanovic is this still relevant or have we deemed it solved in one of our latest releases somehow?

**Comment by tzemanovic** [comment]
> @tzemanovic is this still relevant or have we deemed it solved in one of our latest releases somehow?

@brentstone From my testing this should no longer be an issue since v0.33 - resetting a connection is handled gracefully and reported by CometBFT as e.g. `failed to write responses module=rpc-server err="write tcp ...: i/o timeout`.

@nick-u410 Could you please check this from your side and let us know if that's not the case?

**Comment by cwgoes** [comment]
Closing this for now, but feel free to reopen if this issue recurs.
