### ISSUE TITLE
MacOS installation instructions not working

### ISSUE THREAD

**Issue by neocybereth** [anoma/namada#3094]
Attempted to install on macOS. 

I have all dependencies listed. 

I then ran: 

```make build && make install```

And I'm getting this error as a result: 

![Screenshot 2024-04-17 at 3 53 54 PM](https://github.com/anoma/namada/assets/14209806/480c8a90-4366-4015-b2da-e04a49d2d850)

**Comment by brentstone** [comment]
What exactly are you trying to do here? If you are trying to start a local network, you can use `scripts/gen_localnet.py`. I'm assuming the `make build && make install` were successful for you based on your image.
