### ISSUE TITLE
Ensure `apply_tx` errors for unexpected transactions during `FinalizeBlock`

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#313]
For Namada, only certain types of transactions are expected to be applied during `FinalizeBlock`. They are:
- decrypted transactions
- protocol transactions

Other types of transactions (e.g. raw transactions, wrapper transactions, etc...) reaching `apply_tx` is unexpected and we should handle appropriately, rather than no-opping.

**Comment by cwgoes** [comment]
@sug0 what's the status of this w.r.t. the block space allocator work?

**Comment by sug0** [comment]
@cwgoes it should be impossible to reach FinalizeBlock with invalid tx types, namely raw txs. in fact, AFAIK, currently these serve no purpose whatsoever. as for wrapper txs in `apply_tx`, I'm not sure what is the current behavior, but as the issue states, it shouldn't change any state in storage.

**Comment by sug0** [comment]
so, wrapper txs can reach `FinalizeBlock`, but they do not perform any state updates - which is expected. as for raw transactions, we error out on those. raw transactions should be removed in the future, since they have no purpose, and are rejected by `CheckTx`. closing the issue
