### ISSUE TITLE
Error propagation issue in `EndBlock` handling

### ISSUE THREAD

**Issue by grarco** [anoma/namada#3191]
Reported by Informal Systems.

# Description

`BeginBlock` , `DeliverTx` , and `EndBlock` functions collect data and execute everything together in `EndBlock` , simulating the behavior of `FinalizeBlock` . According to the CometBFT v0.37 documentation, `EndBlock` on CometBFT does not expect any errors. However, in the code, errors are packed in the `EndBlock` response.

# Problem Scenarios

In the `finalize_block` function, errors are propagated in several places within the finalize_block function and its sub-systems (/finalize_block.rs#L105-L119, /finalize_block.rs#L123). Errors in any of these places can be propagated to `EndBlock` , contrary to the expected behavior described in the documentation.

# Recommendation

To ensure consistency with the expected behavior described in the documentation review the error-handling mechanism in the `finalize_block` function and its sub-systems. Errors should not be propagated to `EndBlock` to avoid potential crashes or disruptions in the system's operation. However, it's essential to consider the severity of the error; in some cases, an error and subsequent crash may be justified, especially when the system encounters a critical issue that cannot be safely handled.

**Comment by cwgoes** [comment]
@grarco Is this issue still applicable?

**Comment by grarco** [comment]
No it is outdated, we can close it
