### ISSUE TITLE
add ledger storage snapshots

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#32]
https://docs.tendermint.com/v0.35/spec/abci/apps.html#taking-snapshots

It would be handy to have some commands for exporting and importing snapshots

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762978708615) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Is this still relevant with the deprecation of Tendermint 0.35? What would snapshots help with, exactly?

**Comment by tzemanovic** [comment]
still relevant with CometBFT - it could be used to speed up block sync

**Comment by cwgoes** [comment]
Done as part of state sync.
