### ISSUE TITLE
add a lint to warn about `dbg_macro`

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#3227]
warn about `clippy::dbg_macro` but configure `allow-dbg-in-tests = true` (default is false)

**Comment by sug0** [comment]
might also be helpful to include lints for `println!()` and `eprintln!()`

https://rust-lang.github.io/rust-clippy/master/index.html#/print_stdout
https://rust-lang.github.io/rust-clippy/master/index.html#/print_stderr
