### ISSUE TITLE
Handle gas related errors in tx execution/validation pipeline

### ISSUE THREAD

**Issue by sug0** [anoma/namada#3238]
The PGF VP and potentially other paths in our code ignore some host function errors (eg: with `unwrap_or_default()`), which could have been gas related. This results in the (unauthorized) prolonged execution of some tx.

**Comment by grarco** [comment]
Just to add that this issue only affects native vps, as wasm codes (both txs and vps) are killed by the gust on gas errors regardless of them being cooperative or not
