### ISSUE TITLE
add conditional compilation for serde in the shared crate

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#330]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762928255101) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
this might make the wasm output a bit smaller

**Comment by cwgoes** [comment]
@murisi Can you take a look at this since it's related to the shared crate WASM work?

**Comment by murisi** [comment]
@cwgoes Sure! Will investigate this...

**Comment by cwgoes** [comment]
No longer applicable as there is no shared crate.
