### ISSUE TITLE
Replay Protect Shielded Actions

### ISSUE THREAD

**Issue by murisi** [anoma/namada#3300]
The `Transaction` object embedded inside MASP-IBC transactions only commits to the IBC internal address. This means that an attacker could potentially replay a `Transaction` object inside a different `Tx` where the specific IBC addresses have been changed. Ideally we should get the `Transaction` object to commit to specific IBC addresses instead of just the general IBC internal address.

**Comment by cwgoes** [comment]
Fixes required here:
- Include receiving IBC address in Transaction object
- Add checks in VP to check that this address is correctly authorized
