### ISSUE TITLE
Implement state sync

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#3307]
In order to quickly sync nodes, we need to enable the state sync protocol supported by Cometbft.

An initial write-up has been created [here](https://hackmd.io/xAeRQtArRom-Ti3DUMkBXg).

Tasks:
- [x] Add the ability to create chunkable snapshots to our rocksdb implementation
- [x] Spawn a background task to create snapshots are certain blockheights
- [x] Implement chunking logic for snapshots
- [x] Implement the relevant abci calls
- [x] Write logic to verify and apply chunks to a syncing node.

**Comment by brentstone** [comment]
Is this considered done or just needs #3394 until it is completed?

**Comment by batconjurer** [comment]
> Is this considered done or just needs #3394 until it is completed?

Yeah, #3394 finishes it off

**Comment by sug0** [comment]
Finished in #3701
