### ISSUE TITLE
Inconsistency between code and comment

### ISSUE THREAD

**Issue by YichiZhang0613** [anoma/namada#3364]
In namada/crates/apps_lib/src/config/genesis/transactions.rs, the comment requires that`txs.validator_accounts` must be empty but the code doesn't check it.
```rust
/// Panics if given `txs.validator_accounts` is not empty, because validator
/// transactions must be signed with a validator wallet (see
/// `init-genesis-validator` command).
pub async fn sign_txs(
    txs: UnsignedTransactions,
    wallet: &RwLock<Wallet<CliWalletUtils>>,
    validator_wallet: Option<&ValidatorWallet>,
    use_device: bool,
) -> Transactions<Unvalidated> {
```

**Comment by cwgoes** [comment]
@sug0 Could you check this quickly?

**Comment by sug0** [comment]
the comment is fine, it's just incomplete. the panic conditions are validator txs being non-empty and the passed validator wallet being `None`
