### ISSUE TITLE
Uniquely identify user txs

### ISSUE THREAD

**Issue by sug0** [anoma/namada#3403]
Currently, inner txs in a batch are only uniquely identified by the code, data and memo section hashes, but these hashes are not necessarily unique, since they may only differ by the `salt` parameter used to compute them, which is not decided by the protocol (i.e. users can control the value of `salt`).

In order to uniquely identify an inner tx in a batch, we should concat the hash of the wrapper tx containing the inner txs (i.e. `tx.header_hash()`) with the hash of all the commitments, and compute a new hash which we now define as the actual hash of the inner tx.

**Comment by grarco** [comment]
Just a note: this is an problem from the UI/UX perspective, to our understanding there's no issue with the way we handle hashes in protocol.

Another option to the one suggested here above could be to mock a `Header` of a batch with a single transaction and then extract the `raw_header_hash`

**Comment by cwgoes** [comment]
Why do we need to uniquely identify inner transactions? Inner transactions aren't really transactions at all, they're more like atomic actions - perhaps we should call them "actions" instead.

**Comment by Fraccaman** [comment]
I think we dont want to break the user-model of: I can check a tx given its hash.

**Comment by cwgoes** [comment]
Yes; but inner txs are not "transactions" proper, they are parts of a transaction. When/why would a user need to look up something on the basis of only a specific action?

**Comment by Fraccaman** [comment]
For example: an exchange is batching withdraw transfers. Its better to show the user in the UI the specific "action/transaction" id with his specific transfer or the wrapper/batch id with hundred of actions/txs ?

**Comment by cwgoes** [comment]
I see - good point.
