### ISSUE TITLE
Malleable MASP Witness Data

### ISSUE THREAD

**Issue by murisi** [anoma/namada#3440]
The `MaspTx` section is identified by the TxId digest described https://zips.z.cash/zip-0244#txid-digest . This is problematic because the TxId digest does not cover witness data like zero-knowledge proofs, authorization signatures, and binding signatures meaning that those entries are malleable. We should probably hash MASP `Transaction` serialization bytes when trying to prevent tampering and the TxId digest to facilitate hardware wallet signing.

**Comment by cwgoes** [comment]
Good catch. I agree, we need to commit to this data. We should have no malleable data in transactions at all, really, not that I can think of at least.

**Comment by cwgoes** [comment]
@murisi This has since been fixed, right?

**Comment by grarco** [comment]
Closed by #3463
