### ISSUE TITLE
prometheus didnot get populated from main config.toml to cometbft/config/config.toml

### ISSUE THREAD

**Issue by msobh13** [anoma/namada#3493]
after editing prometheus field in config.toml located in main dir for the chain-ID seems to be  prometheus config  didnot get populated from that main config.toml to cometbft/config/config.toml . tried few times and having same results althought other filed got copied without issue 

`Namada v0.40.0
`

**Comment by msobh13** [comment]
`wasm_dir = "wasm"

[ledger]
genesis_time = "2024-07-06T07:23:42.000000000+00:00"
chain_id = "tududes-test.81efb06d86523ae4f"

[ledger.shell]
base_dir = "/home/medo/.local/share/namada/tududes-test.81efb06d86523ae4f"
storage_read_past_height_limit = 3600
db_dir = "db"
cometbft_dir = "cometbft"
tendermint_mode = "Full"

[ledger.cometbft]
proxy_app = "tcp://127.0.0.1:19901"
moniker = "CryptoSJnet"
fast_sync = true
db_backend = "goleveldb"
db_dir = "data"
log_level = "info"
log_format = "plain"
genesis_file = "config/genesis.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_state_file = "data/priv_validator_state.json"
priv_validator_laddr = ""
node_key_file = "config/node_key.json"
abci = "socket"
filter_peers = false

[ledger.cometbft.rpc]
laddr = "tcp://127.0.0.1:19902"
cors_allowed_origins = []
cors_allowed_methods = ["HEAD", "GET", "POST"]
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]
grpc_laddr = ""
grpc_max_open_connections = 900
unsafe = false
max_open_connections = 900
max_subscription_clients = 100
max_subscriptions_per_client = 5
timeout_broadcast_tx_commit = "10000ms"
max_body_bytes = 1000000
max_header_bytes = 1048576
tls_cert_file = ""
tls_key_file = ""
pprof_laddr = ""

[ledger.cometbft.p2p]
laddr = "tcp://0.0.0.0:19904"
external_address = "xxx.xxx.xxx.xxx:19904"
seeds = "tcp://0b690e2998d7f423646e608a5851bdfccb44648c@194.163.172.168:26656"
persistent_peers = "tcp://0bcb8ddc23a8cec2756cdc99750be36054da1f79@142.132.135.125:24656"
upnp = false
addr_book_file = "config/addrbook.json"
addr_book_strict = false
max_num_inbound_peers = 40
max_num_outbound_peers = 10
unconditional_peer_ids = ""
persistent_peers_max_dial_period = "0ms"
flush_throttle_timeout = "100ms"
max_packet_msg_payload_size = 1024
send_rate = 5120000
recv_rate = 5120000
pex = true
seed_mode = false
private_peer_ids = ""
allow_duplicate_ip = false
handshake_timeout = "20000ms"
dial_timeout = "3000ms"

[ledger.cometbft.mempool]
recheck = true
broadcast = true
wal_dir = ""
size = 5000
max_txs_bytes = 1073741824
cache_size = 10000
keep-invalid-txs-in-cache = false
max_tx_bytes = 1048576
max_batch_bytes = 0

[ledger.cometbft.consensus]
wal_file = "data/cs.wal/wal"
timeout_propose = "3000ms"
timeout_propose_delta = "500ms"
timeout_prevote = "1000ms"
timeout_prevote_delta = "500ms"
timeout_precommit = "1000ms"
timeout_precommit_delta = "500ms"
timeout_commit = "10000ms"
double_sign_check_height = 0
skip_timeout_commit = false
create_empty_blocks = true
create_empty_blocks_interval = "0ms"
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2000ms"

[ledger.cometbft.storage]
discard_abci_responses = false

[ledger.cometbft.tx_index]
indexer = "null"

[instrumentation]
prometheus = true
prometheus_listen_addr = ":19999"
max_open_connections = 3
namespace = "namada_SJ_Main_"


[ledger.cometbft.statesync]
enable = false
rpc_servers = ""
trust_height = 0
trust_hash = ""
trust_period = "168h0m0s"
discovery_time = "15000ms"
temp_dir = ""

[ledger.cometbft.fastsync]
version = "v0"

[ledger.ethereum_bridge]
mode = "RemoteEndpoint"
oracle_rpc_endpoint = "http://127.0.0.1:9945"
channel_buffer_size = 1000
`

**Comment by cwgoes** [comment]
Unfortunately we aren't able to debug your problem at the moment. Have you tried restarting the ledger? Closing for now, but feel free to reopen if you have any more specific instructions to reproduce the problem.

**Comment by msobh13** [comment]
Sorry I didnot update this , totaly forget about it . the issue was from my side was missing part of the `[instrumentation]` should be `ledger.cometbft.instrumentation` for dont know why it was missing this first part . Thanks @cwgoes
