### ISSUE TITLE
CLI Command Requests

### ISSUE THREAD

**Issue by Crypto-Druide** [anoma/namada#3522]
Hello,

Currently testing the PGF, we think that multiple commands could be usefull:
1) Command to query the current total supply
2) Command to retrieve the internal PoS and PGF addresses

Thank you.

**Comment by brentstone** [comment]
> 1. Command to query the current total supply

What exact functionality do you desire? The total supply of NAM or any token? In the code, for NAM we also distinguish the effective supply too, which does not take into account the PGF account balance.

> 2. Command to retrieve the internal PoS and PGF addresses

These addresses should already be loaded into your local wallet upon `join-network`. Check with `namada wallet list` - in the wallet they should be `pos` and `publicgoodfundings`.

**Comment by brentstone** [comment]
You can also get the total supply information with the SDK currently.

**Comment by Crypto-Druide** [comment]
Hi @brentstone ,
Thank you for your reply.

> What exact functionality do you desire? The total supply of NAM or any token? In the code, for NAM we also distinguish the effective supply too, which does not take into account the PGF account balance.

I'm talking about the total circulating supply of NAM (including the initial supply and all forms of inflation)
