### ISSUE TITLE
Transaction gets rejected when a user reattempts to enter the correct decryption password

### ISSUE THREAD

**Issue by zenodeapp** [anoma/namada#3525]
Hey,

A transaction gets rejected by VP as soon as the user fails at least one time to enter the correct decryption password. I've only tried this with a `transparent-transfer` and `bond` transaction, but this is likely an issue across the CLI.

```
Errors: [
  [
    "tnam1qpnl6yu488t2jskzn2rdf9cc24xxlue63cftcwj2",
    "Invalid transaction section signature: RuntimeError: The section signature is invalid: signature threshold not met: (0 < 1)"
  ]
]
```

> **Example**
> 1. `namadac transparent-transfer --source zen --target zen2 --token nam --amount 1`
> 2. Enter a _wrong_ password
> 3. Re-attempt with the _correct_ password
> 4. Transaction gets _rejected_ (gas fees do get deducted)

ZEN

**Comment by Crypto-Druide** [comment]
Hey ! 
I encountered the same problem.

**Comment by grarco** [comment]
I can confirm this is still an issue with `v0.43.0`: I will investigate the problem. Some more context here: I was able to reproduce this issue by inserting the wrong password first and the correct password the second time (currently the client gives the user only two attempts). If I get the password wrong both times and just try to resubmit the transaction I have no issues.

Also, we should print some error message to the user when the password is wrong cause at the moment we only prompt them for the password again without a response from the first try.

**Comment by grarco** [comment]
The issue is that the ux is misleading: we don't really support a retry mechanism for the password interactive process. The second prompt that you see refers to the signer of the wrapper transaction (in essence, the fee payer). So if you get the password wrong the first time but correct the second time, what happens is actually the following:

- The inner transactions does not get signed (hence the vp error on the signature threshold)
- The wrapper transaction gets correctly signed and submitted leading to a loss of the gas fees

**Comment by zenodeapp** [comment]
> The issue is that the ux is misleading: we don't really support a retry mechanism for the password interactive process. The second prompt that you see refers to the signer of the wrapper transaction (in essence, the fee payer). So if you get the password wrong the first time but correct the second time, what happens is actually the following:
> 
> * The inner transactions does not get signed (hence the vp error on the signature threshold)
> * The wrapper transaction gets correctly signed and submitted leading to a loss of the gas fees

Ah! That's why! Got it, makes sense now.
