### ISSUE TITLE
PoS validator consensus key change

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#36]
Add a tx and update PoS validity predicate to allow validators to change consensus key 

NOTE: how do we update this in tendermint? We currently using the key file on disk. The key change on-chain will happen in a future epoch, so we'd need to update the file at the right time.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763047146961) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@tzemanovic @brentstone do you know the status of this? we do need key rotation for mainnet. also, validators should be able to control this with their multisignature accounts.

**Comment by tzemanovic** [comment]
> @tzemanovic @brentstone do you know the status of this? we do need key rotation for mainnet. also, validators should be able to control this with their multisignature accounts.

we don't have this - I think changing consensus key itself should be pretty straight-forward, restarting tendermint at the right time might be finicky, but hopefully we can automate it

**Comment by cwgoes** [comment]
We shouldn't need to restart Tendermint at all - just pass a different key in the validator set changes.

**Comment by tzemanovic** [comment]
> We shouldn't need to restart Tendermint at all - just pass a different key in the validator set changes.

I'm not sure how this will work with KSM (#67), but without it, the consensus key is in a file in tendermint's dir. Because of the pipeline offset used when you change your consensus key, we need to switch the key in at the right time and I think this does necessitate TM restart, but I'm not 100% sure about it

**Comment by cwgoes** [comment]
Ah, I see - having the validator who is changing their key restart Tendermint makes sense, yeah.
