### ISSUE TITLE
Review `wasm_for_tests` deps

### ISSUE THREAD

**Issue by grarco** [anoma/namada#3606]
It looks like the Cargo files for the `wasm_for_tests` have been carried over from the `wasm` crate and include dependencies that might not be needed. This is especially true for dev-dependencies since we don't have tests for these wasm codes. We should review these dependencies and see if we can remove some.

**Comment by batconjurer** [comment]
My problem was that I had a goofed up merge from main. Once I fixed that, they built. But I haven't checked for unused deps.
