### ISSUE TITLE
`CheckTx` should reject transactions which cannot be charged

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#367]
When Tendermint receives a transaction from via RPC or gossiped from another Tendermint node, it should call `CheckTx` on the ledger and only accept the transaction into its mempool if it passes. This code path is currently around the `mempool_validate` method of the `Shell`.

https://github.com/anoma/namada/blob/d1a06a26abcfc8c3c0fd8904c020a79fac1ac52d/apps/src/lib/node/ledger/shell/mod.rs#L552-L566

We must not allow transactions into the mempool for which we could not incur some cost to the sender if the transaction were to be included in a block. This is to mitigate against mempool spamming. For example, we should check that the sender account of a regular transaction has sufficient `NAM` to at least pay some base cost if the transaction should fail, or a protocol transaction was crafted and signed by an active validator to prevent fake protocol transactions bloating the mempool. This should be specced out in more detail.

As a side effect, `CheckTx` will become more computationally expensive for nodes to run as it will involve e.g. verifying signatures. 

This issue is important for the Ethereum bridge as there will be various protocol transactions to be included in a block in a timely fashion, which mempool spamming may prevent. There is potentially mempool prioritization functionalityi n Tendermint that we could use, that may or may not be WIP.

**Comment by sug0** [comment]
Partially solved by https://github.com/anoma/namada/pull/817, which:

1) Checks if a protocol is indeed a `ProtocolTx`.
2) When 1 verifies, checks the validity of the protocol tx, including validating its signature against the public key of the validator in the protocol tx.

**Comment by cwgoes** [comment]
@grarco I think this falls under the scope of the fee system implementation?

**Comment by grarco** [comment]
Sort of. Speaking with @sug0 and @james-chf in the last few days we thought this issue might be a bit broader and non-trivial. It might be worth a discussion. For the moment, though, I think it actually falls under the fee system 👍🏻
