### ISSUE TITLE
Hard-code all governance proposal types to be 40%

### ISSUE THREAD

**Issue by gavinly** [anoma/namada#3683]
For mainnet, I think we should hard-code the quorum for all proposal types to be 40%.

So 40% quorum would be for PGF, PGF steward, and default proposals. Can leave the majority and supermajority values for now, but i think we should revisit this soon after mainnet launch, beginning with re-evaluating the proposal types.

ps there's a typo in the docs, see image
<img width="818" alt="image" src="https://github.com/user-attachments/assets/6efa01d4-2b28-4f7b-911c-86b9e4923298">

**Comment by brentstone** [comment]
This works with me. Any concerns or comments from @cwgoes or @Fraccaman? Also is trivial to do. Thx for pointing out the typo.

**Comment by brentstone** [comment]
Just for added context, currently the quorum is:
- 2/3 for default proposals
- 1/3 for PGF steward proposals and funding proposals submitted by a non-steward
- 1/3 to veto a funding proposals submitted by a steward (then just requires more nay than yay to veto)

**Comment by mike-u410** [comment]
TY, @gavinly! I don't see a need to raise quorum from 1/3 => 2/5 where applicable. We could narrow scope of this change to just the default proposal quorum adjustment from 2/3 => 2/5

**Comment by brentstone** [comment]
I agree, think it would be fine just to address default proposals with 2/3 --> 2/5

**Comment by cwgoes** [comment]
I concur with @mike-u410 and @brentstone here.

**Comment by gavinly** [comment]
lgmt! (sorry, late replying)
