### ISSUE TITLE
`Epochs::default()`uses block height 0 as the first block height of the first epoch

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#378]
In our `Epochs` struct, we should ensure we are returning `BlockHeight(1)` as the first block height of the first epoch, rather than `BlockHeight(0)`. This may work for tests but `BlockHeight(0)` is not a realistic block height for real Tendermint chains.

https://github.com/anoma/namada/blob/d1a06a26abcfc8c3c0fd8904c020a79fac1ac52d/shared/src/types/storage.rs#L621-L630

Related: https://github.com/anoma/namada/issues/377

**Comment by tzemanovic** [comment]
duplicate of https://github.com/anoma/namada/issues/648
