### ISSUE TITLE
The problem with allocating allocations.

### ISSUE THREAD

**Issue by profit7773** [anoma/namada#3793]
Good day!
I recently saw the project's latest token allocation list, and to my surprise I didn't find my wallet on that list(https://raw.githubusercontent.com/anoma/namada-genesis/main/balances.toml). I donated to the project on git coin, and once created a wallet and filled out a form to receive 600+ coins (it was some time ago). But now I can't see my wallet. I must note that I am a long-time appraiser of the project and have carefully followed all steps to obtain that allocation. Please solve this problem.
Best wishes Alex

**Comment by brentstone** [comment]
Github is not the proper forum to be asking this questions. Furthermore, you've provided no information to help us identify or verify your claims here.

Please use discord to raise this question.

**Comment by gavinly** [comment]
> Good day!
> I recently saw the project's latest token allocation list, and to my surprise I didn't find my wallet on that list(https://raw.githubusercontent.com/anoma/namada-genesis/main/balances.toml). I donated to the project on git coin, and once created a wallet and filled out a form to receive 600+ coins (it was some time ago). But now I can't see my wallet. I must note that I am a long-time appraiser of the project and have carefully followed all steps to obtain that allocation. Please solve this problem.
> Best wishes Alex

hi! can you please message me on Discord? i wonder if i can help: gavinly
