### ISSUE TITLE
Problem with token allocation

### ISSUE THREAD

**Issue by oleksiih2001** [anoma/namada#3815]
Hello
I donated to gitcoin but I was not included in the list to receive token allocation. Previously, I filled out an application to receive 700 coins. Please help me solve my problem. This is important to me, I like the project and have been supporting it for a long time.
tnam is tnam1qze3kad5nwwldwemcjv75ajkqy5xgqdp9q7mku7c
Please give me an answer

**Comment by brentstone** [comment]
If you desire support for this issue, please contact Gavin at gavinly on Discord
