### ISSUE TITLE
Wrong spending key balance of unshielding over IBC

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#3823]
As discovered by @batconjurer and @sug0 when testing shielding actions with mainnet Osmosis. The balance of the spending key in Namada unexpectedly displays an increased (doubled) number rather than the correct new decreased balance.

**Comment by brentstone** [comment]
This is potentially resolved by anoma/namada-masp-indexer/pull/21. @batconjurer to confirm

**Comment by batconjurer** [comment]
> This is potentially resolved by [anoma/namada-masp-indexer/pull/23](https://github.com/anoma/namada-masp-indexer/pull/23). @batconjurer to confirm
Indeed, that pr fixes the issue.

**Comment by batconjurer** [comment]
> This is potentially resolved by [anoma/namada-masp-indexer/pull/23](https://github.com/anoma/namada-masp-indexer/pull/23). @batconjurer to confirm
Indeed, that pr fixes the issue.
