### ISSUE TITLE
config file lacks of the respective state sync related field values to enable state sync snapshots creation

### ISSUE THREAD

**Issue by McDaan** [anoma/namada#3867]
I just tried to start syncing through state-sync method, but got this panic message while trying to start the node:
```
panic: Cannot create validator set: duplicate entry Validator{630DCD2966C4336691125448BBB25B4FF412A49C PubKeyEd25519{000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F} VP:10 A:0} in [Validator{24A0C7E4CC7071DAE09425B3288F327D57AC9E70 PubKeyEd25519{D4D1F9C35EAF605C115E4C9416C68754ED8F0D876E8AD3EFF18F52D1C25EFE06} VP:10 A:0} Validator{630DCD2966C4336691125448BBB25B4FF412A49C PubKeyEd25519{000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F} VP:10 A:0} Validator{630DCD2966C4336691125448BBB25B4FF412A49C PubKeyEd25519{000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F} VP:10 A:0}]
```
These are the config values I've used:
```
[ledger.cometbft.statesync]
enable = true
rpc_servers = "https://rpc.knowable.run:443,https://rpc.knowable.run:443"
trust_height = 37448
trust_hash = "71B06FA2F0D32FCA726D0B5A0766EE1E316541244DCD45EAB57741B4384065C0"
trust_period = "168h0m0s"
discovery_time = "15000ms"
temp_dir = ""
```
CometBFT version used is `0.37.11+c35675ead`
Namada version used is `v0.44.0`

Digging more into this, I have realized that most likely the main reason of the fail is due to lack of respective configuration field values in the config file in regard to the state sync snapshots creation - so, without them, nodes can't be able to create nor serve state sync snapshots. This is an example of them:
```

###############################################################################
###                        State Sync Configuration                         ###
###############################################################################

# State sync snapshots allow other nodes to rapidly join the network without replaying historical
# blocks, instead downloading and applying a snapshot of the application state at a given height.
[state-sync]

# snapshot-interval specifies the block interval at which local state sync snapshots are
# taken (0 to disable).
snapshot-interval = 0

# snapshot-keep-recent specifies the number of recent snapshots to keep and serve (0 to keep all).
snapshot-keep-recent = 2
```

**Comment by sug0** [comment]
I'm not sure what the problem you've run into is about, but we're able to start creating snapshots by setting `blocks_between_snapshots = $some_nonzero_value` under `[ledger.shell]`.

If the RPC servers you specified have enabled snapshot creation, as per the config option above, then they should be able to facilitate the State Sync protocol to proceed normally.

**Comment by sug0** [comment]
@McDaan let me know if you're able to start state sync this way, so I can close this issue

**Comment by McDaan** [comment]
> @McDaan let me know if you're able to start state sync this way, so I can close this issue

I just enabled those parameters in the RPC. Perhaps I'm missing something, but I'm still seeing this kind of panic message while trying to sync through state sync method (a clean `db` folder and a cometbft `data` folder with just a standard `priv_validator_state_json` file:
```
panic: Cannot create validator set: duplicate entry Validator{630DCD2966C4336691125448BBB25B4FF412A49C PubKeyEd25519{000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F} VP:10 A:0} in [Validator{630DCD2966C4336691125448BBB25B4FF412A49C PubKeyEd25519{000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F} VP:10 A:0} Validator{630DCD2966C4336691125448BBB25B4FF412A49C PubKeyEd25519{000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F} VP:10 A:0} Validator{AFCA7435AB4FF07732355E6C8E1A2FC50D3D6841 PubKeyEd25519{8FC404E6686907D517C78736ED6F8D646948E4D4FF54D5B9D51B3588090EDED3} VP:10 A:0}]
```

**Comment by McDaan** [comment]
Okay, just tried to do so without touching `db` and cometbft `data` folders and enabling state sync after running join network command. It worked now. Closing it.
