### ISSUE TITLE
`Namadac tx` broadcasting bugs

### ISSUE THREAD

**Issue by dan-u410** [anoma/namada#3875]
submitting a signed transaction to the chain requires private keys loaded which breaks offline signing:

```
$ namadac tx --tx-path $tx --signatures $tx.sig --owner view_only_account --node 'https://rpc.knowable.run' --gas-payer view_only_account
Error:
   0: unable to sign transaction with tpknam1qr...
```

the CLI also uses the private keys to submit `reveal the public key` type transactions during broadcast. If signing offline, the key isnt available at this time to submit this type of transaction

**Comment by dan-u410** [comment]
@Fraccaman please let me know if I can assist 😄

**Comment by grarco** [comment]
Hi @dan-u410, thanks for reporting this. This seems indeed the case, if you request to dump a tx to later sign it off-line we skip the check for the need of the `reveal_pk` tx so that the dumped batch does not contain it. When you later load it for submission we do this check and push an extra tx to the batch for which you don't have the signing key online.

We'll work on a fix

**Comment by grarco** [comment]
Spoken with @Fraccaman, seems like instead we want to be able to attach an offline wrapper signature, nothing to do with the reveal pk tx. We'll work on that

**Comment by dan-u410** [comment]
Hi @grarco sorry to be confusing on `reveal_pk`. Totally understand all your points! My main point is that the current `broadcast` command seems to add the `reveal_pk` tx to the batch somewhat erroneously. Ive already done that for my account but I am re-prompted for this many times

This is not as important as being able to sign fees offline - but wanted to flag! Simply attaching the offline wrapper signature is a great improvement

**Comment by grarco** [comment]
@dan-u410 we have a PR opened to address offline fee signing at #3900.

Could you report the version of the client you are using and the steps to reproduce the reveal pk issue? I can't manage to reproduce it and we also have a test for it so I'd like to have a better understanding of your specific case

**Comment by dan-u410** [comment]
hi @grarco just tested out the PR. working great & not encountering the pk issue mentioned previously anymore. apologies there but thanks for the work here! great to have a working offline flow
