### ISSUE TITLE
change votes per token PoS param to be per smallest denomination

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#391]
depends on #386 

In genesis, we want to configure the `votes_per_token` to be 1/100 vote per namnam. Currently, it's calculated from whole tokens, so we want to change to be able express votes per nano tokens (in parts-per-billion instead of basis points).

Note that our total staked whole tokens will be capped at around `i64::MAX / 8 / 10^7 = 115_292_150_460` (tendermint total voting power has upper limit of `i64::MAX / 8`) (related issue https://github.com/anoma/namada/issues/159)

**Comment by brentstone** [comment]
I'm wondering if we may have an issue in the above case by storing namnam as a `u64`. If the maximum whole staked tokens is capped at `115_292_150_460`, then let's say the max namnam is `115_292_150_460_000_000_000`, but this is about 6.25 times the value of `u64::MAX`. Perhaps an easy fix could be to reduce the `votes_per_token`.

**Comment by tzemanovic** [comment]
closing as #386 not gonna be implemented
