### ISSUE TITLE
SDK: estimation of shielded rewards to be earned

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#3933]
Provide an SDK query that can estimate rewards to be earned in the shielded pool, primarily to be used for an interface like Namadillo. For example, compute the expected NAM rewards at the next epoch due to holding an incentivized IBC asset `A`.

**Comment by grarco** [comment]
@batconjurer hasn't this been closed by #3974?

**Comment by batconjurer** [comment]
> @batconjurer hasn't this been closed by #3974?

Yes, I think I just forgot to ref it in the PR description
