### ISSUE TITLE
Allow any tx's fees to be paid with the MASP

### ISSUE THREAD

**Issue by sug0** [anoma/namada#3962]
Move `--disposable-gas-payer` and `--gas-spending-key` args to the `Tx` args. This way, any tx can pay gas fees using a MASP unshielding.

**Comment by grarco** [comment]
I'm actually against thi. This is the logic we had before and I moved those two args to the specific txs for which masp fee payment is strictly required. Do you have a use case in mind that would require this change?

**Comment by sug0** [comment]
ah ok. well, I just thought of this when I was working in one of your suggestions in #3954... then I'll close the issue
