### ISSUE TITLE
Build script: only use rustfmt for tonic build if it’s available 

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#40]
The build.rs scripts in apps and shared currently require rustfmt to build tonic, so the build fails if it’s not installed. This is not necessary, we should only enable this if rustfmt is available.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763319549983) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@juped is this still relevant? I see the PR above was closed but not sure why.

**Comment by tzemanovic** [comment]
> @juped is this still relevant? I see the PR above was closed but not sure why.

Still relevant, but the PR wasn't fully done

**Comment by tzemanovic** [comment]
prost update that fixed this has been done in https://github.com/anoma/namada/pull/1217
