### ISSUE TITLE
Error when quering for staking rewards in epoch 0

### ISSUE THREAD

**Issue by mateuszjasiuk** [anoma/namada#4014]
When we query the staking rewards in epoch 0 we get this msg:
```sh
Querying staking rewards rates...
Error in the query: Query("RPC error: Failure in: est_inflation_rate  》/《  last_staked_ratio", 1)
```
I did not debug this, but I assume this happens because  `last_staked_ratio` is `0`

**Comment by tzemanovic** [comment]
Ah yes, the `last_staked_ratio` is initialized to 0 at genesis and it won't be set the right value until the start of epoch 1. We can fix this by setting it the correct value after we apply genesis bonds, but it is unfortunately a consensus breaking change at this point.

@brentstone any thoughts?

**Comment by tzemanovic** [comment]
on a second thought, we could fix this in a slightly hacky way but without a breaking change - in the query for first epoch only we could calculate the locked ratio adhoc

**Comment by brentstone** [comment]
I think it is best that if rewards are not turned on, we should return a message noting as such. If rewards are turned on, then I think in principle we will never have this issue, since the `last_staked_ratio` will be set.
