### ISSUE TITLE
slimmer wasm build

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#41]
It looks that some dependencies (even when unused) end-up bloating the built wasm size, so we should investigate if we can remove some unnecessary dependencies from them (specifically, anything from the transitive deps from the shared crate imported via `vm_env` and now `vp_prelude`/`tx_prelude` crates).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763184725755) by [Unito](https://www.unito.io)

**Comment by murisi** [comment]
@cwgoes Sure! Will take a look at this...

**Comment by tzemanovic** [comment]
one thing that has a significant impact on the size of built wasm are allocations - see e.g. https://nickb.dev/blog/avoiding-allocations-in-rust-to-shrink-wasm-modules/

**Comment by tzemanovic** [comment]
I got some good results with disabling "std" and "clock" features in chrono which decreased most of the WASMs over 10 times, but I didn't get it fully done as there is a bunch of logic that depends on it that would need some modifications to get this to work. Most of it is in our `time.rs` module that we can feature guard
