### ISSUE TITLE
Fix end-to-end tests in CI for `eth-bridge-integration`

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#418]
Currently, many e2e tests don't pass for `eth-bridge-integration` in CI (although some that don't pass in CI might pass locally). This can be fixed now we are using a (relatively) stable v0.37 Tendermint version.

We run CI for every merge to `eth-bridge-integration` in https://github.com/anoma/namada/pull/394.

This issue can be closed once all the `#[ignore]`s introduced by https://github.com/anoma/namada/pull/514 have been removed, and those tests are passing.

**Comment by sug0** [comment]
Closing this issue, as https://github.com/anoma/namada/pull/646 seems to have fixed it
