### ISSUE TITLE
Validation about connection IDs for IBC client

### ISSUE THREAD

**Issue by yito88** [anoma/namada#42]
IBC needs to store IBC connection IDs for each IBC client.
However, there is no validation about "clients/{identifier}/connections" for now.

IBC VP has to check if a new connection ID is stored for the corresponding client when the connection is created.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763320081866) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@yito88 what is the status of this - have we done this already?

**Comment by yito88** [comment]
Aleks has worked on this in https://github.com/anoma/namada/tree/aleks/verify-ibc-connection-list. It hasn't been merged yet.
This issue is not fatal because the list is not used.
I'd like to merge it after updating `ibc-rs` (#840).

Only the IBC relayer would use the list. The current relayer can get it in another way.

**Comment by yito88** [comment]
Fixed by #1217
