### ISSUE TITLE
Add the Ethereum bridge pool

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#420]
The Ethereum bridge pool is a mempool-like store on Namada which holds transfers bound for Ethereum. User make batches of transactions from this pool along with merkle proofs and relay this over to our Ethereum smart contracts. 

 - [x] #421 
 - [x] #422
 - [x] #423
 - [x] #424
 - [x] #425
 - [x] #426

**Comment by cwgoes** [comment]
@batconjurer is this up-to-date?
