### ISSUE TITLE
Keep the signed merkle root of the Ethereum bridge pool updated

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#423]
This will have two implementations: one for vote extensions and one for without.

For vote extensions:
 - [x] Each validator signs the latest root and adds to their vote extensions
 - [ ] At every block, these signatures are aggregated and included in the block proposal to be included in storage.

Without vote extensions:
 - [x] Each validator signs the latest root and broadcasts it as a protocol tx
 - [x] These signatures appear on chain and we keep a tally of partial proofs of different merkle tree roots in storage.
 - [x] We maintain the latest root which has reached a quorum of signatures.

**Comment by cwgoes** [comment]
@batconjurer is this up-to-date?
