### ISSUE TITLE
`storage.last_height` should be an `Option<BlockHeight>`

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#454]
In our `Storage` struct, the type of the `last_height` field (representing the height of the most recently committed block) is just `BlockHeight`, but when a chain is first initialized, no block has yet been committed so it would be clearer if this was `Option<BlockHeight>` and initially `None` rather than `BlockHeight(0)` before the first block has been committed (or some other way of refactoring this to be clearer).

**Comment by tzemanovic** [comment]
it's kinda puke-y, but because cometBFT uses block height 1 for the first block, we can use 0 for when it's not initialized. This is being done in https://github.com/anoma/namada/pull/1993
