### ISSUE TITLE
`run_aux` should be able to manage any arbitrary number of tasks

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#459]
Currently `run_aux` in the `eth-bridge-integration` branch needs a hardcoded five `JoinHandle`s to manage (tendermint node, ABCI server, broadcaster, Ethereum fullnode, oracle). 

https://github.com/anoma/namada/blob/65fb781db1f5194de11a983a39b2166f40b7fb8f/apps/src/lib/node/ledger/mod.rs#L539-L545

This means if we don't want to run the Ethereum fullnode and/or oracle, we still need to provide dummy `JoinHandle`s that don't do anything. We could simplify our code by making `run_aux` work with only handles for mandatory components (i.e. tendermint node + ABCI server + broadcaster) so that we don't need to provide dummy handles for the Ethereum fullnode and/or oracle components if they aren't needed.

**Comment by james-chf** [comment]
Extra context: https://github.com/anoma/namada/pull/663#discussion_r1003023292

**Comment by sug0** [comment]
nope, we still spawn a dummy task that exits immediately for the eth oracle
