### ISSUE TITLE
cli: allow to set default arguments from config

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#47]
We should replace e.g. the hard-coded default `--ledger-address` with the one from the config file

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762914094269) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@Fraccaman do you know the status of this?

**Comment by tzemanovic** [comment]
to be done

**Comment by gavinly** [comment]
would be great to have this
