### ISSUE TITLE
PoS balance clarification

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#476]
Migrating this from the previous docs repo.

In `src/user-guide/ledger/pos.md` we have:

```
Because the PoS system is just an account, you can query its balance, which is the sum of all staked tokens:

anoma client balance --owner PoS
```

This is not quite true because tokens that are unbonded but not yet withdrawn are still locked in the PoS system and hence contribute to its balance. The actual staked tokens sum can be found from the PoS data, but we do not have any client command to query it yet.

Note, we're adding #339 which will make it possible to query the total stake.

**Comment by cwgoes** [comment]
@brentstone is this up-to-date?

**Comment by brentstone** [comment]
Looks like this statement has been moved to `documentation/docs/src/user-guide/ledger/staking.md`, and this is still relevant and true. Let's keep this open and I'll address it in a new PR soon for PoS specs and docs.
