### ISSUE TITLE
spec: explain how ibc works with the vp model

### ISSUE THREAD

**Issue by juped** [anoma/namada#485]
IBC is not designed for the VP model, but we have adapted it to the VP model. The spec should detail this design.

**Comment by cwgoes** [comment]
Possibly done; pending review.

**Comment by yito88** [comment]
We have  https://github.com/anoma/namada/blob/738fd69d6c77e395a8715ce223ce466fe9bb7c9a/documentation/specs/src/interoperability/ibc.md
Should I add more details?

**Comment by cwgoes** [comment]
All spec issues to be re-planned.
