### ISSUE TITLE
Fix compiling with `abcipp` and set up CI to check it

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#497]
ABCI 0.19 (formerly known as ABCI++) is coming in Tendermint v0.38 and will provide us with vote extensions, which was used by the original design of the Ethereum bridge. Code to do with it is guarded behind the `abcipp` flag, and `--no-default-features` should be used also. We should run CI to make sure that our ABCI 0.19 code continues to compile/pass tests.

Compiling with `abcipp` currently doesn't work on `main` or `eth-bridge-integration` branches (as of 2022-11-04). We should fix up in `main` first and have a CI job to at least `cargo check` it, then do the same for `eth-bridge-integration`.

- [ ] fix in `main` 
  - https://github.com/anoma/namada/pull/754
  - https://github.com/anoma/namada/pull/869
- [ ] fix in `eth-bridge-integration`
  - https://github.com/anoma/namada/pull/871
- [ ] CI in `main`
  - https://github.com/anoma/namada/pull/824
- [ ] CI in `eth-bridge-integration`

**Comment by james-chf** [comment]
This has broken a couple of times

**Comment by cwgoes** [comment]
@james-chf is this relevant any more?
