### ISSUE TITLE
Implement reward products

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#499]
Implement the reward product mechanism described in the [F1 Fee distribution](https://drops.dagstuhl.de/opus/volltexte/2020/11974/pdf/OASIcs-Tokenomics-2019-10.pdf) such that rewards are effectively auto-rebonded.

**Comment by brentstone** [comment]
Something to figure out:

If the rewards are auto-rebonded, then how should the voting power and total deltas be updated? Should the total and validator deltas be updated in place in accordance with the reward products? Should there be a way to ensure that the increase in stake due to rewards only affects the voting power starting at the `pipeline_offset`? When voting power is calculated, should we consult the reward products as well in addition to checking the total and validator deltas?

**Comment by tzemanovic** [comment]
We can probably take the same approach as slashing for rewards, which is to update the validators' `total_deltas` with calculated rewards at pipeline offset (eagerly) when it's calculated and individual bonds amount only when those bond are being withdrawn (lazily)

**Comment by brentstone** [comment]
Implemented in #714
