### ISSUE TITLE
Add a test that PrepareProposal returns the correct transactions in the response to Tendermint when proposing a block

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#502]
(Relates to https://github.com/anoma/namada/pull/494 but is more general than that PR)

When calling `PrepareProposal` with some txs from the mempool, we should check that the returned proposed block contains:

- *all* `ProtocolTxType::VoteExtension` protocol transactions that were passed to `PrepareProposal`
- appropriate vote extension digest transactions (i.e. `ProtocolTxType::EthereumEvents` and `ProtocolTxType::ValidatorSetUpdate`) based on the `ProtocolTxType::VoteExtension`s passed in
- roughly half of any wrapper transactions that were passed to `PrepareProposal`
- the rest of the returned transactions should be decrypted transactions

This can be a test in Rust code.

**Comment by cwgoes** [comment]
@sug0 I'm guessing that the block space allocator work might cover this?

**Comment by sug0** [comment]
@cwgoes yup

**Comment by sug0** [comment]
there's a test in `apps/src/lib/node/ledger/shell/block_space_alloc.rs` that covers this, and it should also be covered by PrepareProposal and ProcessProposal tests, therefore I'm closing the issue
