### ISSUE TITLE
Update the Ethereum bridge specs to account for vote extension digests with Tendermint v0.37

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#511]
In the Tendermint v0.38 design of the Ethereum bridge, all vote extensions in a given vote extension digest were guaranteed to have come from the same consensus round, and consequently all voting validators were guaranteed to be from the same active validator set. In the Tendermint v0.37 design, a vote extension digest may contain "vote extensions" from different consensus rounds and therefore possibly validators from different epochs, or multiple vote extensions from the same validator but for different consensus rounds. Review the specs and update accordingly. Some code has/is already being updated to handle this e.g. https://github.com/anoma/namada/pull/284

**Comment by cwgoes** [comment]
@batconjurer I'm guessing that this has been superseded by protocol transactions?

**Comment by batconjurer** [comment]
This isn't an issue for Protocol txs, true. But it will be worth investigating again once vote extensions drop.
