### ISSUE TITLE
Refactor the `Shell` and associated structs so that the fullnode and validator APIs are split up

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#521]
When users run a ledger node, whether as a fullnode or a validator, they are ultimately using a `Shell` component, which has an API which includes methods only relevant to validators e.g. `Shell::prepare_proposal` and other ABCI-related methods. On a `Shell`'s storage field, we also import an implementation of a trait called `QueriesExt` (introduced by the `eth-bridge-integration` branch), which has methods only relevant to validators such as `can_send_validator_set_update`. We should refactor so that fullnodes aren't exposed to the validator-only APIs, and the validator-only APIs don't need to have checks that they are being called by a validator and not a full node.

This is maybe worth doing post-Namada launch

**Comment by cwgoes** [comment]
No longer applicable.
