### ISSUE TITLE
Fix CI for `eth-bridge-integration` branches on our Rust dependency forks

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#537]
We should keep the CI we inherited from upstream green for our forks:

- [ ] [tendermint-rs](https://github.com/heliaxdev/tendermint-rs/tree/eth-bridge-integration)
- [ ] [ibc-rs](https://github.com/heliaxdev/ibc-rs/tree/eth-bridge-integration)
- [ ] [tower-abci](https://github.com/heliaxdev/tower-abci/tree/eth-bridge-integration)

At least straightforward CI jobs like fmt, clippy, cargo test. Involved CI jobs like gaia e2e tests for ibc-rs could be disabled for now and spun out into a separate issue.

**Comment by cwgoes** [comment]
We should move towards reintegration with the upstream (i.e. no forks) where possible.
