### ISSUE TITLE
Support for application-level Merkle trees

### ISSUE THREAD

**Issue by juped** [anoma/namada#55]
It may be best to specialize this to ZK commitment trees specifically, which is a common specific use case. Also requires gas metering.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762843415365) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@murisi did we do this as part of the MASP VP already?

**Comment by murisi** [comment]
@cwgoes @juped I believe this is done: we simply use the Merkle tree primitives from the `anoma/masp` crate. Specifically we have the `CommitmentTree` and `FrozenCommitmentTree` primitives, each providing different performance characteristics. However I don't believe that gas metering in the context of these Merkle trees has yet been handled...
