### ISSUE TITLE
Update event signatures for the new Ethereum bridge smart contracts

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#561]
We have some event signatures hard coded in the ledger:

https://github.com/anoma/namada/blob/85d554217bc5951f1ac77af42a963733ca88086a/apps/src/lib/node/ledger/ethereum_node/events.rs#L2-L11

These signatures need to checked to ensure they are up to date with changes made in https://github.com/anoma/ethereum-bridge as of commit https://github.com/anoma/ethereum-bridge/blob/87056f4c1fa5472e49adaf0793af1f2ecda9b5da

e.g. `TransferToNamada(uint256,address[],string[],uint256[],uint32)` should become `TransferToNamada(uint256,(address,uint256,string)[],uint256)`. 

Also the ABI decoding logic needs to be updated for raw event types, e.g. `RawTransfersToNamada`.

- [x] TransferToNamada (https://github.com/anoma/namada/pull/567)
- [ ] InvalidTransferToNamada (new event type)
- [ ] TransferToErc
- [ ] ValidatorSetUpdate
- [ ] NewContract
- [ ] UpgradedContract
- [ ] UpdateBridgeWhiteList

**Comment by cwgoes** [comment]
@james-chf could we do this as part of the autogenerated types, perhaps?

**Comment by james-chf** [comment]
Yep, the best way to solve this issue would be as part of https://github.com/anoma/namada/issues/986
