### ISSUE TITLE
Prevent redemption of wNAM more than the total amount of NAM actually on Ethereum

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#565]
On the Namada side, we will keep all NAM sent or being sent to Ethereum in an escrow account, so that account’s NAM balance tracks how much NAM is currently on Ethereum or pending being sent to Ethereum. 

We want to prevent redemption of wNAM more than the total amount of NAM that is actually on Ethereum. e.g. if 10 NAM is currently on Ethereum, Namada would enforce that at most 10 wNAM can be redeemed. A running total of how much NAM is on Ethereum needs to be kept track of on the Namada side, so that we can enforce this. One approach is we could listen to events from the Ethereum bridge smart contracts indicating when successful NAM transfers have happened.

**Comment by cwgoes** [comment]
@james-chf what's the status of this?

**Comment by james-chf** [comment]
Not started
