### ISSUE TITLE
Parts of the governance spec page contains broken rendering

### ISSUE THREAD

**Issue by adrianbrink** [anoma/namada#574]
<img width="1348" alt="Screen Shot 2022-10-10 at 18 20 34" src="https://user-images.githubusercontent.com/11320251/194911662-ab13e08a-1cf0-4bed-9dd4-06a3da29ea15.png">

This is the case in multiple instances on the [governance page]](https://specs.namada.net/base-ledger/governance.html).

**Comment by Fraccaman** [comment]
I have #460 that address this problem
