### ISSUE TITLE
Ethereum event oracle should only process blocks for when the node is an active validator

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#589]
Currently the oracle checks and processes all Ethereum blocks starting from the first Ethereum block. The oracle should be further updated to only check Ethereum blocks corresponding to when the node is an active validator.

For each Namada epoch, there could be some deterministic range of Ethereum blocks that should be checked by all active validators for that epoch. The ranges could be non-overlapping. This would require being able to work out what ranges of Ethereum nodes correspond to what Namada epoch in advance of a Namada epoch ending, so maybe isn't possible.

Alternatively, we could let each validator decide which blocks to check corresponding to a Namada epoch, and not define what they should check - this should be designed/specced out before we implement anything. Validators could start checking straight away as soon as a Namada epoch starts for which they are an active validator, and can (and should) stop checking as soon as a Namada epoch ends such that they are no longer an active validator.

**Comment by cwgoes** [comment]
At the very least we can have a configurable Ethereum block scan start height.

**Comment by james-chf** [comment]
Definitely - ideally this block scan start height should be stored somewhere and be updateable by the ledger node, as each validator needs to keep track of the latest Ethereum block height they have processed, so they can continue from an appropriate block height on node restart.

We don't have anything currently implemented for managing state that needs to be persisted between node restarts in general, but to start with for this feature, this could be as simple as a file in the chain directory under `.namada` that contains the latest Ethereum block height processed (and this should be set to or default to an appropriate initial value e.g. the Ethereum block height at which the smart contracts were deployed)
