### ISSUE TITLE
MASP wasm transactions

### ISSUE THREAD

**Issue by juped** [anoma/namada#59]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762857474696) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@murisi this is done, right?

**Comment by murisi** [comment]
@cwgoes Yes. This was done by embedding MASP `Transaction`s inside the `Transfer` transactions. To complete this approach, the `tx_transfer` WASM code had to be extended to append new MASP transactions onto the end of the transaction list owned by the MASP VP.
