### ISSUE TITLE
Slashable offense for voting on an unconfirmed event is not accounted as misbehavior (audit issue #7)

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#595]
This was finding 7 from the audit of `eth-bridge-integration` branch (commit 57fc202ea33df5072c9286f5ccb339537b1be885)

> Severity: Major
> When applying slashing validators in apps/src/lib/node/ledger/shell/mod.rs:525, EvidenceType gets matched with the SlashType. Voting on unconfirmed events is considered a slashable offense according to the provided documentation, but it is not accounted for as one of the variants of EvidenceType. This allows validators to vote on unconfirmed events. > This issue may be abused by malicious validators to double-spend funds.
> Recommendation
> We recommend adding the logic for slashing for the voting on unconfirmed events.

**Comment by james-chf** [comment]
The relevant specs documentation ([also in latest `eth-bridge-integration`](https://github.com/anoma/namada/blob/12ca4da092c4f5f54061783237d9ca7f30b3db51/documentation/specs/src/interoperability/ethereum-bridge/ethereum_events_attestation.md#L41-L43))

https://github.com/anoma/namada/blob/57fc202ea33df5072c9286f5ccb339537b1be885/documentation/specs/src/interoperability/ethereum-bridge/ethereum_events_attestation.md#L41-L43

Currently there is no slashing implemented for validators voting on events which are "unconfirmed" i.e. that have not yet reached enough block depth on the Ethereum chain to be considered safe to include on Namada chain and potentially act on. 

This still needs to be specced out and implemented - since different validators will likely have slightly different views of the longest Ethereum chain depending on how synced they are, we will need to allow some skew, but validators could vote on other validator's votes if they think that those are for events which are still new to be considered confirmed.

**Comment by cwgoes** [comment]
Hmm, I'm not sure that we can slash validators for signing Ethereum events with the "wrong" number of confirmations, at least not without running an Ethereum light client in the Namada state machine. We should be able to slash for validators signing incorrect Namada headers and relaying them to Ethereum, though - do we do that at the moment?

**Comment by james-chf** [comment]
> Hmm, I'm not sure that we can slash validators for signing Ethereum events with the "wrong" number of confirmations, at least not without running an Ethereum light client in the Namada state machine. 
Yeah, different Namada validators can also have different views of which events are deep enough in the Ethereum chain to be considered as confirmed or not, depending on their local Ethereum node's sync status (though their views should be relatively similar - Namada validators should ideally be staying as up to date as possible with the Ethereum chain at all times).

> We should be able to slash for validators signing incorrect Namada headers and relaying them to Ethereum, though - do we do that at the moment?
Not sure what you mean by headers, if you mean messages intended for the Ethereum bridge smart contracts (e.g. validator set updates), there currently isn't slashing implemented

**Comment by batconjurer** [comment]
We have decided that it is not possible to determine if a validator has voted on an unconfirmed event. As such, we will change the specs, and close this issue.
