### ISSUE TITLE
The total size in bytes of the transactions in a block proposal can exceed the block byte size limit (audit issue #10)

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#597]
This was finding 10 from the audit of `eth-bridge-integration` branch (commit 57fc202ea33df5072c9286f5ccb339537b1be885)

> Severity: Minor
> Tendermint expects the application to check whether the size of all transactions exceeds the byte limit RequestPrepareProposal.max_tx_bytes, which by default is set to 1048576 bytes. If so, the application must remove transactions at the end of the list until the total byte size is at or below the limit. However, the current implementation of Shell::prepare_proposal in apps/src/lib/node/ledger/shell/prepare_proposal.rs:48-57 does not enforce this limit. Therefore, if the transaction byte size limit surpasses the limit, Tendermint will reject the block.
> For more details, see [requirement number 2 in Tendermints' formal requirements](https://github.com/tendermint/tendermint/blob/main/spec/abci/abci++_app_requirements.md).
> Recommendation
> We recommend limiting the transactions within a proposed block accordingly to prevent surpassing the byte limit RequestPrepareProposal.max_tx_bytes.

**Comment by cwgoes** [comment]
@sug0 Has this been addressed as part of the block space allocator work?

**Comment by sug0** [comment]
@cwgoes yeah, exactly. it's no longer an issue
