### ISSUE TITLE
Randomize `storage.address_gen` with the chain ID

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#6]
we should add the chain id to have unique address on different chains

_Originally posted by tzemanovic in https://github.com/heliaxdev/anoma-prototype/pull/175#discussion_r628047089_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762993889182) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
Hmm, I'm not sure we want to do it this way, since we might change the chain ID of a running chain (with an upgrade) and we don't want the address format to change. Closing for now, but reopen if there's another reason which I didn't consider.

**Comment by tzemanovic** [comment]
> Hmm, I'm not sure we want to do it this way, since we might change the chain ID of a running chain (with an upgrade) and we don't want the address format to change. Closing for now, but reopen if there's another reason which I didn't consider.

ah sry, the issue's description isn't very clear - what I meant is to add the chain ID to the initial seed for on-chain generated addresses - I have something like this implemented in https://github.com/anoma/namada/pull/685 (WIP), where the seed starts from the genesis bytes. A change of chain ID won't affect format
