### ISSUE TITLE
Extended cryptographic primitives and storage support in wallet

### ISSUE THREAD

**Issue by juped** [anoma/namada#60]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762707394700) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@murisi this is done, right?

**Comment by murisi** [comment]
@cwgoes Yes. The wallet storage has been extended to store spending keys, viewing keys, and payment addresses. The MASP wallet also now provides primitives to generate spending keys, derive viewing keys from spending keys, and deriving payment addresses from viewing keys.
