### ISSUE TITLE
Include a check to ensure that a transfer is sent only if the slashed_amount is greater than 0 (audit issue #14)

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#603]
This was finding 14 from the audit of `eth-bridge-integration` branch (commit 57fc202ea33df5072c9286f5ccb339537b1be885)

> Severity: Informational
> In apps/proof_of_stake/src/lib.rs:881 the transfer method is called regardless of the amount being slashed.
> Recommendation
> We recommend checking if the slashed_amount is greater than 0 before calling transfer in apps/proof_of_stake/src/lib.rs:881.

**Comment by james-chf** [comment]
Relevant code in the `slash` fn which the Ethereum bridge will use once Ethereum bridge slashing logic is implemented: https://github.com/anoma/namada/blob/57fc202ea33df5072c9286f5ccb339537b1be885/proof_of_stake/src/lib.rs#L870-L886

The `slashed_amount` variable goes through being a `u64` before being converted to `Self::TokenAmount` and passed to the `transfer` fn. This is still the case in the latest code - https://github.com/anoma/namada/blob/12ca4da092c4f5f54061783237d9ca7f30b3db51/proof_of_stake/src/lib.rs#L937-L953

**Comment by tzemanovic** [comment]
With change to ceiling mul in #1830, slash rate and slashable token amount being greater than 0, the slash amount that's being transferred should always be non-zero. However, we're currently not transferring slashes, so we should check on this again with #1508

**Comment by cwgoes** [comment]
Not relevant.
