### ISSUE TITLE
Tracking: First stage MASP client support

### ISSUE THREAD

**Issue by juped** [anoma/namada#61]
* [x] anoma/namada#57 
* [x] anoma/namada#59 
* [x] anoma/namada#60

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762857150700) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@murisi this is done, right?

**Comment by murisi** [comment]
@cwgoes Yes. At this point we have a working MASP client supporting receiving/sending assets to shielded addresses and viewing balances at shielded addresses. The MASP wallet works with the MASP client too.
