### ISSUE TITLE
There is no programmatic safeguard to restart the chain if the bridge cannot be started (audit issue #17)

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#611]
This was finding 17 from the audit of `eth-bridge-integration` branch (commit 57fc202ea33df5072c9286f5ccb339537b1be885)

> Severity: Informational
> To bootstrap the bridge the chain needs to halt. If that halt lasts longer than the epoch period, there is a risk that time sync or epochs may be lost. In the current implementation, there is no programmatic guarantee that the bootstrapping of the bridge will not cause problems with epoch time sync.
> Recommendation
> We recommend bootstrapping the bridge at the beginning of an epoch to maximize the time available to coordinate the resumption of operations. We also recommend developing and communicating a fallback plan for the unlikely case that bootstrapping will not be finished in time.

**Comment by james-chf** [comment]
What to do in the case that the bridge cannot be launched is not currently specified (except that it must be possible).

https://github.com/anoma/namada/blob/a307a4c2aee5efa41eebefc0a68614b4ec27f29c/documentation/specs/src/interoperability/ethereum-bridge/bootstrapping.md#L60-L65

We should lay out the fallback plan. Most likely, the chain can just be restarted without any genesis `ethereum_bridge_params` specified (as are being added in https://github.com/anoma/namada/pull/575), and it will act just as before.

**Comment by batconjurer** [comment]
Epoch must meet both a minimum amount of time and a minimum number of blocks must be processed. So it is not possible to for a the bridge to take longer than an epoch to sync since validators cannot start producing new blocks until their bridge is activated.
