### ISSUE TITLE
Mismatch in initial block heights at genesis

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#648]
The initial block height of the chain according to `request::InitChain` from tower ABCI is 1 ([see code here](https://github.com/anoma/namada/blob/546a043f023e329b815d7cb6dfa49d33425a02a9/apps/src/lib/node/ledger/shell/init_chain.rs#L52-L55)), which does not match the initial block height of the chain in the namada protocol, which is 0.

The initial block height of 1 from tower ABCI is used to determine when the next epoch begins [right here](https://github.com/anoma/namada/blob/546a043f023e329b815d7cb6dfa49d33425a02a9/apps/src/lib/node/ledger/shell/init_chain.rs#L64-L69), so possibly epoch 1 (the second epoch) starts a block later than intended.

**Comment by james-chf** [comment]
Related: https://github.com/anoma/namada/issues/377

We should look to remove `BlockHeight(0)` from our code since it doesn't exist (and change `BlockHeight::default()` to be `BlockHeight(1)` instead of `BlockHeight(0)`)

**Comment by tzemanovic** [comment]
Good catch! Looks like we should be setting our block height from the `initial_height` we receive on init chain.

There's one place where `BlockHeight(0)` is used - in ABCI queries, where it's used as a special meaning for "last committed height"

**Comment by tzemanovic** [comment]
Additionally, we should initialize block.pre_epochs with empty `first_block_heights` and write it from init-chain too

**Comment by tzemanovic** [comment]
thanks @james-chf for clearing this up in another discussion. There is no genesis block, `InitChain` initialized state to be used for the first block, which will have the `BlockHeight(1)` - the confusing part for me was that `InitChain` request comes with `height = 1`, which really means "prepare the genesis state for the first block, which will have height 1".

The issue with `storage.block.pre_epochs` is actually wrong though - we should use the `InitChain` height to initialize its value.

**Comment by cwgoes** [comment]
@tzemanovic What still needs to be done here - just the block height type fix?

**Comment by tzemanovic** [comment]
> @tzemanovic What still needs to be done here - just the block height type fix?

the default value for `pred_epochs.first_block_heights` is incorrect - we're using 0 height, but it should be set from the value received in `init_chain` (typically 1)
