### ISSUE TITLE
RPC queries - refactor library code

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#66]
Move the RPC library code from `apps/src/lib/client/rpc.rs` to the `shared` Anoma crate. Factor out the code's side-effects to allow to query storage data with any client that `impl tendermint_rpc::client::Client` and return the typed values (e.g. `Result<pos::Bonds, QueryError>`. The prints back to stdout/stderr should be factored out and kept in the `apps` crate.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762840944343) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@grarco what is the status of this?

**Comment by grarco** [comment]
I used to have a PR for this one on the old repo (a few months back) that was failing some tests. After that, I've never come back to this one because of other tasks

**Comment by tzemanovic** [comment]
I think we could potentially make use of https://github.com/anoma/namada/pull/553 for this - I've used it to add client-only methods to it here https://github.com/anoma/namada/blob/5e26b4dd05dc8ac144ac19b3ab2a111f74d743f0/shared/src/ledger/queries/vp/mod.rs#L27

**Comment by sug0** [comment]
@cwgoes @tzemanovic I think this issue can be closed, right? The only missing task is getting rid of I/O (prints).

**Comment by tzemanovic** [comment]
Done in #925
