### ISSUE TITLE
tendermint KMS integration for validator consensus key

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#67]
Integrate, test and add docs for https://github.com/iqlusioninc/tmkms

**Comment by tzemanovic** [comment]
> @tzemanovic What is the current status of this issue? Is TMKMS supported?

it's to-do

**Comment by cwgoes** [comment]
@brentstone would you be able to take this on (after the PoS work), since it is related? shouldn't be too tricky. @tzemanovic can probably help

**Comment by brentstone** [comment]
> @brentstone would you be able to take this on (after the PoS work), since it is related? shouldn't be too tricky. @tzemanovic can probably help

Sure, sounds good.

**Comment by cwgoes** [comment]
This requires no additional work on our end, it seems.

**Comment by adrianbrink** [comment]
Horcrox support should be mentioned in the docs @bengtlofgren
