### ISSUE TITLE
Move away from using our current `web30` crate

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#672]
We use the [web30](https://github.com/althea-net/web30) crate for interacting with Ethereum JSON-RPC endpoints. Due to https://github.com/althea-net/web30/issues/4 , there is some difficulty with sharing the `web30::client::Web3` between threads, which means we have to do some odd things in our code with regards to spawning Tokio tasks and the like where this type is involved. We should move to a fork of `web30` that doesn't have this issue, or to some other Ethereum client crate altogether.

After that, we should get rid of the following sort of tech debt where still present.

- [ ] we have conditional imports using `#[cfg(test)]`, we should start using an (async) trait of some sort
https://github.com/anoma/namada/blob/3b6066ed34b41b4c1948658d350f76e7f4bbda49/apps/src/lib/node/ledger/ethereum_node/oracle.rs#L9-L10
https://github.com/anoma/namada/blob/3b6066ed34b41b4c1948658d350f76e7f4bbda49/apps/src/lib/node/ledger/ethereum_node/oracle.rs#L13-L14
- [ ] the spawning of the Tokio task that handles the Ethereum events oracle can probably be simplified a lot
https://github.com/anoma/namada/blob/3b6066ed34b41b4c1948658d350f76e7f4bbda49/apps/src/lib/node/ledger/ethereum_node/oracle.rs#L102-L121

**Comment by sug0** [comment]
Bumping up the priority of this issue, as it is required by the SDK to check if the Ethereum node is online

**Comment by sug0** [comment]
I think we still need `!Send` to be compatible with Namada's web inteface code, so we'll keep the `LocalSet` logic for now
