### ISSUE TITLE
simplified gas accounting

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#69]
Depends on anoma/anoma#875, anoma/anoma#876, anoma/namada#8

For the limited set of whitelisted VPs and txs that can be used in a network, we'd like to implement a simplified gas accounting system, where each VP and tx WASM code will have (almost) constant gas consumption.

This has at least 2 high-level components:
 - determining the gas consumed by a tx
 - turning the gas into tx fee and charging it from the tx source account

**Comment by grarco** [comment]
Closed in favor of #1010
