### ISSUE TITLE
Prevent changes to a vote tracked event that has already been seen or expired

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#693]

**Comment by sug0** [comment]
Since an event is considered seen, it will never be deleted from storage, and you can keep voting on it, which bloats up storage with new votes.

There's also the fact validators with very little stake can keep voting on forged events, thereby spamming storage. Eventually, we expire events that haven't reached the "seen" state (i.e. that haven't reached a quorum decision with >2/3 of the voting power behind it), so this is less of a problem.

**Comment by cwgoes** [comment]
@sug0 What should we do here? For one, I think we could expire votes from validators who aren't in the active set anymore (and not accept votes from validators currently not in the active set) - would that help?

**Comment by sug0** [comment]
regarding the first sub-issue, that should be a fairly easy fix: we just need to check the state of Ethereum events in storage, and immediately stop running tx code if "seen" is set to true.

@cwgoes regarding the second sub-issue: we never accept events from validators who aren't in the active set. but yeah, there is an issue with events from validators who aren't in the active set anymore not expiring. events should expire if:

- a validator unbonds (to avoid rebonding later and voting with another address)
- the event is not decided after some expiration period (probably coinciding with `pipeline_length` somehow? or `unbonding_length`, not sure which of the two is suitable here)

**Comment by cwgoes** [comment]
Agreed on both counts.

**Comment by sug0** [comment]
@cwgoes it's slightly annoying if a validator votes right before the end of an epoch, as there's no way to tell when an epoch is about to begin because it depends on a non-deterministic factor - time. we would need a way to refund users whose transfers for a corresponding event expired. as for events that need to expire, it might be feasible to simply iterate over a storage prefix for a given epoch. if the voting power behind the events is `<= 2/3`, we expire them, and refund users, somehow.

**Comment by sug0** [comment]
it'd be nice to know the latency in blocks for an ethereum event to be considered seen in production. we can probably estimate the length of an epoch in blocks, and use this value to determine when we should not vote for events again. this would reduce the need to refund a bunch of events right before an epoch ended

**Comment by james-chf** [comment]
> regarding the first sub-issue, that should be a fairly easy fix: we just need to check the state of Ethereum events in storage, and immediately stop running tx code if "seen" is set to true.

Yep (honest validators shouldn't be voting on already seen events, but while we don't have vote extensions, their votes for an event can potentially come in late i.e. after an event is confirmed - it should essentially be a noop when this happens) - this would be simple to implement

The expiry side of things is related to https://github.com/anoma/namada/issues/181. I think expiring events at the end of an epoch is the way to go - technically there is an "advantage" then to Ethereum events submitted at the beginning of an epoch vs the end of an epoch, in that they have a longer time period in which they can be confirmed, but this should be immaterial as valid events should be confirmed relatively quickly in any case by honest validators and the main thing is that events expire before a rebonding attack could take place (as described in https://github.com/anoma/namada/issues/181).

As part of implementing event expiration, we should make sure that votes can't be applied to expired events similarly to how they should not be able to be applied to already confirmed events.

**Comment by sug0** [comment]
> As part of implementing event expiration, we should make sure that votes can't be applied to expired events similarly to how they should not be able to be applied to already confirmed events.

I don't think this needs a special case. If an event expires, and a Byzantine validator votes on it again, the voting power behind it would reset, anyway, and it'd never reach >2/3 voting power. It would bloat up storage, though, which is annoying and something we should find a measure against IMO.

**Comment by cwgoes** [comment]
Makes sense. In that case I agree with your proposal, but for safety we probably have to allow refunds of tokens on the Ethereum side if an event is never confirmed by Namada, no? So maybe we should just put explicit block height timeouts in events, and refund tokens if the block height timeout has passed and the event hasn't been processed?

**Comment by batconjurer** [comment]
We just need to ensure that the timeout on ethereum is longer than the timeout on Namada. This can be checked when we do valset updates since those happen once an epoch. So after FACTOR epochs, we can time out eth side and refund.
