### ISSUE TITLE
Increase ledger code coverage based on tarpauling report

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#72]
We have a partial tarpaulin report on code coverage for this repository. This an issue for tracking the places in the base ledger where coverage needs to be increased.

 - [ ] anoma/namada#73 
 - [ ] anoma/anoma#894
 - [ ] Receiving a non-deserializable tx in `process_and_decode_proposal` in `apps/src/lib/node/ledger/shell/process_proposal.rs`
 - [ ] anoma/namada#75
 - [ ] anoma/namada#76 
 - [ ] anoma/namada#77

`apps/src/lib/node/ledger/shell/prepare_proposal.rs` is unclear as our report is only for the abci feature.

**Comment by tzemanovic** [comment]
the results might be a bit dated, we should try to re-iterate after running #71 (at least partially) again

**Comment by cwgoes** [comment]
@batconjurer is this still accurate?
