### ISSUE TITLE
Some `MockDB` methods are not fully implemented

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#732]
Affects v0.9.0

`MockDB` is a fake implementation of the `DB` trait but some methods are not fully implemented e.g.

https://github.com/anoma/namada/blob/6cbce4a4dcdd3811679f5eb4aa7c82f51dff74e6/shared/src/ledger/storage/mockdb.rs#L335-L342

There are some other methods which ignore passed in `height` parameters but are otherwise partially implemented. We should complete the implementation so that `MockDB` corresponds closer to how a real `DB` behaves, or otherwise refactor.

**Comment by tzemanovic** [comment]
I don't think we need this, feel free to re-open if there's a usecase
