### ISSUE TITLE
Consolidate IBC and wrapped ERC20 multitoken handling code

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#735]

**Comment by cwgoes** [comment]
cc @yito88 can we possibly merge these two implementations?

**Comment by james-chf** [comment]
To add some context (I should have added when opening the issue) - there are some helper functions used by ERC20 code defined in `core/src/ledger/eth_bridge/storage/wrapped_erc20s.rs` (e.g. `sub_prefix` fn) that could probably be replaced/merged with multitoken helper functionality in `core/src/types/token.rs`

**Comment by sug0** [comment]
Closed by https://github.com/anoma/namada/pull/1693
