### ISSUE TITLE
Increase code coverage for shell/finalize_block.rs

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#75]
Based on a partial code coverage report for tarpaulin, we should increase the code coverage of `apps/src/lib/node/ledger/shell/finalize_block.rs`. This following code paths should be covered 

- [ ] The `update_state` function (this covered in PR anoma/anoma#377 )
- [ ] Test finalize block on a tx with an invalid signature.
- [ ] Test `update_epoch`
- [ ] test a gas overflow

**Comment by cwgoes** [comment]
@batconjurer is this still accurate?

**Comment by brentstone** [comment]
@batconjurer @grarco @Fraccaman how relevant is this issue still?

**Comment by batconjurer** [comment]
> @batconjurer @grarco @Fraccaman how relevant is this issue still?

No. It's way too out of date.

**Comment by batconjurer** [comment]
No. It's way too out of date.
