### ISSUE TITLE
Increase code coverage for shell/queries

### ISSUE THREAD

**Issue by batconjurer** [anoma/namada#76]
Based on a partial code coverage report for tarpaulin, we should increase the code coverage of `apps/src/lib/node/ledger/shell/queries.rs`. This following code paths should be covered

- [x] the function `read_storage_value`
- [x] the function `read_storage_prefix`

**Comment by cwgoes** [comment]
@yito88 can you take this on in conjunction with the rocksdb work?

**Comment by yito88** [comment]
They are covered now.

https://github.com/anoma/namada/blob/d425dd59ef2c0227fac3ec11211502cff32564b4/shared/src/ledger/queries/shell.rs#L448

https://github.com/anoma/namada/blob/d425dd59ef2c0227fac3ec11211502cff32564b4/shared/src/ledger/queries/shell.rs#L460
