### ISSUE TITLE
Add commission rate transition to PoS VP state machine test

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#769]
From a thread of comments on #695:

We can however add a `Transition` for `ValidPosAction::ChangeCommissionRate`, for which the model would need to have a pre-condition that ensures that the new rate is less than or equal to the validator's `max_commission_rate_change` with respect to its last epoch's rate. I think this can be done in in the abstract SM by e.g. looking through `self.all_valid_actions().into_iter().rev()` for the last rate value (either from a previous `ValidPosAction::ChangeCommissionRate` or `ValidPosAction::InitValidator` if it's not been changed before) before the last epoch switch. However, the epoch switch is currently not preserved in the abstract state machine - we only have the current `epoch`, so we might need to change that first.

_Originally posted by @tzemanovic in https://github.com/anoma/namada/pull/695#discussion_r1019085202_

**Comment by cwgoes** [comment]
@brentstone Is this still applicable?

**Comment by brentstone** [comment]
> @brentstone Is this still applicable?

Yes, this ultimately wasn't covered in #695 and should still be done.

**Comment by cwgoes** [comment]
Does not apply anymore.
