### ISSUE TITLE
End-to-end IBC tests using the Hermes relayer

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada#773]
Before finalizing the Namada IBC integration, we need to have e2e tests with the Hermes relayer, as this is what validators & relayer operators will be using.

**Comment by yito88** [comment]
I made scripts to execute E2E tests.
- [ibc-rs' E2E test](https://github.com/heliaxdev/ibc-rs/tree/yuji/v0.14.0_namada/e2e/namada-test.sh)
It tests creating client/connection/channel and simple transfer (the balance changes are not checked) by Hermes commands. It also has passive tests (Hermes process monitors Namada and requests transactions).
- [E2E transfer test](https://github.com/heliaxdev/namada-ibc-docker/blob/master/transfer_test.sh)
It has transfer tests which are including transfer, transfer back(return a token to the source chain), relay transfer (transfer a token between 2 chains via the third chain), and relay transfer back. This script uses only the Namada CLI commands.

**Comment by cwgoes** [comment]
Thank you! Could we add these to CI, perhaps (cc @Fraccaman)? (it's not the most urgent though)
