### ISSUE TITLE
Parameter for the epoch window width of cubic slashing

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#789]
We currently have in the Specs:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/26880226/202019408-f9228e4a-9e84-47be-bbf5-2f314f164b21.png">

This issue tracks whether or not we want to do this with a parameter and if it would belong in the protocol or PoS params.

**Comment by cwgoes** [comment]
It should be symmetric, otherwise there are weird effects based on when slashes are detected. `(-n, +n)` would be reasonable, with `n` the parameter.

**Comment by brentstone** [comment]
Completed in #892
