### ISSUE TITLE
Add E2E tests for IBC between Anoma chains

### ISSUE THREAD

**Issue by yito88** [anoma/namada#79]
We need E2E tests to verify the IBC operations on Anoma.

This task focuses on the verification for IBC between two Anoma chains without a relayer.

### Test targets
- Client
  - [x] Create, update
- Connection
  - [x] Handshake to open a connection
- Channel
  - [x] Handshake to open a channel
  - [x] Close a channel
  - [x] Close a channel due to timeout
- ICS20 Token transfer
  - [x] Token transfer (escrow/unescrow/mint/burn)
  - [x] Refund due to timeout or ack failure
  - [x] Transfer via the third chain (Chain A -> Chain B -> Chain C)
  - [x] Transfer back via the thrid chain (Chain C -> Chain B -> Chain A)

**Comment by cwgoes** [comment]
@yito88 what is the status of this?

**Comment by yito88** [comment]
https://github.com/anoma/namada/blob/main/tests/src/e2e/ibc_tests.rs
