### ISSUE TITLE
switch wasm allocator

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#808]
we're currently using wee_alloc, which is not maintained. One option for replacement is https://github.com/yvt/rlsf (thanks @sug0 for the suggestion)

**Comment by cwgoes** [comment]
Is this something we can do quickly?

**Comment by sug0** [comment]
switching allocators is very easy, testing is the hard part

**Comment by tzemanovic** [comment]
I think we can set this to low prio for now. The wee alloc leak is hard to trigger and I suspect that in our context it might never happen, at least I haven't seen it so far.

We could try using the deliberately leaking alloc from https://github.com/Craig-Macomber/lol_alloc, which would probably be a good fit as tx/VP code is very short lived

**Comment by tzemanovic** [comment]
duplicate of #401
