### ISSUE TITLE
Update to Tendermint v0.37.0-rc1

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#825]
Currently our Tendermint v0.37.x fork (`0.1.4-abciplus`) is based off of this commit - https://github.com/heliaxdev/tendermint/commit/0b58342a46b1917a40d506e48e87448dcc8b3131 (from 2022-08-31). We need to update our fork to be based on the more recent Tendermint v0.37-rc1 (https://github.com/tendermint/tendermint/releases/tag/v0.37.0-rc1). The way we do patching for our Tendermint dependencies is off as well, this can be fixed at the same time, and CI for our forks can also be cleaned up a bit (https://github.com/anoma/namada/issues/537).

First, making the patching saner:
- [x] create a `ledger-main` branch for `tendermint-rs`, using the `tendermint-rs` version used in namada v0.10.1
- [x] create a `ledger-main` branch for `ibc-rs` and pin it to `tendermint-rs` version used in namada v0.10.1 (https://github.com/heliaxdev/ibc-rs/pull/11)
- [x] create a `ledger-main` branch for `tower-abci` and pin it to `tendermint-rs` version used in namada v0.10.1 (https://github.com/heliaxdev/tower-abci/pull/6)
- [x] update `tendermint-v0.37-integration` to use revisions from the `ledger-main` branches of tendermint-rs/ibc-rs/tower-abci, for `0.1.4-abciplus` (https://github.com/anoma/namada/pull/827)

Then
- [x] integrate v0.37.0-rc1 changes for `tendermint-rs`(https://github.com/heliaxdev/tendermint-rs/pull/10) into `ledger-main`
- [x] integrate v0.37.0-rc1 changes for `ibc-rs`(https://github.com/heliaxdev/ibc-rs/pull/9) into `ledger-main`
- [x] integrate v0.37.0-rc1 changes for `tower-abci`(https://github.com/heliaxdev/tower-abci/pull/5) into `ledger-main`
- [x] update https://github.com/heliaxdev/tendermint `ledger-main` to be based on upstream `v0.37.0-rc1` (https://github.com/heliaxdev/tendermint/pull/213)

- [ ] update Namada `main` to use newer revisions from the `ledger-main` branches of tendermint-rs/ibc-rs/tower-abci, for `0.1.4-abciplus + v0.37.0-rc1` (being done directly in https://github.com/anoma/namada/pull/838)
- [ ] update Namada `main` to build an updated Tendermint binary in CI (https://github.com/anoma/namada/pull/839)
- [ ] update Namada to run all tests against the updated Tendermint binary, and stop building the old one (https://github.com/anoma/namada/pull/872)

Anything that lands in `main` should ideally be using `tag` instead of `rev` or `branch` for any crates pulled in via `git` sources.

**Comment by sug0** [comment]
tags are generally better I think, since revisions are very opaque (as in, you can't really tell much about them unless you browse the corresponding git tree).

**Comment by james-chf** [comment]
It looks like we don't need our Tendermint fork anymore - the only differences between v0.37.0-rc1 and our fork is the addition of the events endpoint - https://github.com/tendermint/tendermint/compare/v0.37.0-rc1...heliaxdev:tendermint:ledger-main - which is not being used now

**Comment by tzemanovic** [comment]
closed in favor of #1349

**Comment by tzemanovic** [comment]
closed in favor of https://github.com/anoma/namada/issues/1349
