### ISSUE TITLE
protocol balance change events

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#84]
The ledger should attach an event to blocks in which some accounts' balances are modified by the protocol (e.g. wrapper tx fee charges, PoS slashing, future governance proposal refunds), to make the changes externally visible and index-able.

**Comment by cwgoes** [comment]
@tzemanovic do you know the current status of this?

**Comment by tzemanovic** [comment]
> @tzemanovic do you know the current status of this?

This is still open. We do have events that replaced tendermint ones from https://github.com/anoma/namada/pull/587 now, which should help a lot
