### ISSUE TITLE
Update ibc-rs to cosmos/ibc-rs

### ISSUE THREAD

**Issue by yito88** [anoma/namada#840]
`informalsystems/ibc-rs` has been split to [`cosmos/ibc-rs`](https://github.com/cosmos/ibc-rs) and [`informalsystems/hermes`](https://github.com/informalsystems/hermes).
The new version of ibc-rs has bug fixes and ICS20 implementation (also some breaking changes).
The redundant code can be removed from Namada.

**Comment by yito88** [comment]
the latest `v0.25.0` is also including the misbehaviour handling

**Comment by cwgoes** [comment]
I see, thanks. We should include this before mainnet but it is not blocking anything else so not the most urgent rn.

**Comment by yito88** [comment]
Done by #1217
