### ISSUE TITLE
Update Tendermint version in the project README

### ISSUE THREAD

**Issue by sug0** [anoma/namada#841]
The project README file instructs users to install Tendermint 0.34.x, which is no longer used. We should point users to our fork of Tendermint instead.

**Comment by rootulp** [comment]
I think this issue is obsolete because Tendermint 0.34.x is no longer explicitly mentioned in the [README.md](https://github.com/anoma/namada/blob/main/README.md).

Ref: https://github.com/anoma/namada/blob/b6714b5eca577c520b2b42b5f7f8048d46bb9d8b/README.md?plain=1#L30

**Comment by tzemanovic** [comment]
we should link to https://docs.namada.net/introduction/installing-cometbft now

**Comment by cwgoes** [comment]
This has been completed.
