### ISSUE TITLE
generalize `SignedTxData` to allow multiple signatures

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#85]
This is to allow transactions with multiple signatures (e.g. multi-sig VP or multiple transfers from different sources bundled in one tx).

A possible approach would be to replace the `sig` field with e.g.

```rust
pub struct SignedTxData {
    ...
    /// The signatures are produced on the unsigned tx (tx data concatenated
    /// with the tx code and the timestamp).
    pub sigs: BTreeMap<PublicKeyHash, common::Signature>,
}
```

So a VP looking for a signature can look it up from the sigs using the hash of its PK.

**Comment by cwgoes** [comment]
@grarco what is the status of this w.r.t. the multisignature VP?

**Comment by grarco** [comment]
We started addressing this with the specs of #680. We might close this in favor of #81  since they look very similar to me?

**Comment by grarco** [comment]
Close in favor of #81
