### ISSUE TITLE
client transfer check `--signer` or `--signing-key` for shielded transfer

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#862]
We should improve the client when sending a shielded to shielded or shielded to transparent transfer to catch when `--signer` or `--signing-key` is not specified, otherwise it fails on trying to reveal the sentinel PK, which is confusing

**Comment by cwgoes** [comment]
@murisi Can you check on this? If no longer applicable, can you close it?

**Comment by cwgoes** [comment]
Closing since this appears to be out-of-date, but please reopen if I'm mistaken.
