### ISSUE TITLE
Ensure we wait for the RPC server to start in all e2e tests, before making any client calls

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#867]
In many of our e2e tests, we wait for the ledger node to start up by looking for a string like below:

```rust
    validator_0.exp_string("Anoma ledger node started")?;
```

We often want to make client calls straight after (e.g. `namadac tx`), these require that the RPC server has started up, which we can check by awaiting for this string:

```rust
    validator_0.exp_string("Starting RPC HTTP server on")?;
```

Sometimes tests can flake locally as the client call is made before the RPC server is started. We should ensure we await the RPC server to be started in any tests where that is required - we could factor out a helper function to do this, which would also reduce code duplication.

**Comment by sug0** [comment]
Related to #644

**Comment by james-chf** [comment]
The string "Starting RPC HTTP server on" doesn't seem to be present on `main` branch, only `eth-bridge-integration`, so we could port it back

**Comment by cwgoes** [comment]
Seems to be fixed.
