### ISSUE TITLE
client `init-validator` transaction command should update config

### ISSUE THREAD

**Issue by tzemanovic** [anoma/namada#88]
the `init-validator` command should update the Anoma config after it successfully applies the transaction to set `ledger.tendermint.tendermint_node = "Validator"`

**Comment by cwgoes** [comment]
@brentstone can you check on this / take this on if necessary as part of the PoS work?

**Comment by brentstone** [comment]
> @brentstone can you check on this / take this on if necessary as part of the PoS work?

Sure.

**Comment by tzemanovic** [comment]
this has been done somewhere
