### ISSUE TITLE
Bind specified IP for port 26656

### ISSUE THREAD

**Issue by DaveWK** [anoma/namada#930]
Currently when the node runs, port 26656 is bound to `0.0.0.0:26656` -- in some instances such as with NAT or with multiple NICs, this will over-expose traffic to un-intended IP's.

Example: 
Public IP: 1.1.1.1
Public NIC: 192.168.1.2
Private NIC: 192.168.5.2

I want to be able to specify `192.168.1.2:26656` as the "listener" address so that there is no traffic sent/received on `192.168.5.2:26656`, which would be the case if the app is listening on `0.0.0.0:26656`

**Comment by DaveWK** [comment]
This functionality exists (thanks Fraccaman!) -- in the `config.toml` there is a parameter called `p2p_address` which can be adjusted from `0.0.0.0:26656` to the desired value. I would suggest adding a section to the docs for the `config.toml` params to avoid confusion

**Comment by DaveWK** [comment]
After getting it up and running, I noticed that the `listen_address` being advertised by tendermint was my private IP. I had to change the tendermint config toml from:
`external_address = ""`
to:
`external_address = "tcp://<Public IP Goes here>:26656"`

**Comment by bengtlofgren** [comment]
Sorry, this was assigned to the wrong person, I will update the docs promptly. Sorry for the wait @DaveWK
