### ISSUE TITLE
Apply inflationary rewards to voting power

### ISSUE THREAD

**Issue by brentstone** [anoma/namada#939]
Need to decide how/when to apply inflationary rewards to voting powers. Voting power for consensus-participating validators and for validators and delegators participating in governance must consider inflationary rewards.

Current idea is for rewards to contribute to voting power at `pipeline_len` epochs after the rewards are *distributed* via the rewards products, as this is consistent with the current epoched staking model. Having rewards contribute to voting power immediately can cause issues for fixing a validator set in advance in order to run a DKG.

**Comment by tzemanovic** [comment]
I'm in favor of `pipeline_len` offset for "auto-bonding" to behave like a bonding tx, as these can also affect validator sets (even if they are small changes)

**Comment by cwgoes** [comment]
Agreed with rewards contributing to voting power after `pipeline_len` epochs.

**Comment by tzemanovic** [comment]
we won't be auto-bonding rewards for now

**Comment by cwgoes** [comment]
This is no longer planned.
