### ISSUE TITLE
Documentation for setting up a local chain as a developer

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#95]
The local chain should
* run a single genesis validator node by default (as does the devchain made when using `ANOMA_DEV=true`)
* have a faucet just like our testnets
* work with our [user guide](https://docs.anoma.net/user-guide/index.html) - ie it should have predefined any tokens that may be used in the guide, like `XAN`

**Comment by cwgoes** [comment]
@bengtlofgren we should include this in the docs at some point (but low priority)

**Comment by james-chf** [comment]
Related, working on sharing a script I'm using locally (`build_network.sh`) in this PR - https://github.com/anoma/devchain-container/pull/8 - that can configure a local Namada chain
