### ISSUE TITLE
Can’t up node after update to 0.12.2

### ISSUE THREAD

**Issue by Romainua** [anoma/namada#957]
Can’t run node after update, any way yo solve it? Screenshot is added
![10 13 33](https://user-images.githubusercontent.com/44613085/209307860-56b3d85c-87c3-4ca5-8168-cd53d76c005f.png)

**Comment by tzemanovic** [comment]
It seems you're using an incompatible tendermint version. You can either use https://github.com/anoma/namada/blob/main/scripts/get_tendermint.sh to install it into `/usr/local/bin` or install from https://github.com/heliaxdev/tendermint/releases/tag/v0.1.4-abciplus and use `TENDERMINT=path/to/tendermint` to run the node.

You may also need to rm the base dir (`.namada` by default) and start again, as the incompatible version would have written a tendermint config into it that won’t work with the supported version
